/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/organizations/{organizationId}/endpoints": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get a list of resolved Custom API endpoints.
         * @description List resolved Custom API endpoints, including not registered endpoints.
         */
        get: operations["getEndpoints"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * @description An identifier for the organization the request is being made by
         * @example f_ecom_zzxy_prd
         */
        OrganizationId: string;
        /**
         * @example active
         * @enum {string}
         */
        EndpointStatus: "active" | "not_registered";
        /**
         * Format: int32
         * @description Maximum records to retrieve per request, not to exceed the maximum defined. A limit must be at least 1 so at least one record is returned (if any match the criteria).
         * @default 10
         * @example 10
         */
        Limit: number;
        /**
         * Format: int32
         * @description The total number of hits that match the search's criteria. This can be greater than the number of results returned as search results are pagenated.
         * @default 0
         * @example 10
         */
        Total: number;
        /**
         * @description Schema defining generic list result. Each response schema of a resource requiring a list response should extend this schema.
         *     Additionally it needs to be defined what data is returned.
         */
        ResultBase: {
            limit: components["schemas"]["Limit"];
            total: components["schemas"]["Total"];
        };
        CustomApiEndpointFilter: {
            /**
             * @example not_registered
             * @enum {string}
             */
            status?: "active" | "not_registered";
        };
        /**
         * @description The identifier of the site that a request is being made in the context of. Attributes might have site specific values, and some objects may only be assigned to specific sites
         * @example RefArch
         */
        SiteId: string;
        CustomApiEndpoint: {
            /** @example loyalty-info */
            apiName?: string;
            /** @example v1 */
            apiVersion?: string;
            /** @example test_bc_wapi */
            cartridgeName?: string;
            /** @example /customers */
            endpointPath?: string;
            /** @example API schema not found. */
            errorReason?: string;
            /**
             * @example GET
             * @enum {string}
             */
            httpMethod?: "GET" | "POST" | "PUT" | "DELETE" | "PATCH" | "OPTIONS" | "HEAD";
            /** @example 10bd7f2dc40ab7aede7f0d60e5c3a783 */
            id?: string;
            /** @example script.js */
            implementationScript?: string;
            /** @example getLoyaltyInfo */
            operationId?: string;
            /**
             * @example ShopperToken
             * @enum {string}
             */
            securityScheme?: "ShopperToken" | "AmOAuth2";
            /** @example schema.yaml */
            schemaFile?: string;
            siteId?: components["schemas"]["SiteId"];
            status?: components["schemas"]["EndpointStatus"];
        };
        CustomApiEndpointResult: {
            filter?: components["schemas"]["CustomApiEndpointFilter"];
            data?: components["schemas"]["CustomApiEndpoint"][];
            /** @example version1 */
            activeCodeVersion?: string;
        } & components["schemas"]["ResultBase"];
        ErrorResponse: {
            /**
             * @description A short, human-readable summary of the problem
             *     type.  It will not change from occurrence to occurrence of the
             *     problem, except for purposes of localization
             * @example You do not have enough credit
             */
            title: string;
            /**
             * @description A URI reference [RFC3986] that identifies the
             *     problem type.  This specification encourages that, when
             *     dereferenced, it provide human-readable documentation for the
             *     problem type (e.g., using HTML [W3C.REC-html5-20141028]).  When
             *     this member is not present, its value is assumed to be
             *     "about:blank". It accepts relative URIs; this means
             *     that they must be resolved relative to the document's base URI, as
             *     per [RFC3986], Section 5.
             * @example NotEnoughMoney
             */
            type: string;
            /**
             * @description A human-readable explanation specific to this occurrence of the problem.
             * @example Your current balance is 30, but that costs 50
             */
            detail: string;
            /**
             * @description A URI reference that identifies the specific
             *     occurrence of the problem.  It may or may not yield further
             *     information if dereferenced.  It accepts relative URIs; this means
             *     that they must be resolved relative to the document's base URI, as
             *     per [RFC3986], Section 5.
             * @example /account/12345/msgs/abc
             */
            instance?: string;
        } & {
            [key: string]: unknown;
        };
    };
    responses: never;
    parameters: {
        /**
         * @description An identifier for the organization the request is being made by
         * @example f_ecom_zzxy_prd
         */
        organizationId: components["schemas"]["OrganizationId"];
        status: components["schemas"]["EndpointStatus"];
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    getEndpoints: {
        parameters: {
            query?: {
                status?: components["parameters"]["status"];
            };
            header?: never;
            path: {
                /**
                 * @description An identifier for the organization the request is being made by
                 * @example f_ecom_zzxy_prd
                 */
                organizationId: components["parameters"]["organizationId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful operation */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CustomApiEndpointResult"];
                };
            };
            /** @description Invalid or malformed filter parameter */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
}
