/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/organizations/{organizationId}/metrics/overall": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getOverallMetrics"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/organizations/{organizationId}/metrics/sales": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getSalesMetrics"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/organizations/{organizationId}/metrics/ecdn": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getEcdnMetrics"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/organizations/{organizationId}/metrics/third-party": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getThirdPartyMetrics"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/organizations/{organizationId}/metrics/scapi": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getScapiMetrics"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/organizations/{organizationId}/metrics/scapi-hooks": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getScapiHooksMetrics"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/organizations/{organizationId}/metrics/mrt": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getMrtMetrics"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/organizations/{organizationId}/metrics/controller": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getControllerMetrics"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/organizations/{organizationId}/metrics/ocapi": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getOcapiMetrics"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        OrganizationId: string;
        MetricId: string;
        DataSeriesId: string;
        DataPoint: {
            timestamp: number;
            value: number;
        };
        DataSeries: {
            id: components["schemas"]["DataSeriesId"];
            name: string;
            data: components["schemas"]["DataPoint"][];
        };
        Metric: {
            metricId: components["schemas"]["MetricId"];
            title: string;
            description: string;
            unit?: string;
            dataSeries: components["schemas"]["DataSeries"][];
        };
        MetricsDataResponse: {
            data: components["schemas"]["Metric"][];
        };
        ErrorResponse: {
            title: string;
            type: string;
            detail: string;
            instance?: string;
        } & {
            [key: string]: unknown;
        };
        InvalidTimeParameterErrorResponse: {
            parameter: string;
        } & components["schemas"]["ErrorResponse"];
        InvalidTimeRangeErrorResponse: {
            /** Format: int64 */
            fromValue: number;
            /** Format: int64 */
            toValue: number;
        } & components["schemas"]["ErrorResponse"];
        CategoryNotFoundErrorResponse: {
            category?: string;
            organizationId?: components["schemas"]["OrganizationId"];
        } & components["schemas"]["ErrorResponse"];
        MetricsNotAvailableErrorResponse: {
            organizationId?: components["schemas"]["OrganizationId"];
        } & components["schemas"]["ErrorResponse"];
        ThirdPartyServiceId: string;
        InvalidThirdPartyServiceErrorResponse: {
            thirdPartyServiceId: components["schemas"]["ThirdPartyServiceId"];
            organizationId: components["schemas"]["OrganizationId"];
        } & components["schemas"]["ErrorResponse"];
        InvalidApiFilterErrorResponse: {
            filterName: string;
            filterValue: string;
        } & components["schemas"]["ErrorResponse"];
    };
    responses: {
        /** @description Successfully retrieved overall application metrics for the requested time window */
        OverallMetricsResponse: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["MetricsDataResponse"];
            };
        };
        /** @description Bad request — invalid time parameters */
        BadRequestTimeResponse: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["InvalidTimeParameterErrorResponse"] | components["schemas"]["InvalidTimeRangeErrorResponse"];
            };
        };
        /** @description Your access token is invalid or expired and can’t be used to identify a user. */
        "401unauthorized": {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["ErrorResponse"];
            };
        };
        /** @description Forbidden. Your access token is valid, but you don’t have the required permissions to access the resource. */
        "403forbidden": {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["ErrorResponse"];
            };
        };
        /** @description Metrics category not available for the organization */
        CategoryNotFoundResponse: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["CategoryNotFoundErrorResponse"];
            };
        };
        /** @description Metrics data temporarily unavailable */
        ServiceUnavailableResponse: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["MetricsNotAvailableErrorResponse"];
            };
        };
        /** @description Successfully retrieved sales metrics for the requested time window */
        SalesMetricsResponse: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["MetricsDataResponse"];
            };
        };
        /** @description Successfully retrieved eCDN metrics for the requested time window */
        EcdnMetricsResponse: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["MetricsDataResponse"];
            };
        };
        /** @description Successfully retrieved third party service metrics for the requested time window */
        ThirdPartyMetricsResponse: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["MetricsDataResponse"];
            };
        };
        /** @description Bad request — invalid time parameters or third party service filter */
        BadRequestThirdPartyResponse: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["InvalidTimeParameterErrorResponse"] | components["schemas"]["InvalidTimeRangeErrorResponse"] | components["schemas"]["InvalidThirdPartyServiceErrorResponse"];
            };
        };
        /** @description Successfully retrieved SCAPI metrics for the requested time window */
        ScapiMetricsResponse: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["MetricsDataResponse"];
            };
        };
        /** @description Bad request — invalid time parameters or SCAPI filter value */
        BadRequestScapiResponse: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["InvalidTimeParameterErrorResponse"] | components["schemas"]["InvalidTimeRangeErrorResponse"] | components["schemas"]["InvalidApiFilterErrorResponse"];
            };
        };
        /** @description Successfully retrieved SCAPI hooks metrics for the requested time window */
        ScapiHooksMetricsResponse: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["MetricsDataResponse"];
            };
        };
        /** @description Successfully retrieved Managed Runtime metrics for the requested time window */
        MrtMetricsResponse: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["MetricsDataResponse"];
            };
        };
        /** @description Successfully retrieved controller metrics for the requested time window */
        ControllerMetricsResponse: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["MetricsDataResponse"];
            };
        };
        /** @description Successfully retrieved OCAPI metrics for the requested time window */
        OcapiMetricsResponse: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["MetricsDataResponse"];
            };
        };
        /** @description Bad request — invalid time parameters or OCAPI filter value */
        BadRequestOcapiResponse: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["InvalidTimeParameterErrorResponse"] | components["schemas"]["InvalidTimeRangeErrorResponse"] | components["schemas"]["InvalidApiFilterErrorResponse"];
            };
        };
    };
    parameters: {
        organizationId: components["schemas"]["OrganizationId"];
        from: number;
        to: number;
        thirdPartyServiceId: components["schemas"]["ThirdPartyServiceId"];
        apiFamily: string;
        apiName: string;
        ocapiCategory: string;
        ocapiApi: string;
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    getOverallMetrics: {
        parameters: {
            query?: {
                from?: number;
                to?: number;
            };
            header?: never;
            path: {
                organizationId: components["schemas"]["OrganizationId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successfully retrieved overall application metrics for the requested time window */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MetricsDataResponse"];
                };
            };
            /** @description Bad request — invalid time parameters */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["InvalidTimeParameterErrorResponse"] | components["schemas"]["InvalidTimeRangeErrorResponse"];
                };
            };
            /** @description Your access token is invalid or expired and can’t be used to identify a user. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Forbidden. Your access token is valid, but you don’t have the required permissions to access the resource. */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Metrics category not available for the organization */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["CategoryNotFoundErrorResponse"];
                };
            };
            /** @description Metrics data temporarily unavailable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["MetricsNotAvailableErrorResponse"];
                };
            };
        };
    };
    getSalesMetrics: {
        parameters: {
            query?: {
                from?: number;
                to?: number;
            };
            header?: never;
            path: {
                organizationId: components["schemas"]["OrganizationId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successfully retrieved sales metrics for the requested time window */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MetricsDataResponse"];
                };
            };
            /** @description Bad request — invalid time parameters */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["InvalidTimeParameterErrorResponse"] | components["schemas"]["InvalidTimeRangeErrorResponse"];
                };
            };
            /** @description Your access token is invalid or expired and can’t be used to identify a user. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Forbidden. Your access token is valid, but you don’t have the required permissions to access the resource. */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Metrics category not available for the organization */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["CategoryNotFoundErrorResponse"];
                };
            };
            /** @description Metrics data temporarily unavailable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["MetricsNotAvailableErrorResponse"];
                };
            };
        };
    };
    getEcdnMetrics: {
        parameters: {
            query?: {
                from?: number;
                to?: number;
            };
            header?: never;
            path: {
                organizationId: components["schemas"]["OrganizationId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successfully retrieved eCDN metrics for the requested time window */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MetricsDataResponse"];
                };
            };
            /** @description Bad request — invalid time parameters */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["InvalidTimeParameterErrorResponse"] | components["schemas"]["InvalidTimeRangeErrorResponse"];
                };
            };
            /** @description Your access token is invalid or expired and can’t be used to identify a user. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Forbidden. Your access token is valid, but you don’t have the required permissions to access the resource. */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Metrics category not available for the organization */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["CategoryNotFoundErrorResponse"];
                };
            };
            /** @description Metrics data temporarily unavailable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["MetricsNotAvailableErrorResponse"];
                };
            };
        };
    };
    getThirdPartyMetrics: {
        parameters: {
            query?: {
                from?: number;
                to?: number;
                thirdPartyServiceId?: components["schemas"]["ThirdPartyServiceId"];
            };
            header?: never;
            path: {
                organizationId: components["schemas"]["OrganizationId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successfully retrieved third party service metrics for the requested time window */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MetricsDataResponse"];
                };
            };
            /** @description Bad request — invalid time parameters or third party service filter */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["InvalidTimeParameterErrorResponse"] | components["schemas"]["InvalidTimeRangeErrorResponse"] | components["schemas"]["InvalidThirdPartyServiceErrorResponse"];
                };
            };
            /** @description Your access token is invalid or expired and can’t be used to identify a user. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Forbidden. Your access token is valid, but you don’t have the required permissions to access the resource. */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Metrics category not available for the organization */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["CategoryNotFoundErrorResponse"];
                };
            };
            /** @description Metrics data temporarily unavailable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["MetricsNotAvailableErrorResponse"];
                };
            };
        };
    };
    getScapiMetrics: {
        parameters: {
            query?: {
                from?: number;
                to?: number;
                apiFamily?: string;
                apiName?: string;
            };
            header?: never;
            path: {
                organizationId: components["schemas"]["OrganizationId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successfully retrieved SCAPI metrics for the requested time window */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MetricsDataResponse"];
                };
            };
            /** @description Bad request — invalid time parameters or SCAPI filter value */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["InvalidTimeParameterErrorResponse"] | components["schemas"]["InvalidTimeRangeErrorResponse"] | components["schemas"]["InvalidApiFilterErrorResponse"];
                };
            };
            /** @description Your access token is invalid or expired and can’t be used to identify a user. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Forbidden. Your access token is valid, but you don’t have the required permissions to access the resource. */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Metrics category not available for the organization */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["CategoryNotFoundErrorResponse"];
                };
            };
            /** @description Metrics data temporarily unavailable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["MetricsNotAvailableErrorResponse"];
                };
            };
        };
    };
    getScapiHooksMetrics: {
        parameters: {
            query?: {
                from?: number;
                to?: number;
            };
            header?: never;
            path: {
                organizationId: components["schemas"]["OrganizationId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successfully retrieved SCAPI hooks metrics for the requested time window */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MetricsDataResponse"];
                };
            };
            /** @description Bad request — invalid time parameters */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["InvalidTimeParameterErrorResponse"] | components["schemas"]["InvalidTimeRangeErrorResponse"];
                };
            };
            /** @description Your access token is invalid or expired and can’t be used to identify a user. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Forbidden. Your access token is valid, but you don’t have the required permissions to access the resource. */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Metrics category not available for the organization */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["CategoryNotFoundErrorResponse"];
                };
            };
            /** @description Metrics data temporarily unavailable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["MetricsNotAvailableErrorResponse"];
                };
            };
        };
    };
    getMrtMetrics: {
        parameters: {
            query?: {
                from?: number;
                to?: number;
            };
            header?: never;
            path: {
                organizationId: components["schemas"]["OrganizationId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successfully retrieved Managed Runtime metrics for the requested time window */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MetricsDataResponse"];
                };
            };
            /** @description Bad request — invalid time parameters */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["InvalidTimeParameterErrorResponse"] | components["schemas"]["InvalidTimeRangeErrorResponse"];
                };
            };
            /** @description Your access token is invalid or expired and can’t be used to identify a user. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Forbidden. Your access token is valid, but you don’t have the required permissions to access the resource. */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Metrics category not available for the organization */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["CategoryNotFoundErrorResponse"];
                };
            };
            /** @description Metrics data temporarily unavailable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["MetricsNotAvailableErrorResponse"];
                };
            };
        };
    };
    getControllerMetrics: {
        parameters: {
            query?: {
                from?: number;
                to?: number;
            };
            header?: never;
            path: {
                organizationId: components["schemas"]["OrganizationId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successfully retrieved controller metrics for the requested time window */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MetricsDataResponse"];
                };
            };
            /** @description Bad request — invalid time parameters */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["InvalidTimeParameterErrorResponse"] | components["schemas"]["InvalidTimeRangeErrorResponse"];
                };
            };
            /** @description Your access token is invalid or expired and can’t be used to identify a user. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Forbidden. Your access token is valid, but you don’t have the required permissions to access the resource. */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Metrics category not available for the organization */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["CategoryNotFoundErrorResponse"];
                };
            };
            /** @description Metrics data temporarily unavailable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["MetricsNotAvailableErrorResponse"];
                };
            };
        };
    };
    getOcapiMetrics: {
        parameters: {
            query?: {
                from?: number;
                to?: number;
                ocapiCategory?: string;
                ocapiApi?: string;
            };
            header?: never;
            path: {
                organizationId: components["schemas"]["OrganizationId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successfully retrieved OCAPI metrics for the requested time window */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MetricsDataResponse"];
                };
            };
            /** @description Bad request — invalid time parameters or OCAPI filter value */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["InvalidTimeParameterErrorResponse"] | components["schemas"]["InvalidTimeRangeErrorResponse"] | components["schemas"]["InvalidApiFilterErrorResponse"];
                };
            };
            /** @description Your access token is invalid or expired and can’t be used to identify a user. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Forbidden. Your access token is valid, but you don’t have the required permissions to access the resource. */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Metrics category not available for the organization */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["CategoryNotFoundErrorResponse"];
                };
            };
            /** @description Metrics data temporarily unavailable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["MetricsNotAvailableErrorResponse"];
                };
            };
        };
    };
}
