/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/organizations/{organizationId}/global-custom-preferences": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Retrieves the Global Custom Preferences. */
        get: operations["getGlobalCustomPreferenceList"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/organizations/{organizationId}/site-custom-preferences": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Retrieves the Custom Preferences for a specified siteId. */
        get: operations["getSiteCustomPreferenceList"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/organizations/{organizationId}/global-preference-groups/{groupId}/{instanceType}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Read the custom preferences in a global preference group for a given instance type.
         * @description For the specified instance, read the custom preferences in the preference group at the
         *     global (organization) level. Specify 'current' to retrieve the preferences for the instance
         *     on which this call is being made. The system will recognize its type.
         *
         *
         *     **Note:** If instance type sandbox is used, the preference values of development instance type
         *     will be returned as fallback.
         */
        get: operations["getGlobalPreferenceGroup"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * Update the custom preferences in a global preference group for a given instance type.
         * @description For the specified instance, update one or more custom preferences in the preference group
         *     at the global (organization) level.
         *
         *
         *     **Note:** If instance type sandbox is used, the preference values of development instance type
         *     will be returned as fallback.
         */
        patch: operations["updateGlobalPreferenceGroup"];
        trace?: never;
    };
    "/organizations/{organizationId}/site-preference-groups/{groupId}/{instanceType}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Read the custom preferences in a site preference group for a given instance type.
         * @description For the specified site and instance, read the custom preferences in the preference group.
         *     Specify 'current' to retrieve the preferences for the instance on which this call is being made.
         *     The system will recognize its type.
         */
        get: operations["getSitePreferenceGroup"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * Update the custom preferences in a site preference group for a given instance type.
         * @description For the specified site and instance, update one or more custom preferences in the preference group.
         *     Preferences of type password cannot be set to "************" since it is a reserved value.
         */
        patch: operations["updateSitePreferenceGroup"];
        trace?: never;
    };
    "/organizations/{organizationId}/site-preference-groups/{groupId}/{instanceType}/preference-search": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Search preferences across sites in a preference group for a given instance type.
         * @description Search preferences across sites in the specified preference group and instance.
         *     The query attribute specifies a complex query that can be used to narrow down the search.
         *
         *
         *     The following is a list of searchable fields:
         *
         *     | Field | Type |
         *     |---|---|
         *     | id | String |
         *     | display_name | Localized String |
         *     | description | Localized String |
         *     | value_type | Enum (see below) |
         *
         *
         *     Allowed value_type values: string, int, double, text, html, date, image, boolean, money,
         *     quantity, datetime, email, password, set_of_string, set_of_int, set_of_double,
         *     enum_of_string, enum_of_int.
         *
         *
         *     **Note:** value_type can only be joined with other attributes using a conjunction (AND).
         *     Only searchable attributes can be used in sorting.
         *
         *
         *     **Note:** If instance type sandbox is used, the preference values of development instance type
         *     will be returned as fallback.
         */
        post: operations["searchSitePreferences"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/organizations/{organizationId}/site-preference-groups/{groupId}/{instanceType}/preferences/{preferenceId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Read a single preference value across sites in a preference group for a given instance type.
         * @description Read a specific preference value identified by its ID within the given preference group
         *     and instance type. Returns the preference value for all sites.
         */
        get: operations["getSitePreference"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * Update a single preference value across sites in a preference group for a given instance type.
         * @description Update a specific preference value identified by its ID within the given preference group
         *     and instance type. The siteValues map specifies the new values per site.
         */
        patch: operations["updateSitePreference"];
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * @description An identifier for the Salesforce Commerce Cloud organization the request is being made by. It consists of a prefix 'f_ecom_' followed by a 4-character [realm identifier](https://developer.salesforce.com/docs/commerce/commerce-api/guide/base-url.html#realm-id) and a 3-character [instance type identifier](https://developer.salesforce.com/docs/commerce/commerce-api/guide/base-url.html#instance-id).
         * @example f_ecom_zzxy_prd
         */
        OrganizationId: string;
        /**
         * Format: int32
         * @description The total number of hits that match the search's criteria. This can be greater than the number of results returned as search results are pagenated.
         * @default 0
         * @example 10
         */
        Total: number;
        /**
         * @description Schema defining generic list result. Each response schema of a resource requiring a list response should extend this schema.
         *     Additionally it needs to be defined what data is returned.
         */
        ResultBase: {
            /**
             * Format: int32
             * @description Maximum records to retrieve per request. The limit with its constraints (minimum, maximum, default) is defined by the request parameter `limit` of the endpoint returning this schema.
             * @example 10
             */
            limit: number;
            total: components["schemas"]["Total"];
        };
        /**
         * Format: int32
         * @description The zero-based index of the first hit/data to include in the result.
         * @default 0
         * @example 0
         */
        Offset: number;
        /**
         * @description Schema defining generic pageable result. Each response schema of a resource requiring pagination should extend this schema.
         *     If you use this extend this schema directly, it needs to be defined what data is returned. Allowed names for the data field is `data`.
         */
        PaginatedResultBase: {
            offset: components["schemas"]["Offset"];
        } & WithRequired<components["schemas"]["ResultBase"], "limit" | "total">;
        /** @description Preference object */
        CustomPreference: {
            /** @description The ID of the preference group. */
            groupId: string;
            /** @description The Preference Id. */
            id: string;
            /** @description The value for the Preference Id. */
            value: unknown;
        };
        /** @description Document representing a Custom Preference result. */
        CustomPreferenceList: {
            /** @description The list of custom preferences in the search result. */
            data: components["schemas"]["CustomPreference"][];
        } & WithRequired<components["schemas"]["PaginatedResultBase"], "offset">;
        ErrorResponse: {
            /**
             * @description A short, human-readable summary of the problem
             *     type.  It will not change from occurrence to occurrence of the
             *     problem, except for purposes of localization
             * @example You do not have enough credit
             */
            title: string;
            /**
             * @description A URI reference [RFC3986] that identifies the
             *     problem type.  This specification encourages that, when
             *     dereferenced, it provide human-readable documentation for the
             *     problem type (e.g., using HTML [W3C.REC-html5-20141028]).  When
             *     this member is not present, its value is assumed to be
             *     "about:blank". It accepts relative URIs; this means
             *     that they must be resolved relative to the document's base URI, as
             *     per [RFC3986], Section 5.
             * @example NotEnoughMoney
             */
            type: string;
            /**
             * @description A human-readable explanation specific to this occurrence of the problem.
             * @example Your current balance is 30, but that costs 50
             */
            detail: string;
            /**
             * @description A URI reference that identifies the specific
             *     occurrence of the problem.  It may or may not yield further
             *     information if dereferenced.  It accepts relative URIs; this means
             *     that they must be resolved relative to the document's base URI, as
             *     per [RFC3986], Section 5.
             * @example /account/12345/msgs/abc
             */
            instance?: string;
        } & {
            [key: string]: unknown;
        };
        /**
         * @description The identifier of the site that a request is being made in the context of. Attributes might have site specific values, and some objects may only be assigned to specific sites
         * @example RefArch
         */
        SiteId: string;
        /** @description Document representing a link to a customer list. */
        CustomerListLink: {
            /**
             * @description The customer list identifier
             * @example customer-list-1
             */
            customerListId?: string;
            /**
             * @description The title of the customer list link
             * @example Default Customer List
             */
            title?: string;
        };
        Site: {
            /**
             * ID
             * @description The ID of the site.
             */
            id: components["schemas"]["SiteId"];
            displayName?: {
                [key: string]: string;
            };
            description?: {
                [key: string]: string;
            };
            /** @description The link to the customer list */
            customerListLink?: components["schemas"]["CustomerListLink"];
            /**
             * @description Specifies whether the site status is in deletion (true) or not (false)
             * @example false
             */
            inDeletion?: boolean;
            /**
             * @description Status of the storefront
             * @example online
             * @enum {string}
             */
            storefrontStatus?: "online" | "maintenance" | "to_be_deleted" | "protected";
            /**
             * @description The catalog bound to the given site.
             * @example storefront-catalog-m-en
             */
            siteCatalogId?: string;
            /**
             * @description The cartridge names assigned to a site delemited by ':'.
             * @example app_storefront_core:app_storefront_base
             */
            cartridges?: string;
            /**
             * Format: date-time
             * @description The timestamp when the site was created.
             * @example 2024-01-15T10:00:00.000Z
             */
            creationDate?: string;
            /**
             * Format: date-time
             * @description The timestamp when the site was last modified.
             * @example 2024-10-14T15:30:00.000Z
             */
            lastModified?: string;
        };
        /** @description Represents custom preferences at the site level within a preference group. Custom preference attributes are returned with the "c_" prefix. */
        SitePreferences: {
            site?: components["schemas"]["Site"];
        } & {
            [key: string]: unknown;
        };
        /** @description Represents custom preferences at the global (organization) level within a preference group. Custom preference attributes are returned with the "c_" prefix. */
        OrganizationPreferences: {
            /** @description The list of site-specific preferences, returned when expand=sites. */
            sitePreferences?: components["schemas"]["SitePreferences"][];
        } & {
            [key: string]: unknown;
        };
        /**
         * @description A set of objects that define criteria used to select records. A query can contain one of the following:
         *     * `MatchAllQuery`
         *      - Matches all documents.
         *     * `TermQuery`
         *      - Matches one or more documents against one or more document fields.
         *     * `TextQuery`
         *      - Matches text against one or more fields.
         *     * `BoolQuery`
         *      - Allows construction of a logical expression of multiple queries.
         *     * `FilteredQuery`
         *      - Allows a filter to be applied to a query.
         *     * `NestedQuery`
         *      - Allows you to query on nested documents.
         *      - _Only supported by some Commerce APIs. For more details, see the endpoint descriptions in the API documentation._
         * @example {
         *       "filteredQuery": {
         *         "query": {
         *           "textQuery": {
         *             "fields": [
         *               "couponId"
         *             ],
         *             "searchPhrase": "disabled"
         *           }
         *         },
         *         "filter": {
         *           "termFilter": {
         *             "field": "enabled",
         *             "operator": "is",
         *             "values": [
         *               false
         *             ]
         *           }
         *         }
         *       }
         *     }
         */
        Query: {
            boolQuery?: components["schemas"]["BoolQuery"];
            filteredQuery?: components["schemas"]["FilteredQuery"];
            matchAllQuery?: components["schemas"]["MatchAllQuery"];
            nestedQuery?: components["schemas"]["NestedQuery"];
            termQuery?: components["schemas"]["TermQuery"];
            textQuery?: components["schemas"]["TextQuery"];
        };
        /**
         * @description A boolean query allows construction of full logical expression trees that are composed of other queries (usually term queries and text queries). A boolean query has three sets of clauses:
         *
         *       - `must`, which combines as an `AND` operator.
         *       - `should`, which combines as an `OR` operator.
         *       - `must_not`, which combines as a `NOT` operator.
         *
         *     If `must`, `mustNot`, or `should` appear in the same boolean query, they are combined logically using the `AND` operator. For example:
         *
         *         (must-1 AND must-1 AND ...)
         *           AND (should-1 OR should-2 OR ...)
         *           AND NOT (must_not-1 OR must_not-2 OR ...)
         * @example {
         *       "value": {
         *         "must": [
         *           {
         *             "textQuery": {
         *               "fields": [
         *                 "couponId"
         *               ],
         *               "searchPhrase": "DEAL"
         *             }
         *           },
         *           {
         *             "textQuery": {
         *               "fields": [
         *                 "description"
         *               ],
         *               "searchPhrase": "Big bargain deal"
         *             }
         *           }
         *         ],
         *         "mustNot": [
         *           {
         *             "termQuery": {
         *               "fields": [
         *                 "enabled"
         *               ],
         *               "operator": "is",
         *               "values": [
         *                 false
         *               ]
         *             }
         *           }
         *         ]
         *       }
         *     }
         */
        BoolQuery: {
            /** @description List of queries to be evaluated as an `AND` operator. */
            must?: components["schemas"]["Query"][];
            /** @description List of queries to be evaluated as a `NOT` operator. */
            mustNot?: components["schemas"]["Query"][];
            /** @description List of queries to be evaluated as an `OR` operator. */
            should?: components["schemas"]["Query"][];
        };
        /**
         * @description Contains a set of objects that define criteria used to select records. A filter can contain one of the following:
         *       * `TermFilter`
         *        - Matches records where a field (or fields) exactly matches some simple value (including `null`).
         *       * `RangeFilter`
         *        - Matches records where a field value lies within a specified range.
         *       * `Range2Filter`
         *        - Matches records in a specified range across fields.
         *       * `QueryFilter`
         *        - Matches records based on a query.
         *       * `BoolFilter`
         *        - Provides filtering of records using a set of filters combined using a logical operator.
         * @example null
         */
        Filter: {
            boolFilter?: components["schemas"]["BoolFilter"];
            queryFilter?: components["schemas"]["QueryFilter"];
            range2Filter?: components["schemas"]["Range2Filter"];
            rangeFilter?: components["schemas"]["RangeFilter"];
            termFilter?: components["schemas"]["TermFilter"];
        };
        /**
         * @description Allows you to combine other filters into (possibly recursive) logical expression trees. A boolean filter is composed of a logical operator (`AND`, `OR`, `NOT`) and a list of filters that the operator relates to. Multiple filters can be negated with a single `NOT` operator, even when the filters are combined with the `AND` operator.
         * @example {
         *       "value": {
         *         "operator": "and",
         *         "filters": [
         *           {
         *             "termFilter": {
         *               "field": "id",
         *               "operator": "is",
         *               "values": [
         *                 "myId"
         *               ]
         *             }
         *           },
         *           {
         *             "termFilter": {
         *               "field": "couponId",
         *               "operator": "is",
         *               "values": [
         *                 "couponOne"
         *               ]
         *             }
         *           }
         *         ]
         *       }
         *     }
         */
        BoolFilter: {
            /** @description A list of filters that are logically combined by an operator. */
            filters?: components["schemas"]["Filter"][];
            /**
             * @description The logical operator that is used to combine the filters.
             * @example and
             * @enum {string}
             */
            operator: "and" | "or" | "not";
        };
        /** @description Wraps any query and allows it to be used as a filter. */
        QueryFilter: {
            query: components["schemas"]["Query"];
        };
        /**
         * @description Name of the field. Might be a custom field name prefixed with c_.
         * @example couponId
         */
        Field: string;
        /**
         * @description Allows you to restrict a search result to hits where a range defined by specified attributes has a certain relationship to a specified range.
         *
         *     The first range (R1) is defined by a pair of attributes (`fromField` and `toField`) that specify the extent of a range, such as attributes `validFrom` and `validTo`.
         *
         *     The second range (R2) is defined by `fromValue` and `toValue`.
         *
         *     The filter mode specifies the method used to compare the two ranges:
         *
         *     * `overlap`: R1 overlaps fully or partially with R2.
         *     * `containing`: R1 contains R2.
         *     * `contained`: R1 is contained in R2.
         *
         *     The range filter supports several value types, and relies on the natural sorting of the value type for range interpretation. Value ranges can be open-ended, but only at one end of the range. You can configure whether the lower bounds and upper bounds are inclusive or exclusive.
         *
         *     A range 2 filter is useful for general restrictions that can be shared between searches (like a static date range) because the filter result is cached in memory. Range filters are not appropriate if the range is expected to be different for every query (for example, if the user controls the date range down to the hour via a UI control). Range filters are inclusive by default.
         * @example {
         *       "fromField": "validFrom",
         *       "toField": "validTo",
         *       "filterMode": "overlap",
         *       "fromValue": "2007-01-01T00:00:00.000Z",
         *       "toValue": "2017-01-01T00:00:00.000Z"
         *     }
         */
        Range2Filter: {
            /**
             * @description Compare mode: overlap, containing, or contained.
             * @default overlap
             * @example overlap
             * @enum {string}
             */
            filterMode: "overlap" | "containing" | "contained";
            /**
             * @description The field name of the field that starts the first range.
             * @example validFrom
             */
            fromField: components["schemas"]["Field"];
            /**
             * @description A flag indicating if the lower bound of the second range is inclusive. To make the lower bound exclusive, set to `false`.
             * @default true
             * @example true
             */
            fromInclusive: boolean;
            /**
             * @description The lower bound of the second range. If not specified, the range is open-ended with respect to the lower bound. You can't leave both the lower and upper bounds open-ended.
             * @example 2007-01-01T00:00:00.000Z
             */
            fromValue?: unknown;
            /**
             * @description The field name of the field that ends the first range.
             * @example validTo
             */
            toField: components["schemas"]["Field"];
            /**
             * @description A flag indicating if the upper bound of the second range is inclusive. To make the lower bound exclusive, set to `false`.
             * @default true
             * @example true
             */
            toInclusive: boolean;
            /**
             * @description The upper bound of the second range. If not specified, the range is open-ended with respect to the upper bound. You can't leave both the upper and lower bounds open-ended.
             * @example 2017-01-01T00:00:00.000Z
             */
            toValue?: unknown;
        };
        /**
         * @description Allows you to restrict a search result to hits that have values for a given attribute that fall within a given value range. The range filter supports several value types and relies on the natural sorting of the value type for range interpretation. Value ranges can be open-ended, but only at one end of the range. You can configure whether the lower bounds and upper bounds are inclusive or exclusive.
         *
         *     A range filter is useful for general restrictions that can be shared between searches (like a static date range) because the filter result is cached in memory. Range filters are not appropriate if the range is expected to be different for every query (for example, if the user controls the date range down to the hour via a UI control). Range filters are inclusive by default.
         */
        RangeFilter: {
            /**
             * @description The search field.
             * @example validFrom
             */
            field: components["schemas"]["Field"];
            /** @description The lower bound of the filter range. If not specified, the range is open-ended with respect to the lower bound. You can't leave both the lower and upper bounds open-ended. */
            from?: string | number;
            /**
             * @description A flag indicating if the lower bound of the range is inclusive. To make the lower bound exclusive, set to `false`.
             * @default true
             * @example true
             */
            fromInclusive: boolean;
            /** @description The upper bound of the filter range. If not specified, the range is open-ended with respect to the upper bound. You can't leave both the upper and lower bounds open-ended. */
            to?: string | number;
            /**
             * @description A flag indicating if the upper bound of the range is inclusive. To make the upper bound exclusive, set to `false`.
             * @default true
             * @example true
             */
            toInclusive: boolean;
        };
        /**
         * @description Allows you to restrict a search result to hits that match exactly one of the values configured for the filter. A term filter is useful for general restrictions that can be shared between searches. Use term filters whenever the criteria you filter on is a shared property of multiple searches (for example, like filtering by an order status). Use term filters for fields that have a discrete and small set of values only.
         * @example {
         *       "field": "id",
         *       "operator": "is",
         *       "values": [
         *         "myId"
         *       ]
         *     }
         */
        TermFilter: {
            /** @description The filter field. */
            field: components["schemas"]["Field"];
            /**
             * @description The operator used to compare the field's values with the given values.
             * @example is
             * @enum {string}
             */
            operator: "is" | "one_of" | "is_null" | "is_not_null" | "less" | "greater" | "not_in" | "neq";
            /** @description The filter values. */
            values?: string[];
        };
        /**
         * @description Allows to filter the result of a possibly complex query using a possibly complex filter.
         * @example {
         *       "query": {
         *         "textQuery": {
         *           "fields": [
         *             "couponId"
         *           ],
         *           "searchPhrase": "disabled"
         *         }
         *       },
         *       "filter": {
         *         "termFilter": {
         *           "field": "enabled",
         *           "operator": "is",
         *           "values": [
         *             false
         *           ]
         *         }
         *       }
         *     }
         */
        FilteredQuery: {
            filter: components["schemas"]["Filter"];
            query: components["schemas"]["Query"];
        };
        /** @description Matches all documents (namespace and document type). This query comes in handy if you just want to filter a search result or really do not have any constraints. */
        MatchAllQuery: Record<string, never>;
        /**
         * @description Allows you to query nested documents that are part of a larger document. Say, for example, that you have a main product with variations in one big document, and you want to constrain a search to main products that have variations that match multiple constraints.
         *
         *     A `NestedQuery` is only supported by some Commerce APIs. For more details, see the endpoint descriptions in the API documentation.
         * @example {
         *       "path": "order.shippingAddresses",
         *       "query": {
         *         "boolQuery": {
         *           "must": [
         *             {
         *               "boolQuery": {
         *                 "must": [
         *                   {
         *                     "termQuery": {
         *                       "fields": [
         *                         "order.shippingAddresses.firstName"
         *                       ],
         *                       "operator": "is",
         *                       "values": [
         *                         "John"
         *                       ]
         *                     }
         *                   }
         *                 ]
         *               }
         *             },
         *             {
         *               "boolQuery": {
         *                 "must": [
         *                   {
         *                     "termQuery": {
         *                       "fields": [
         *                         "order.shippingAddresses.lastName"
         *                       ],
         *                       "operator": "is",
         *                       "values": [
         *                         "Doe"
         *                       ]
         *                     }
         *                   }
         *                 ]
         *               }
         *             }
         *           ]
         *         }
         *       },
         *       "scoreMode": "avg"
         *     }
         */
        NestedQuery: {
            /**
             * @description The path to the nested document.
             * @example order.shippingAddresses
             */
            path: string;
            query: components["schemas"]["Query"];
            /**
             * @description Indicates how scores for matching child objects affect the root parent document’s relevance score.
             * @example avg
             * @enum {string}
             */
            scoreMode?: "avg" | "total" | "max" | "none";
        };
        /**
         * @description A term query matches one or more values against one or more document fields. A document is considered a hit if one of the values matches exactly with at least one of the given fields. The operator `is` can only take one value, while `one_of` can take multiple values. If multiple fields are specified, they are combined using a logical `OR` operator.
         *
         *     **Limitations:**
         *
         *     * The `greater` and `less` operators are not supported under certain conditions. Both operators are permitted unless the API documentation states otherwise.
         *     * A subset of Commerce APIs handle queries with multiple fields differently. If the query has multiple fields, the query is internally handled as a logical `OR` of `DisjointMaxQueries` (with the dismax matching a value against all fields). The dismax makes sure that a document carrying a single term in multiple fields does not get higher scores than a document matching multiple terms in multiple fields.
         */
        TermQuery: {
            /** @description The document fields that the values are matched against, combined with the operator. */
            fields: components["schemas"]["Field"][];
            /**
             * @description Returns the operator to use for the term query.
             * @example is
             * @enum {string}
             */
            operator: "is" | "one_of" | "is_null" | "is_not_null" | "less" | "greater" | "not_in" | "neq";
            /** @description The values that the fields are compared against, combined with the operator. */
            values?: (string | number | boolean)[];
        };
        /**
         * @description A text query is used to match some text (for example, a search phrase possibly consisting of multiple terms) against one or more fields. When multiple fields are provided, the phrase conceptually forms a logical `OR` over the fields. In this case, the terms of the phrase basically have to match within the text, that would result in concatenating all given fields.
         * @example {
         *       "fields": [
         *         "couponId"
         *       ],
         *       "searchPhrase": "limit"
         *     }
         */
        TextQuery: {
            /** @description The document fields that the search phrase matches against. */
            fields: components["schemas"]["Field"][];
            /**
             * @description A search phrase, which can include multiple terms separated by spaces.
             * @example campaign summer
             */
            searchPhrase: string;
        };
        /**
         * @description Document representing a sort request. Each API has a different default sort configuration that can be modified in the request.
         * @example {
         *       "field": "couponId",
         *       "sortOrder": "desc"
         *     }
         */
        Sort: {
            /**
             * @description The name of the field to sort on.
             * @example couponId
             */
            field: string;
            /**
             * @description The sort order to be applied when sorting. When omitted, the default sort order (asc) is used.
             * @default asc
             * @example asc
             * @enum {string}
             */
            sortOrder: "asc" | "desc";
        };
        /** @description Document representing a search request for retrieving items within the Data API. The query is a potentially complex set of expressions. The fields and expands that each query supports are defined within the search resource. */
        SearchRequest: {
            /**
             * Format: int32
             * @description Maximum records to retrieve per request, not to exceed 200.
             * @example 10
             */
            limit?: number;
            query: components["schemas"]["Query"];
            /** @description The list of sort clauses configured for the search request. Sort clauses are optional. See the description of the search endpoint for details on the default sorting behavior that is used when explicit sorts are not passed. */
            sorts?: components["schemas"]["Sort"][];
            offset?: components["schemas"]["Offset"];
        };
        /**
         * @description Document representing a generic search result. Each search resource should extend this to define what is returned in the `hits`.
         * @example {
         *       "limit": 1,
         *       "hits": [
         *         {
         *           "couponId": "coupon1",
         *           "creationDate": "2019-10-20T12:00:00Z",
         *           "description": "This coupon is used to give 10% off stuff.",
         *           "enabled": false,
         *           "exportedCodeCount": 0,
         *           "lastModified": "2019-10-30T04:23:59Z",
         *           "redemptionCount": 3,
         *           "redemptionLimits": {
         *             "limitPerCode": 1,
         *             "limitPerCustomer": 1,
         *             "limitPerTimeFrame": {
         *               "limit": 2,
         *               "redemptionTimeFrame": 24
         *             }
         *           },
         *           "singleCode": "MyCode",
         *           "systemCodesConfig": {
         *             "codePrefix": "SG",
         *             "numberOfCodes": 500000
         *           },
         *           "totalCodesCount": 50,
         *           "type": "single_code"
         *         }
         *       ],
         *       "query": {
         *         "textQuery": {
         *           "fields": [
         *             "id",
         *             "description"
         *           ],
         *           "searchPhrase": "stuff"
         *         }
         *       },
         *       "sorts": [
         *         {
         *           "field": "couponId",
         *           "sortOrder": "desc"
         *         }
         *       ],
         *       "offset": 2,
         *       "total": 8
         *     }
         */
        PaginatedSearchResult: {
            query: components["schemas"]["Query"];
            /** @description The sorting that was applied to the result. */
            sorts?: components["schemas"]["Sort"][];
            /** @description The sorted array of search hits. Can be empty. */
            hits?: Record<string, never>[];
        } & components["schemas"]["PaginatedResultBase"];
        /**
         * @description The type of an attribute value
         * @example string
         * @enum {string}
         */
        ValueType: "string" | "int" | "double" | "text" | "html" | "date" | "image" | "boolean" | "money" | "quantity" | "datetime" | "email" | "password" | "set_of_string" | "set_of_int" | "set_of_double" | "enum_of_string" | "enum_of_int";
        /** @description An attribute definition value */
        ObjectAttributeValueDefinition: {
            /**
             * @description The ID of the attribute value
             * @example value-1
             */
            readonly id?: string;
            /**
             * @description The value of the attribute
             * @example 1
             */
            readonly value?: string;
            /**
             * @example {
             *       "default": "One",
             *       "de": "Eins",
             *       "en": "One"
             *     }
             */
            readonly displayValue?: {
                [key: string]: string;
            };
            /**
             * @example {
             *       "default": "Object type representing products.",
             *       "de": "Objekttyp, der Produkte repräsentiert.",
             *       "en": "Object type representing products."
             *     }
             */
            readonly description?: {
                [key: string]: string;
            };
            /**
             * Format: double
             * @description The position of the attribute value within the set of attribute values
             * @example 1
             */
            readonly position?: number;
        };
        /** @description Document representing an attribute definition */
        ObjectAttributeDefinition: {
            /**
             * @description The user supplied ID of the attribute
             * @example color
             */
            id: string;
            /**
             * @description The effective ID, which is c_id if the attribute is custom, and just the id otherwise
             * @example c_color
             */
            readonly effectiveId?: string;
            /**
             * @example {
             *       "default": "Product",
             *       "de": "Produkt",
             *       "en": "Product"
             *     }
             */
            displayName?: {
                [key: string]: string;
            };
            /**
             * @example {
             *       "default": "Object type representing products.",
             *       "de": "Objekttyp, der Produkte repräsentiert.",
             *       "en": "Object type representing products."
             *     }
             */
            description?: {
                [key: string]: string;
            };
            /**
             * @description Flag indicating if this is a key attribute
             * @example false
             */
            key?: boolean;
            /**
             * @description Flag indicating if a value is mandatory for the attribute
             * @example false
             */
            mandatory?: boolean;
            /**
             * @description Flag indicating if this attribute can be localized
             * @example false
             */
            localizable?: boolean;
            /**
             * @description Flag indicating if this attribute is site-specific
             * @example false
             */
            siteSpecific?: boolean;
            /**
             * @description Flag indicating if this attribute is searchable
             * @example true
             */
            searchable?: boolean;
            /**
             * @description Returns true if the attribute definition is explicitly marked queryable or if the attribute value type belongs to a queryable type. Computed and read-only.
             * @example true
             */
            readonly queryable?: boolean;
            valueType?: components["schemas"]["ValueType"];
            /**
             * @description Flag indicating if this attribute is visible
             * @example true
             */
            visible?: boolean;
            /**
             * @description Flag indicating if this attribute is a system attribute
             * @example false
             */
            system?: boolean;
            /**
             * @example {
             *       "default": "General unit",
             *       "de": "Allgemeine Einheit",
             *       "en": "General unit"
             *     }
             */
            unit?: {
                [key: string]: string;
            };
            /**
             * @description Flag indicating if this attribute can be encoded using the encoding='off' flag in ISML templates
             * @example false
             */
            readonly requiresEncoding?: boolean;
            /**
             * @description True if the attribute can have multiple values. Applicable to set_of_* and enum_of_* types.
             * @example false
             */
            multiValueType?: boolean;
            /**
             * @description Flag indicating if this attribute is of type 'Set of'
             * @example false
             */
            readonly setValueType?: boolean;
            /**
             * @description Flag indicating if this attribute is externally managed
             * @example false
             */
            externallyManaged?: boolean;
            /**
             * @description Flag indicating if this attribute is externally defined
             * @example false
             */
            externallyDefined?: boolean;
            /**
             * @description Flag indicating if this attribute is required for order of the attribute model's product
             * @example false
             */
            orderRequired?: boolean;
            /**
             * @description A regular expression that defines the legal values for this attribute
             * @example ^[a-zA-Z]+$
             */
            readonly regularExpression?: string;
            /**
             * Format: int32
             * @description The length of the field for this attribute in the editor
             * @example 50
             */
            readonly fieldLength?: number;
            /**
             * Format: int32
             * @description The height of the field for this attribute in the editor
             * @example 1
             */
            readonly fieldHeight?: number;
            /**
             * Format: int32
             * @description The minimum length of the field for this attribute
             * @example 1
             */
            readonly minLength?: number;
            /**
             * @description Flag indicating if this attribute is read-only
             * @example false
             */
            readonly readOnly?: boolean;
            /**
             * Format: double
             * @description The minimum possible value for this attribute
             * @example 0
             */
            readonly minValue?: number;
            /**
             * Format: double
             * @description The maximum possible value for this attribute
             * @example 100
             */
            readonly maxValue?: number;
            /**
             * Format: int32
             * @description The minimum number of fraction digits for a value of this attribute
             * @example 2
             */
            readonly scale?: number;
            /** @description The default value of this attribute. It can be updated, but not created. */
            defaultValue?: components["schemas"]["ObjectAttributeValueDefinition"];
            /** @description A set of values that are possible for this attribute */
            readonly valueDefinitions?: components["schemas"]["ObjectAttributeValueDefinition"][];
            /**
             * Format: date-time
             * @description The date/time when the attribute definition was created
             * @example 2024-01-15T10:30:00Z
             */
            readonly creationDate?: string;
            /**
             * Format: date-time
             * @description The date/time when the attribute definition was last modified
             * @example 2024-01-15T11:00:00Z
             */
            readonly lastModified?: string;
        };
        /** @description Represents a single preference value with its attribute definition and site-specific values. */
        PreferenceValue: {
            /**
             * @description The preference attribute ID
             * @example WapiStringAttr
             */
            id: string;
            description?: {
                [key: string]: string;
            };
            displayName?: {
                [key: string]: string;
            };
            attributeDefinition?: components["schemas"]["ObjectAttributeDefinition"];
            /** @description A mapping of site IDs to their preference values. */
            siteValues?: {
                [key: string]: unknown;
            };
            valueType?: components["schemas"]["ValueType"];
        };
        /** @description Document representing a preference value search result. */
        PreferenceValueSearchResult: {
            /** @description The sorted array of search hits. Can be empty. */
            hits?: components["schemas"]["PreferenceValue"][];
        } & components["schemas"]["PaginatedSearchResult"];
    };
    responses: never;
    parameters: {
        /**
         * @description An identifier for the Salesforce Commerce Cloud organization the request is being made by. It consists of a prefix 'f_ecom_' followed by a 4-character [realm identifier](https://developer.salesforce.com/docs/commerce/commerce-api/guide/base-url.html#realm-id) and a 3-character [instance type identifier](https://developer.salesforce.com/docs/commerce/commerce-api/guide/base-url.html#instance-id).
         * @example f_ecom_zzxy_prd
         */
        organizationId: components["schemas"]["OrganizationId"];
        /** @description Whether to mask password or not. */
        maskPassword: boolean;
        /** @description The identifier of the site that a request is being made in the context of. Attributes might have site specific values, and some objects may only be assigned to specific sites. */
        siteId: components["schemas"]["SiteId"];
        /** @description The preference group ID. */
        groupId: string;
        /**
         * @description The instance type for which to read or update preferences.
         * @example staging
         */
        instanceType: "staging" | "development" | "sandbox" | "production";
        /** @description The preference values of type Password are masked when set. */
        maskPasswords: boolean;
        /** @description Expands the result document to include additional information. For global preference groups, the expansion "sites" retrieves the custom preferences for all the available sites. */
        globalPreferenceGroupExpand: "sites"[];
        /** @description Expands the result document to include additional information. For preference search, the expansion "value" retrieves the value definitions of the attribute definition. */
        preferenceSearchExpand: "value"[];
        /** @description The preference attribute ID. */
        preferenceId: string;
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    getGlobalCustomPreferenceList: {
        parameters: {
            query?: {
                /** @description Whether to mask password or not. */
                maskPassword?: components["parameters"]["maskPassword"];
                /** @description Number of records to retrieve per request. Must be between 1 (minimum) and 200 (maximum). Defaults to 200. */
                limit?: number;
                /** @description Used to retrieve the results based on a particular resource offset. */
                offset?: number;
            };
            header?: never;
            path: {
                /**
                 * @description An identifier for the Salesforce Commerce Cloud organization the request is being made by. It consists of a prefix 'f_ecom_' followed by a 4-character [realm identifier](https://developer.salesforce.com/docs/commerce/commerce-api/guide/base-url.html#realm-id) and a 3-character [instance type identifier](https://developer.salesforce.com/docs/commerce/commerce-api/guide/base-url.html#instance-id).
                 * @example f_ecom_zzxy_prd
                 */
                organizationId: components["parameters"]["organizationId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Retrieved Global Custom Preferences successfully. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CustomPreferenceList"];
                };
            };
            /** @description Thrown if the query is ill-formed. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /**
             * @description Unauthorized. Your Client ID is invalid, or you are not allowed to access
             *     the content provided by the requested URL.
             */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    getSiteCustomPreferenceList: {
        parameters: {
            query: {
                /** @description Whether to mask password or not. */
                maskPassword?: components["parameters"]["maskPassword"];
                /** @description The identifier of the site that a request is being made in the context of. Attributes might have site specific values, and some objects may only be assigned to specific sites. */
                siteId: components["parameters"]["siteId"];
                /** @description Number of records to retrieve per request. Must be between 1 (minimum) and 200 (maximum). Defaults to 200. */
                limit?: number;
                /** @description Used to retrieve the results based on a particular resource offset. */
                offset?: number;
            };
            header?: never;
            path: {
                /**
                 * @description An identifier for the Salesforce Commerce Cloud organization the request is being made by. It consists of a prefix 'f_ecom_' followed by a 4-character [realm identifier](https://developer.salesforce.com/docs/commerce/commerce-api/guide/base-url.html#realm-id) and a 3-character [instance type identifier](https://developer.salesforce.com/docs/commerce/commerce-api/guide/base-url.html#instance-id).
                 * @example f_ecom_zzxy_prd
                 */
                organizationId: components["parameters"]["organizationId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Retrieved Site Custom Preferences successfully. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CustomPreferenceList"];
                };
            };
            /** @description Thrown if the query is ill-formed. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /**
             * @description Unauthorized. Your Client ID is invalid, or you are not allowed to access
             *     the content provided by the requested URL.
             */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    getGlobalPreferenceGroup: {
        parameters: {
            query?: {
                /** @description The preference values of type Password are masked when set. */
                maskPasswords?: components["parameters"]["maskPasswords"];
                /** @description Expands the result document to include additional information. For global preference groups, the expansion "sites" retrieves the custom preferences for all the available sites. */
                expand?: components["parameters"]["globalPreferenceGroupExpand"];
            };
            header?: never;
            path: {
                /**
                 * @description An identifier for the Salesforce Commerce Cloud organization the request is being made by. It consists of a prefix 'f_ecom_' followed by a 4-character [realm identifier](https://developer.salesforce.com/docs/commerce/commerce-api/guide/base-url.html#realm-id) and a 3-character [instance type identifier](https://developer.salesforce.com/docs/commerce/commerce-api/guide/base-url.html#instance-id).
                 * @example f_ecom_zzxy_prd
                 */
                organizationId: components["parameters"]["organizationId"];
                /** @description The preference group ID. */
                groupId: components["parameters"]["groupId"];
                /**
                 * @description The instance type for which to read or update preferences.
                 * @example staging
                 */
                instanceType: components["parameters"]["instanceType"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Custom preferences retrieved successfully. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OrganizationPreferences"];
                };
            };
            /** @description Invalid instance type was provided. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description The preference group was not found. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    updateGlobalPreferenceGroup: {
        parameters: {
            query?: {
                /** @description The preference values of type Password are masked when set. */
                maskPasswords?: components["parameters"]["maskPasswords"];
            };
            header?: never;
            path: {
                /**
                 * @description An identifier for the Salesforce Commerce Cloud organization the request is being made by. It consists of a prefix 'f_ecom_' followed by a 4-character [realm identifier](https://developer.salesforce.com/docs/commerce/commerce-api/guide/base-url.html#realm-id) and a 3-character [instance type identifier](https://developer.salesforce.com/docs/commerce/commerce-api/guide/base-url.html#instance-id).
                 * @example f_ecom_zzxy_prd
                 */
                organizationId: components["parameters"]["organizationId"];
                /** @description The preference group ID. */
                groupId: components["parameters"]["groupId"];
                /**
                 * @description The instance type for which to read or update preferences.
                 * @example staging
                 */
                instanceType: components["parameters"]["instanceType"];
            };
            cookie?: never;
        };
        /** @description The preferences to update. Custom preference attributes use the "c_" prefix. */
        requestBody: {
            content: {
                "application/json": components["schemas"]["OrganizationPreferences"];
            };
        };
        responses: {
            /** @description Custom preferences updated successfully. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OrganizationPreferences"];
                };
            };
            /** @description Invalid instance type was provided. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description The preference group was not found. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    getSitePreferenceGroup: {
        parameters: {
            query: {
                /** @description The preference values of type Password are masked when set. */
                maskPasswords?: components["parameters"]["maskPasswords"];
                /** @description The identifier of the site that a request is being made in the context of. Attributes might have site specific values, and some objects may only be assigned to specific sites. */
                siteId: components["parameters"]["siteId"];
            };
            header?: never;
            path: {
                /**
                 * @description An identifier for the Salesforce Commerce Cloud organization the request is being made by. It consists of a prefix 'f_ecom_' followed by a 4-character [realm identifier](https://developer.salesforce.com/docs/commerce/commerce-api/guide/base-url.html#realm-id) and a 3-character [instance type identifier](https://developer.salesforce.com/docs/commerce/commerce-api/guide/base-url.html#instance-id).
                 * @example f_ecom_zzxy_prd
                 */
                organizationId: components["parameters"]["organizationId"];
                /** @description The preference group ID. */
                groupId: components["parameters"]["groupId"];
                /**
                 * @description The instance type for which to read or update preferences.
                 * @example staging
                 */
                instanceType: components["parameters"]["instanceType"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Custom site preferences retrieved successfully. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SitePreferences"];
                };
            };
            /** @description Invalid instance type was provided. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description The preference group was not found. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    updateSitePreferenceGroup: {
        parameters: {
            query: {
                /** @description The preference values of type Password are masked when set. */
                maskPasswords?: components["parameters"]["maskPasswords"];
                /** @description The identifier of the site that a request is being made in the context of. Attributes might have site specific values, and some objects may only be assigned to specific sites. */
                siteId: components["parameters"]["siteId"];
            };
            header?: never;
            path: {
                /**
                 * @description An identifier for the Salesforce Commerce Cloud organization the request is being made by. It consists of a prefix 'f_ecom_' followed by a 4-character [realm identifier](https://developer.salesforce.com/docs/commerce/commerce-api/guide/base-url.html#realm-id) and a 3-character [instance type identifier](https://developer.salesforce.com/docs/commerce/commerce-api/guide/base-url.html#instance-id).
                 * @example f_ecom_zzxy_prd
                 */
                organizationId: components["parameters"]["organizationId"];
                /** @description The preference group ID. */
                groupId: components["parameters"]["groupId"];
                /**
                 * @description The instance type for which to read or update preferences.
                 * @example staging
                 */
                instanceType: components["parameters"]["instanceType"];
            };
            cookie?: never;
        };
        /** @description The site preferences to update. Custom preference attributes use the "c_" prefix. */
        requestBody: {
            content: {
                "application/json": components["schemas"]["SitePreferences"];
            };
        };
        responses: {
            /** @description Custom site preferences updated successfully. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SitePreferences"];
                };
            };
            /** @description Invalid instance type was provided. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description The preference group was not found. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    searchSitePreferences: {
        parameters: {
            query?: {
                /** @description The preference values of type Password are masked when set. */
                maskPasswords?: components["parameters"]["maskPasswords"];
                /** @description Expands the result document to include additional information. For preference search, the expansion "value" retrieves the value definitions of the attribute definition. */
                expand?: components["parameters"]["preferenceSearchExpand"];
            };
            header?: never;
            path: {
                /**
                 * @description An identifier for the Salesforce Commerce Cloud organization the request is being made by. It consists of a prefix 'f_ecom_' followed by a 4-character [realm identifier](https://developer.salesforce.com/docs/commerce/commerce-api/guide/base-url.html#realm-id) and a 3-character [instance type identifier](https://developer.salesforce.com/docs/commerce/commerce-api/guide/base-url.html#instance-id).
                 * @example f_ecom_zzxy_prd
                 */
                organizationId: components["parameters"]["organizationId"];
                /** @description The preference group ID. */
                groupId: components["parameters"]["groupId"];
                /**
                 * @description The instance type for which to read or update preferences.
                 * @example staging
                 */
                instanceType: components["parameters"]["instanceType"];
            };
            cookie?: never;
        };
        /** @description The search request document. */
        requestBody: {
            content: {
                "application/json": components["schemas"]["SearchRequest"];
            };
        };
        responses: {
            /** @description Preference search executed successfully. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PreferenceValueSearchResult"];
                };
            };
            /**
             * @description The request is malformed. This can be caused by an invalid instance type,
             *     an ill-formed search query, or attempting to sort by a non-sortable field.
             */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description The preference group was not found. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    getSitePreference: {
        parameters: {
            query?: {
                /** @description The preference values of type Password are masked when set. */
                maskPasswords?: components["parameters"]["maskPasswords"];
            };
            header?: never;
            path: {
                /**
                 * @description An identifier for the Salesforce Commerce Cloud organization the request is being made by. It consists of a prefix 'f_ecom_' followed by a 4-character [realm identifier](https://developer.salesforce.com/docs/commerce/commerce-api/guide/base-url.html#realm-id) and a 3-character [instance type identifier](https://developer.salesforce.com/docs/commerce/commerce-api/guide/base-url.html#instance-id).
                 * @example f_ecom_zzxy_prd
                 */
                organizationId: components["parameters"]["organizationId"];
                /** @description The preference group ID. */
                groupId: components["parameters"]["groupId"];
                /**
                 * @description The instance type for which to read or update preferences.
                 * @example staging
                 */
                instanceType: components["parameters"]["instanceType"];
                /** @description The preference attribute ID. */
                preferenceId: components["parameters"]["preferenceId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Preference value retrieved successfully. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PreferenceValue"];
                };
            };
            /** @description Invalid instance type was provided. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description The preference group or preference was not found. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    updateSitePreference: {
        parameters: {
            query?: {
                /** @description The preference values of type Password are masked when set. */
                maskPasswords?: components["parameters"]["maskPasswords"];
            };
            header?: never;
            path: {
                /**
                 * @description An identifier for the Salesforce Commerce Cloud organization the request is being made by. It consists of a prefix 'f_ecom_' followed by a 4-character [realm identifier](https://developer.salesforce.com/docs/commerce/commerce-api/guide/base-url.html#realm-id) and a 3-character [instance type identifier](https://developer.salesforce.com/docs/commerce/commerce-api/guide/base-url.html#instance-id).
                 * @example f_ecom_zzxy_prd
                 */
                organizationId: components["parameters"]["organizationId"];
                /** @description The preference group ID. */
                groupId: components["parameters"]["groupId"];
                /**
                 * @description The instance type for which to read or update preferences.
                 * @example staging
                 */
                instanceType: components["parameters"]["instanceType"];
                /** @description The preference attribute ID. */
                preferenceId: components["parameters"]["preferenceId"];
            };
            cookie?: never;
        };
        /** @description The preference value to update with site-specific values. */
        requestBody: {
            content: {
                "application/json": components["schemas"]["PreferenceValue"];
            };
        };
        responses: {
            /** @description Preference value updated successfully. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PreferenceValue"];
                };
            };
            /** @description Invalid instance type was provided. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description The preference group or preference was not found. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
}
type WithRequired<T, K extends keyof T> = T & {
    [P in K]-?: T[P];
};
