/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/organizations/{organizationId}/cors": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Return all CORS preferences for the given site.
         * @description Return all CORS preferences for the given site.
         */
        get: operations["getCorsPreferences"];
        /**
         * Create or replace all CORS preferences for the given site.
         * @description Create or replace all CORS preferences for the given site.
         */
        put: operations["updateCorsPreferences"];
        post?: never;
        /**
         * Delete all CORS preferences for the given site.
         * @description Delete all CORS preferences for the given site.
         */
        delete: operations["deleteCorsPreferences"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * @description An identifier for the organization the request is being made by
         * @example f_ecom_zzxy_prd
         */
        OrganizationId: string;
        /**
         * @description The identifier of the site that a request is being made in the context of. Attributes might have site specific values, and some objects may only be assigned to specific sites
         * @example RefArch
         */
        SiteId: string;
        /** @description Document representing all CORS preferences of a specific client */
        CorsClientPreferences: {
            /**
             * @description Client ID
             * @example 12345678-90ab-cdef-fedc-ba0987654321
             */
            clientId: string;
            /** @description List containing allowed origins in the format '<scheme>://<domain>.<tld>' */
            origins: string[];
        };
        /** @description Document representing all CORS preferences for a given site */
        CorsPreferences: {
            /** @description List of client-specific CORS preferences */
            corsClientPreferences?: components["schemas"]["CorsClientPreferences"][];
        };
        ErrorResponse: {
            /**
             * @description A short, human-readable summary of the problem
             *     type.  It will not change from occurrence to occurrence of the
             *     problem, except for purposes of localization
             * @example You do not have enough credit
             */
            title: string;
            /**
             * @description A URI reference [RFC3986] that identifies the
             *     problem type.  This specification encourages that, when
             *     dereferenced, it provide human-readable documentation for the
             *     problem type (e.g., using HTML [W3C.REC-html5-20141028]).  When
             *     this member is not present, its value is assumed to be
             *     "about:blank". It accepts relative URIs; this means
             *     that they must be resolved relative to the document's base URI, as
             *     per [RFC3986], Section 5.
             * @example NotEnoughMoney
             */
            type: string;
            /**
             * @description A human-readable explanation specific to this occurrence of the problem.
             * @example Your current balance is 30, but that costs 50
             */
            detail: string;
            /**
             * @description A URI reference that identifies the specific
             *     occurrence of the problem.  It may or may not yield further
             *     information if dereferenced.  It accepts relative URIs; this means
             *     that they must be resolved relative to the document's base URI, as
             *     per [RFC3986], Section 5.
             * @example /account/12345/msgs/abc
             */
            instance?: string;
        } & {
            [key: string]: unknown;
        };
    };
    responses: never;
    parameters: {
        /**
         * @description An identifier for the organization the request is being made by
         * @example f_ecom_zzxy_prd
         */
        organizationId: components["schemas"]["OrganizationId"];
        /** @description The identifier of the site that a request is being made in the context of. Attributes might have site specific values, and some objects may only be assigned to specific sites. */
        siteId: components["schemas"]["SiteId"];
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    getCorsPreferences: {
        parameters: {
            query: {
                /** @description The identifier of the site that a request is being made in the context of. Attributes might have site specific values, and some objects may only be assigned to specific sites. */
                siteId: components["parameters"]["siteId"];
            };
            header?: never;
            path: {
                /**
                 * @description An identifier for the organization the request is being made by
                 * @example f_ecom_zzxy_prd
                 */
                organizationId: components["parameters"]["organizationId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description CORS preferences for the given site returned successfully. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CorsPreferences"];
                };
            };
        };
    };
    updateCorsPreferences: {
        parameters: {
            query: {
                /** @description The identifier of the site that a request is being made in the context of. Attributes might have site specific values, and some objects may only be assigned to specific sites. */
                siteId: components["parameters"]["siteId"];
            };
            header?: never;
            path: {
                /**
                 * @description An identifier for the organization the request is being made by
                 * @example f_ecom_zzxy_prd
                 */
                organizationId: components["parameters"]["organizationId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CorsPreferences"];
            };
        };
        responses: {
            /** @description CORS preferences for the given site replaced successfully. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CorsPreferences"];
                };
            };
            /** @description CORS preferences successfully created for the given site. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CorsPreferences"];
                };
            };
            /**
             * @description Possible reasons:
             *     - The clientId is missing.
             *     - The domain names in the origins list are invalid.
             */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    deleteCorsPreferences: {
        parameters: {
            query: {
                /** @description The identifier of the site that a request is being made in the context of. Attributes might have site specific values, and some objects may only be assigned to specific sites. */
                siteId: components["parameters"]["siteId"];
            };
            header?: never;
            path: {
                /**
                 * @description An identifier for the organization the request is being made by
                 * @example f_ecom_zzxy_prd
                 */
                organizationId: components["parameters"]["organizationId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description CORS preferences for the given site deleted successfully. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
}
