/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/organizations/{organizationId}/job-execution-search": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["searchJobExecutions"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/organizations/{organizationId}/jobs/{jobId}/executions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["createJobExecution"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/organizations/{organizationId}/jobs/{jobId}/executions/{executionId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getJobExecution"];
        put?: never;
        post?: never;
        delete: operations["deleteJobExecution"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        OrganizationId: string;
        Query: {
            boolQuery?: components["schemas"]["BoolQuery"];
            filteredQuery?: components["schemas"]["FilteredQuery"];
            matchAllQuery?: components["schemas"]["MatchAllQuery"];
            nestedQuery?: components["schemas"]["NestedQuery"];
            termQuery?: components["schemas"]["TermQuery"];
            textQuery?: components["schemas"]["TextQuery"];
        };
        BoolQuery: {
            must?: components["schemas"]["Query"][];
            mustNot?: components["schemas"]["Query"][];
            should?: components["schemas"]["Query"][];
        };
        Filter: {
            boolFilter?: components["schemas"]["BoolFilter"];
            queryFilter?: components["schemas"]["QueryFilter"];
            range2Filter?: components["schemas"]["Range2Filter"];
            rangeFilter?: components["schemas"]["RangeFilter"];
            termFilter?: components["schemas"]["TermFilter"];
        };
        BoolFilter: {
            filters?: components["schemas"]["Filter"][];
            /** @enum {string} */
            operator: "and" | "or" | "not";
        };
        QueryFilter: {
            query: components["schemas"]["Query"];
        };
        Field: string;
        Range2Filter: {
            /**
             * @default overlap
             * @enum {string}
             */
            filterMode: "overlap" | "containing" | "contained";
            fromField: components["schemas"]["Field"];
            /** @default true */
            fromInclusive: boolean;
            fromValue?: unknown;
            toField: components["schemas"]["Field"];
            /** @default true */
            toInclusive: boolean;
            toValue?: unknown;
        };
        RangeFilter: {
            field: components["schemas"]["Field"];
            from?: string | number;
            /** @default true */
            fromInclusive: boolean;
            to?: string | number;
            /** @default true */
            toInclusive: boolean;
        };
        TermFilter: {
            field: components["schemas"]["Field"];
            /** @enum {string} */
            operator: "is" | "one_of" | "is_null" | "is_not_null" | "less" | "greater" | "not_in" | "neq";
            values?: string[];
        };
        FilteredQuery: {
            filter: components["schemas"]["Filter"];
            query: components["schemas"]["Query"];
        };
        MatchAllQuery: Record<string, never>;
        NestedQuery: {
            path: string;
            query: components["schemas"]["Query"];
            /** @enum {string} */
            scoreMode?: "avg" | "total" | "max" | "none";
        };
        TermQuery: {
            fields: components["schemas"]["Field"][];
            /** @enum {string} */
            operator: "is" | "one_of" | "is_null" | "is_not_null" | "less" | "greater" | "not_in" | "neq";
            values?: (string | number | boolean)[];
        };
        TextQuery: {
            fields: components["schemas"]["Field"][];
            searchPhrase: string;
        };
        Sort: {
            field: string;
            /**
             * @default asc
             * @enum {string}
             */
            sortOrder: "asc" | "desc";
        };
        /**
         * Format: int32
         * @default 0
         */
        Offset: number;
        SearchRequest: {
            /** Format: int32 */
            limit?: number;
            query: components["schemas"]["Query"];
            sorts?: components["schemas"]["Sort"][];
            offset?: components["schemas"]["Offset"];
        };
        JobExecutionSearchRequest: components["schemas"]["SearchRequest"];
        /**
         * Format: int32
         * @default 0
         */
        Total: number;
        ResultBase: {
            /** Format: int32 */
            limit: number;
            total: components["schemas"]["Total"];
        };
        PaginatedResultBase: {
            offset: components["schemas"]["Offset"];
        } & WithRequired<components["schemas"]["ResultBase"], "limit" | "total">;
        PaginatedSearchResult: {
            query: components["schemas"]["Query"];
            sorts?: components["schemas"]["Sort"][];
            hits?: Record<string, never>[];
        } & components["schemas"]["PaginatedResultBase"];
        /** @enum {string} */
        ExecutionStatus: "pending" | "running" | "pausing" | "paused" | "resuming" | "resumed" | "restarting" | "restarted" | "retrying" | "retried" | "aborting" | "aborted" | "finished" | "unknown";
        ExitStatus: {
            code?: string;
            message?: string;
            /** @enum {string} */
            status?: "ok" | "error";
        };
        StatusMetadata: {
            clientId?: string;
            reason?: string;
            userLogin?: string;
        };
        JobParameter: {
            name: string;
            value: string;
        };
        JobExecutionRetryInformation: {
            /** Format: int32 */
            currentRetryAttempt?: number;
            /** Format: int32 */
            maxRetries?: number;
        };
        JobExecutionContinueInformation: {
            isPending?: boolean;
            continueStatus?: string;
        };
        JobStepExecution: {
            id?: string;
            stepId?: string;
            stepDescription?: string;
            stepTypeId?: string;
            stepTypeInfo?: string;
            executionScope?: string;
            executionStatus?: components["schemas"]["ExecutionStatus"];
            status?: string;
            /** Format: date-time */
            startTime?: string;
            /** Format: date-time */
            endTime?: string;
            /** Format: int64 */
            duration?: number;
            /** Format: date-time */
            modificationTime?: string;
            statusMetadata?: components["schemas"]["StatusMetadata"];
            exitStatus?: components["schemas"]["ExitStatus"];
            includeStepsFromJobId?: string;
            isChunkOriented?: boolean;
            /** Format: int32 */
            chunkSize?: number;
            /** Format: int32 */
            itemFilterCount?: number;
            /** Format: int32 */
            itemWriteCount?: number;
            /** Format: int64 */
            totalItemCount?: number;
        };
        JobExecution: {
            id: string;
            jobId: string;
            jobDescription?: string;
            clientId?: string;
            userLogin?: string;
            executionStatus?: components["schemas"]["ExecutionStatus"];
            status: string;
            /** Format: date-time */
            startTime?: string;
            /** Format: date-time */
            endTime?: string;
            /** Format: date-time */
            creationDate?: string;
            /** Format: int64 */
            duration?: number;
            /** Format: int64 */
            effectiveDuration?: number;
            /** Format: date-time */
            modificationTime?: string;
            /** Format: date-time */
            lastModified?: string;
            executedServerId?: string;
            exitStatus?: components["schemas"]["ExitStatus"];
            statusMetadata?: components["schemas"]["StatusMetadata"];
            isLogFileExisting?: boolean;
            isRestart?: boolean;
            logFilePath?: string;
            parameters?: components["schemas"]["JobParameter"][];
            executionScopes?: string[];
            retryInformation?: components["schemas"]["JobExecutionRetryInformation"];
            continueInformation?: components["schemas"]["JobExecutionContinueInformation"];
            stepExecutions?: components["schemas"]["JobStepExecution"][];
        };
        JobExecutionSearchResult: {
            hits: components["schemas"]["JobExecution"][];
        } & WithRequired<components["schemas"]["PaginatedSearchResult"], "hits" | "query">;
        ErrorResponse: {
            title: string;
            type: string;
            detail: string;
            instance?: string;
        } & {
            [key: string]: unknown;
        };
        JobExecutionRequest: {
            parameters?: components["schemas"]["JobParameter"][];
        };
    };
    responses: {
        /** @description Your access token is invalid or expired and can’t be used to identify a user. */
        "401unauthorized": {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["ErrorResponse"];
            };
        };
        /** @description Forbidden. Your access token is valid, but you don’t have the required permissions to access the resource. */
        "403forbidden": {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["ErrorResponse"];
            };
        };
    };
    parameters: {
        organizationId: components["schemas"]["OrganizationId"];
        jobId: string;
        executionId: string;
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    searchJobExecutions: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                organizationId: components["schemas"]["OrganizationId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["JobExecutionSearchRequest"];
            };
        };
        responses: {
            /** @description Returns job execution search results */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobExecutionSearchResult"];
                };
            };
            /** @description Bad Request - Malformed search query or invalid parameters */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Your access token is invalid or expired and can’t be used to identify a user. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Forbidden. Your access token is valid, but you don’t have the required permissions to access the resource. */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    createJobExecution: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                organizationId: components["schemas"]["OrganizationId"];
                jobId: string;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["JobExecutionRequest"];
            };
        };
        responses: {
            /** @description The job execution was successfully created */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobExecution"];
                };
            };
            /** @description Bad Request - Invalid job execution request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Your access token is invalid or expired and can’t be used to identify a user. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Forbidden. Your access token is valid, but you don’t have the required permissions to access the resource. */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Job not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    getJobExecution: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                organizationId: components["schemas"]["OrganizationId"];
                jobId: string;
                executionId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Returns the job execution details */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobExecution"];
                };
            };
            /** @description Your access token is invalid or expired and can’t be used to identify a user. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Forbidden. Your access token is valid, but you don’t have the required permissions to access the resource. */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Job execution not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    deleteJobExecution: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                organizationId: components["schemas"]["OrganizationId"];
                jobId: string;
                executionId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The job execution was successfully deleted */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Your access token is invalid or expired and can’t be used to identify a user. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Forbidden. Your access token is valid, but you don’t have the required permissions to access the resource. */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Job execution not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
}
type WithRequired<T, K extends keyof T> = T & {
    [P in K]-?: T[P];
};
