/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/organizations/{organizationId}/users": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getUsers"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/organizations/{organizationId}/users/{login}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getUser"];
        put: operations["createOrReplaceUser"];
        post?: never;
        delete: operations["deleteUser"];
        options?: never;
        head?: never;
        patch: operations["updateUser"];
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        OrganizationId: string;
        Select: string;
        /**
         * Format: int32
         * @default 0
         */
        Total: number;
        ResultBase: {
            /** Format: int32 */
            limit: number;
            total: components["schemas"]["Total"];
        };
        /**
         * Format: int32
         * @default 0
         */
        Offset: number;
        PaginatedResultBase: {
            offset: components["schemas"]["Offset"];
        } & WithRequired<components["schemas"]["ResultBase"], "limit" | "total">;
        LanguageCountry: string;
        LanguageCode: string;
        /** @default default */
        DefaultFallback: string;
        LocaleCode: components["schemas"]["LanguageCountry"] | components["schemas"]["LanguageCode"] | components["schemas"]["DefaultFallback"];
        User: {
            login: string;
            password?: string;
            email: string;
            firstName?: string;
            lastName?: string;
            externalId?: string;
            disabled?: boolean;
            locked?: boolean;
            /** Format: date */
            lastLoginDate?: string;
            /** Format: date-time */
            passwordExpirationDate?: string;
            /** Format: date-time */
            passwordModificationDate?: string;
            preferredDataLocale?: components["schemas"]["LocaleCode"];
            preferredUiLocale?: components["schemas"]["LocaleCode"];
            roles?: string[];
        };
        UserSearch: {
            data: components["schemas"]["User"][];
        } & components["schemas"]["PaginatedResultBase"];
        ErrorResponse: {
            title: string;
            type: string;
            detail: string;
            instance?: string;
        } & {
            [key: string]: unknown;
        };
        UserUpdateRequest: {
            email?: string;
            firstName?: string;
            lastName?: string;
            externalId?: string;
            preferredDataLocale?: components["schemas"]["LocaleCode"];
            preferredUiLocale?: components["schemas"]["LocaleCode"];
        };
    };
    responses: never;
    parameters: {
        organizationId: components["schemas"]["OrganizationId"];
        select: components["schemas"]["Select"];
        login: string;
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    getUsers: {
        parameters: {
            query?: {
                select?: components["schemas"]["Select"];
                limit?: number;
                offset?: number;
            };
            header?: never;
            path: {
                organizationId: components["schemas"]["OrganizationId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Returns the collection of users */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserSearch"];
                };
            };
        };
    };
    getUser: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                organizationId: components["schemas"]["OrganizationId"];
                login: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Returns the user details */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["User"];
                };
            };
            /** @description User not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    createOrReplaceUser: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                organizationId: components["schemas"]["OrganizationId"];
                login: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["User"];
            };
        };
        responses: {
            /** @description The user was successfully updated */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["User"];
                };
            };
            /** @description The user was successfully created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["User"];
                };
            };
            /** @description Bad Request - Invalid user request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    deleteUser: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                organizationId: components["schemas"]["OrganizationId"];
                login: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The user was successfully deleted */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description User not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    updateUser: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                organizationId: components["schemas"]["OrganizationId"];
                login: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UserUpdateRequest"];
            };
        };
        responses: {
            /** @description The user was successfully updated */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["User"];
                };
            };
            /** @description Bad Request - Invalid user update request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description User not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
}
type WithRequired<T, K extends keyof T> = T & {
    [P in K]-?: T[P];
};
