/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/organizations/{organizationId}/site-search": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["searchSites"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/organizations/{organizationId}/sites": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getSites"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/organizations/{organizationId}/sites/{siteId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getSiteById"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        OrganizationId: string;
        Query: {
            boolQuery?: components["schemas"]["BoolQuery"];
            filteredQuery?: components["schemas"]["FilteredQuery"];
            matchAllQuery?: components["schemas"]["MatchAllQuery"];
            nestedQuery?: components["schemas"]["NestedQuery"];
            termQuery?: components["schemas"]["TermQuery"];
            textQuery?: components["schemas"]["TextQuery"];
        };
        BoolQuery: {
            must?: components["schemas"]["Query"][];
            mustNot?: components["schemas"]["Query"][];
            should?: components["schemas"]["Query"][];
        };
        Filter: {
            boolFilter?: components["schemas"]["BoolFilter"];
            queryFilter?: components["schemas"]["QueryFilter"];
            range2Filter?: components["schemas"]["Range2Filter"];
            rangeFilter?: components["schemas"]["RangeFilter"];
            termFilter?: components["schemas"]["TermFilter"];
        };
        BoolFilter: {
            filters?: components["schemas"]["Filter"][];
            /** @enum {string} */
            operator: "and" | "or" | "not";
        };
        QueryFilter: {
            query: components["schemas"]["Query"];
        };
        Field: string;
        Range2Filter: {
            /**
             * @default overlap
             * @enum {string}
             */
            filterMode: "overlap" | "containing" | "contained";
            fromField: components["schemas"]["Field"];
            /** @default true */
            fromInclusive: boolean;
            fromValue?: unknown;
            toField: components["schemas"]["Field"];
            /** @default true */
            toInclusive: boolean;
            toValue?: unknown;
        };
        RangeFilter: {
            field: components["schemas"]["Field"];
            from?: string | number;
            /** @default true */
            fromInclusive: boolean;
            to?: string | number;
            /** @default true */
            toInclusive: boolean;
        };
        TermFilter: {
            field: components["schemas"]["Field"];
            /** @enum {string} */
            operator: "is" | "one_of" | "is_null" | "is_not_null" | "less" | "greater" | "not_in" | "neq";
            values?: string[];
        };
        FilteredQuery: {
            filter: components["schemas"]["Filter"];
            query: components["schemas"]["Query"];
        };
        MatchAllQuery: Record<string, never>;
        NestedQuery: {
            path: string;
            query: components["schemas"]["Query"];
            /** @enum {string} */
            scoreMode?: "avg" | "total" | "max" | "none";
        };
        TermQuery: {
            fields: components["schemas"]["Field"][];
            /** @enum {string} */
            operator: "is" | "one_of" | "is_null" | "is_not_null" | "less" | "greater" | "not_in" | "neq";
            values?: (string | number | boolean)[];
        };
        TextQuery: {
            fields: components["schemas"]["Field"][];
            searchPhrase: string;
        };
        Sort: {
            field: string;
            /**
             * @default asc
             * @enum {string}
             */
            sortOrder: "asc" | "desc";
        };
        /**
         * Format: int32
         * @default 0
         */
        Offset: number;
        SearchRequest: {
            /** Format: int32 */
            limit?: number;
            query: components["schemas"]["Query"];
            sorts?: components["schemas"]["Sort"][];
            offset?: components["schemas"]["Offset"];
        };
        SiteSearchRequest: components["schemas"]["SearchRequest"];
        /**
         * Format: int32
         * @default 0
         */
        Total: number;
        ResultBase: {
            /** Format: int32 */
            limit: number;
            total: components["schemas"]["Total"];
        };
        PaginatedResultBase: {
            offset: components["schemas"]["Offset"];
        } & WithRequired<components["schemas"]["ResultBase"], "limit" | "total">;
        PaginatedSearchResult: {
            query: components["schemas"]["Query"];
            sorts?: components["schemas"]["Sort"][];
            hits?: Record<string, never>[];
        } & components["schemas"]["PaginatedResultBase"];
        SiteId: string;
        CustomerListLink: {
            customerListId?: string;
            title?: string;
        };
        Site: {
            id: components["schemas"]["SiteId"];
            displayName?: {
                [key: string]: string;
            };
            description?: {
                [key: string]: string;
            };
            customerListLink?: components["schemas"]["CustomerListLink"];
            inDeletion?: boolean;
            /** @enum {string} */
            storefrontStatus?: "online" | "maintenance" | "to_be_deleted" | "protected";
            siteCatalogId?: string;
            cartridges?: string;
            /** Format: date-time */
            creationDate?: string;
            /** Format: date-time */
            lastModified?: string;
        };
        SiteSearchResult: {
            hits: components["schemas"]["Site"][];
        } & WithRequired<components["schemas"]["PaginatedSearchResult"], "hits" | "query">;
        ErrorResponse: {
            title: string;
            type: string;
            detail: string;
            instance?: string;
        } & {
            [key: string]: unknown;
        };
        Select: string;
        Sites: {
            data: components["schemas"]["Site"][];
        } & components["schemas"]["PaginatedResultBase"];
    };
    responses: {
        /** @description Your access token is invalid or expired and can’t be used to identify a user. */
        "401unauthorized": {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["ErrorResponse"];
            };
        };
        /** @description Forbidden. Your access token is valid, but you don’t have the required permissions to access the resource. */
        "403forbidden": {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["ErrorResponse"];
            };
        };
    };
    parameters: {
        organizationId: components["schemas"]["OrganizationId"];
        select: components["schemas"]["Select"];
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    searchSites: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                organizationId: components["schemas"]["OrganizationId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SiteSearchRequest"];
            };
        };
        responses: {
            /** @description Returns site search results */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SiteSearchResult"];
                };
            };
            /** @description Bad Request - Malformed search query or invalid parameters */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Your access token is invalid or expired and can’t be used to identify a user. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Forbidden. Your access token is valid, but you don’t have the required permissions to access the resource. */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    getSites: {
        parameters: {
            query?: {
                select?: components["schemas"]["Select"];
                limit?: number;
                offset?: number;
            };
            header?: never;
            path: {
                organizationId: components["schemas"]["OrganizationId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Returns a paginated list of sites */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Sites"];
                };
            };
            /** @description Your access token is invalid or expired and can’t be used to identify a user. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Forbidden. Your access token is valid, but you don’t have the required permissions to access the resource. */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    getSiteById: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                organizationId: components["schemas"]["OrganizationId"];
                siteId: components["schemas"]["SiteId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Returns the requested site */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Site"];
                };
            };
            /** @description Your access token is invalid or expired and can’t be used to identify a user. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Forbidden. Your access token is valid, but you don’t have the required permissions to access the resource. */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Site Not Found - The requested site ID does not exist */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
}
type WithRequired<T, K extends keyof T> = T & {
    [P in K]-?: T[P];
};
