/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/organizations/{organizationId}/code-versions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getCodeVersions"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/organizations/{organizationId}/code-versions/{codeVersionId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getCodeVersion"];
        put: operations["createCodeVersion"];
        post?: never;
        delete: operations["deleteCodeVersion"];
        options?: never;
        head?: never;
        patch: operations["updateCodeVersion"];
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        OrganizationId: string;
        /**
         * Format: int32
         * @default 0
         */
        Total: number;
        ResultBase: {
            /** Format: int32 */
            limit: number;
            total: components["schemas"]["Total"];
        };
        CodeVersion: {
            id?: string;
            active?: boolean;
            cartridges?: string[];
            compatibilityMode?: string;
            /** Format: date-time */
            activationTime?: string;
            /** Format: date-time */
            lastModificationTime?: string;
            rollback?: boolean;
            /** Format: int64 */
            totalSize?: number;
            webDavUrl?: string;
        };
        CodeVersionResult: {
            data?: components["schemas"]["CodeVersion"][];
        } & components["schemas"]["ResultBase"];
        ErrorResponse: {
            title: string;
            type: string;
            detail: string;
            instance?: string;
        } & {
            [key: string]: unknown;
        };
    };
    responses: {
        /** @description Your access token is invalid or expired and can’t be used to identify a user. */
        "401unauthorized": {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["ErrorResponse"];
            };
        };
        /** @description Forbidden. Your access token is valid, but you don’t have the required permissions to access the resource. */
        "403forbidden": {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["ErrorResponse"];
            };
        };
    };
    parameters: {
        organizationId: components["schemas"]["OrganizationId"];
        expand: "size"[];
        codeVersionId: string;
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    getCodeVersions: {
        parameters: {
            query?: {
                expand?: "size"[];
            };
            header?: never;
            path: {
                organizationId: components["schemas"]["OrganizationId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description List of code versions successfully retrieved. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CodeVersionResult"];
                };
            };
            /** @description Your access token is invalid or expired and can’t be used to identify a user. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Forbidden. Your access token is valid, but you don’t have the required permissions to access the resource. */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    getCodeVersion: {
        parameters: {
            query?: {
                expand?: "size"[];
            };
            header?: never;
            path: {
                organizationId: components["schemas"]["OrganizationId"];
                codeVersionId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Code version successfully retrieved. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CodeVersion"];
                };
            };
            /** @description Your access token is invalid or expired and can’t be used to identify a user. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Forbidden. Your access token is valid, but you don’t have the required permissions to access the resource. */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Code version not found. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    createCodeVersion: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                organizationId: components["schemas"]["OrganizationId"];
                codeVersionId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Code version successfully replaced. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CodeVersion"];
                };
            };
            /** @description Code version successfully created. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CodeVersion"];
                };
            };
            /** @description Your access token is invalid or expired and can’t be used to identify a user. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Forbidden. Your access token is valid, but you don’t have the required permissions to access the resource. */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description A code version with the given ID already exists. */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    deleteCodeVersion: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                organizationId: components["schemas"]["OrganizationId"];
                codeVersionId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Code version successfully deleted. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description The active code version cannot be deleted. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Your access token is invalid or expired and can’t be used to identify a user. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Forbidden. Your access token is valid, but you don’t have the required permissions to access the resource. */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Code version not found. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    updateCodeVersion: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                organizationId: components["schemas"]["OrganizationId"];
                codeVersionId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CodeVersion"];
            };
        };
        responses: {
            /** @description Code version successfully updated. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CodeVersion"];
                };
            };
            /** @description The active code version cannot be modified. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Your access token is invalid or expired and can’t be used to identify a user. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Forbidden. Your access token is valid, but you don’t have the required permissions to access the resource. */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Code version not found. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description A code version with the given ID already exists (when renaming). */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
}
