/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/organizations/{organizationId}/roles": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getRoles"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/organizations/{organizationId}/roles/{roleId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getRole"];
        put: operations["createRole"];
        post?: never;
        delete: operations["deleteRole"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/organizations/{organizationId}/roles/{roleId}/permissions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getRolePermissions"];
        put: operations["setRolePermissions"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/organizations/{organizationId}/roles/{roleId}/user-search": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["searchRoleUsers"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/organizations/{organizationId}/roles/{roleId}/users": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getRoleUsers"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/organizations/{organizationId}/roles/{roleId}/users/{login}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put: operations["assignUserToRole"];
        post?: never;
        delete: operations["unassignUserFromRole"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        OrganizationId: string;
        Select: string;
        /**
         * Format: int32
         * @default 0
         */
        Total: number;
        ResultBase: {
            /** Format: int32 */
            limit: number;
            total: components["schemas"]["Total"];
        };
        /**
         * Format: int32
         * @default 0
         */
        Offset: number;
        PaginatedResultBase: {
            offset: components["schemas"]["Offset"];
        } & WithRequired<components["schemas"]["ResultBase"], "limit" | "total">;
        RoleModulePermission: {
            name: string;
            type: string;
            application: string;
            system?: boolean;
            value?: string;
            values?: {
                [key: string]: string;
            };
        };
        RoleModulePermissions: {
            organization?: components["schemas"]["RoleModulePermission"][];
            site?: components["schemas"]["RoleModulePermission"][];
        };
        RoleFunctionalPermission: {
            name: string;
            type: string;
            value?: string;
            values?: {
                [key: string]: string;
            };
        };
        RoleFunctionalPermissions: {
            organization?: components["schemas"]["RoleFunctionalPermission"][];
            site?: components["schemas"]["RoleFunctionalPermission"][];
        };
        LanguageCountry: string;
        LanguageCode: string;
        /** @default default */
        DefaultFallback: string;
        LocaleCode: components["schemas"]["LanguageCountry"] | components["schemas"]["LanguageCode"] | components["schemas"]["DefaultFallback"];
        RoleLocalePermission: {
            localeId: components["schemas"]["LocaleCode"];
            type: string;
            value?: string;
            values?: {
                [key: string]: string;
            };
        };
        RoleLocalePermissions: {
            unscoped?: components["schemas"]["RoleLocalePermission"][];
        };
        RoleWebdavPermission: {
            folder: string;
            type: string;
            value?: string;
            values?: {
                [key: string]: string;
            };
        };
        RoleWebdavPermissions: {
            unscoped?: components["schemas"]["RoleWebdavPermission"][];
        };
        RolePermissions: {
            module?: components["schemas"]["RoleModulePermissions"];
            functional?: components["schemas"]["RoleFunctionalPermissions"];
            locale?: components["schemas"]["RoleLocalePermissions"];
            webdav?: components["schemas"]["RoleWebdavPermissions"];
        };
        User: {
            login: string;
            password?: string;
            email: string;
            firstName?: string;
            lastName?: string;
            externalId?: string;
            disabled?: boolean;
            locked?: boolean;
            /** Format: date */
            lastLoginDate?: string;
            /** Format: date-time */
            passwordExpirationDate?: string;
            /** Format: date-time */
            passwordModificationDate?: string;
            preferredDataLocale?: components["schemas"]["LocaleCode"];
            preferredUiLocale?: components["schemas"]["LocaleCode"];
            roles?: string[];
        };
        Role: {
            id?: string;
            description?: string;
            /** Format: int32 */
            userCount?: number;
            userManager?: boolean;
            permissions?: components["schemas"]["RolePermissions"];
            users?: components["schemas"]["User"][];
        };
        RoleSearch: {
            data: components["schemas"]["Role"][];
        } & components["schemas"]["PaginatedResultBase"];
        ErrorResponse: {
            title: string;
            type: string;
            detail: string;
            instance?: string;
        } & {
            [key: string]: unknown;
        };
        Query: {
            boolQuery?: components["schemas"]["BoolQuery"];
            filteredQuery?: components["schemas"]["FilteredQuery"];
            matchAllQuery?: components["schemas"]["MatchAllQuery"];
            nestedQuery?: components["schemas"]["NestedQuery"];
            termQuery?: components["schemas"]["TermQuery"];
            textQuery?: components["schemas"]["TextQuery"];
        };
        BoolQuery: {
            must?: components["schemas"]["Query"][];
            mustNot?: components["schemas"]["Query"][];
            should?: components["schemas"]["Query"][];
        };
        Filter: {
            boolFilter?: components["schemas"]["BoolFilter"];
            queryFilter?: components["schemas"]["QueryFilter"];
            range2Filter?: components["schemas"]["Range2Filter"];
            rangeFilter?: components["schemas"]["RangeFilter"];
            termFilter?: components["schemas"]["TermFilter"];
        };
        BoolFilter: {
            filters?: components["schemas"]["Filter"][];
            /** @enum {string} */
            operator: "and" | "or" | "not";
        };
        QueryFilter: {
            query: components["schemas"]["Query"];
        };
        Field: string;
        Range2Filter: {
            /**
             * @default overlap
             * @enum {string}
             */
            filterMode: "overlap" | "containing" | "contained";
            fromField: components["schemas"]["Field"];
            /** @default true */
            fromInclusive: boolean;
            fromValue?: unknown;
            toField: components["schemas"]["Field"];
            /** @default true */
            toInclusive: boolean;
            toValue?: unknown;
        };
        RangeFilter: {
            field: components["schemas"]["Field"];
            from?: string | number;
            /** @default true */
            fromInclusive: boolean;
            to?: string | number;
            /** @default true */
            toInclusive: boolean;
        };
        TermFilter: {
            field: components["schemas"]["Field"];
            /** @enum {string} */
            operator: "is" | "one_of" | "is_null" | "is_not_null" | "less" | "greater" | "not_in" | "neq";
            values?: string[];
        };
        FilteredQuery: {
            filter: components["schemas"]["Filter"];
            query: components["schemas"]["Query"];
        };
        MatchAllQuery: Record<string, never>;
        NestedQuery: {
            path: string;
            query: components["schemas"]["Query"];
            /** @enum {string} */
            scoreMode?: "avg" | "total" | "max" | "none";
        };
        TermQuery: {
            fields: components["schemas"]["Field"][];
            /** @enum {string} */
            operator: "is" | "one_of" | "is_null" | "is_not_null" | "less" | "greater" | "not_in" | "neq";
            values?: (string | number | boolean)[];
        };
        TextQuery: {
            fields: components["schemas"]["Field"][];
            searchPhrase: string;
        };
        Sort: {
            field: string;
            /**
             * @default asc
             * @enum {string}
             */
            sortOrder: "asc" | "desc";
        };
        SearchRequest: {
            /** Format: int32 */
            limit?: number;
            query: components["schemas"]["Query"];
            sorts?: components["schemas"]["Sort"][];
            offset?: components["schemas"]["Offset"];
        };
        RoleUserSearchRequest: components["schemas"]["SearchRequest"];
        PaginatedSearchResult: {
            query: components["schemas"]["Query"];
            sorts?: components["schemas"]["Sort"][];
            hits?: Record<string, never>[];
        } & components["schemas"]["PaginatedResultBase"];
        RoleUserSearchResult: {
            hits: components["schemas"]["User"][];
        } & WithRequired<components["schemas"]["PaginatedSearchResult"], "hits" | "query">;
        UserSearch: {
            data: components["schemas"]["User"][];
        } & components["schemas"]["PaginatedResultBase"];
    };
    responses: never;
    parameters: {
        organizationId: components["schemas"]["OrganizationId"];
        expand: ("users" | "permissions")[];
        select: components["schemas"]["Select"];
        roleId: string;
        login: string;
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    getRoles: {
        parameters: {
            query?: {
                expand?: ("users" | "permissions")[];
                select?: components["schemas"]["Select"];
                limit?: number;
                offset?: number;
            };
            header?: never;
            path: {
                organizationId: components["schemas"]["OrganizationId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Returns the collection of access roles */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RoleSearch"];
                };
            };
        };
    };
    getRole: {
        parameters: {
            query?: {
                expand?: ("users" | "permissions")[];
            };
            header?: never;
            path: {
                organizationId: components["schemas"]["OrganizationId"];
                roleId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Returns the access role details */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Role"];
                };
            };
            /** @description Role not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    createRole: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                organizationId: components["schemas"]["OrganizationId"];
                roleId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Role"];
            };
        };
        responses: {
            /** @description The access role was successfully updated */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Role"];
                };
            };
            /** @description The access role was successfully created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Role"];
                };
            };
            /** @description Bad Request - Invalid role request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    deleteRole: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                organizationId: components["schemas"]["OrganizationId"];
                roleId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The access role was successfully deleted */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Role not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    getRolePermissions: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                organizationId: components["schemas"]["OrganizationId"];
                roleId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Returns the role permissions */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RolePermissions"];
                };
            };
            /** @description Role not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    setRolePermissions: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                organizationId: components["schemas"]["OrganizationId"];
                roleId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RolePermissions"];
            };
        };
        responses: {
            /** @description The permissions were successfully updated */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RolePermissions"];
                };
            };
            /** @description The permissions were successfully assigned */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RolePermissions"];
                };
            };
            /** @description Bad Request - Invalid permissions request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Role not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    searchRoleUsers: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                organizationId: components["schemas"]["OrganizationId"];
                roleId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RoleUserSearchRequest"];
            };
        };
        responses: {
            /** @description Returns role user search results */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RoleUserSearchResult"];
                };
            };
            /** @description Bad Request - Malformed search query or invalid parameters */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Role not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    getRoleUsers: {
        parameters: {
            query?: {
                select?: components["schemas"]["Select"];
                limit?: number;
                offset?: number;
            };
            header?: never;
            path: {
                organizationId: components["schemas"]["OrganizationId"];
                roleId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Returns the collection of users assigned to the role */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserSearch"];
                };
            };
            /** @description Role not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    assignUserToRole: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                organizationId: components["schemas"]["OrganizationId"];
                roleId: string;
                login: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The user was successfully re-assigned to the role */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["User"];
                };
            };
            /** @description The user was successfully assigned to the role */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["User"];
                };
            };
            /** @description Role or user not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    unassignUserFromRole: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                organizationId: components["schemas"]["OrganizationId"];
                roleId: string;
                login: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The user was successfully unassigned from the role */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Role or user not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
}
type WithRequired<T, K extends keyof T> = T & {
    [P in K]-?: T[P];
};
