/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/oauth2/authorize": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query: {
                    client_id: string;
                    response_type: "code";
                    redirect_uri: string;
                    hint: "guest";
                    code_challenge: string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                303: components["responses"]["AuthorizationRedirect"];
                default: components["responses"]["Error"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/oauth2/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/x-www-form-urlencoded": {
                        client_id: string;
                        channel_id: string;
                        code_challenge: string;
                        redirect_uri: string;
                    };
                };
            };
            responses: {
                303: components["responses"]["AuthorizationRedirect"];
                default: components["responses"]["Error"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/oauth2/token": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/x-www-form-urlencoded": {
                        /** @enum {string} */
                        grant_type: "client_credentials" | "authorization_code_pkce";
                        channel_id: string;
                        client_id?: string;
                        code?: string;
                        code_verifier?: string;
                        redirect_uri?: string;
                        usid?: string;
                    };
                };
            };
            responses: {
                /** @description Shopper access token */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            access_token: string;
                            refresh_token: string;
                            expires_in: number;
                            token_type: string;
                            usid: string;
                            customer_id: string;
                            id_token?: string;
                        };
                    };
                };
                default: components["responses"]["Error"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: never;
    responses: {
        /** @description Authorization code returned in the Location header */
        AuthorizationRedirect: {
            headers: {
                Location: string;
                [name: string]: unknown;
            };
            content?: never;
        };
        /** @description SLAS error response */
        Error: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": {
                    [key: string]: unknown;
                };
            };
        };
    };
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
