/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/organizations/{organizationId}/storefronts/{storefrontId}/environments/{environmentId}/environment-variables": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get environment variables for an environment.
         * @description Retrieves the environment variables configured for the specified environment. Values are returned masked (only the last few characters are visible) and cannot be read back in plaintext.
         */
        get: operations["getEnvironmentVariables"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * Update environment variables for an environment.
         * @description Updates the environment variables using merge-PATCH semantics: a key present in the request is created or replaced; a key with a `null` value is deleted; a key omitted from the request is left unchanged. Returns 204 No Content on success.
         */
        patch: operations["updateEnvironmentVariables"];
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        ErrorResponse: {
            title: string;
            type: string;
            detail: string;
            instance?: string;
        } & {
            [key: string]: unknown;
        };
        /**
         * @description The publishing status of an environment variable.
         * @example completed
         * @enum {string}
         */
        PublishingStatus: "pending" | "completed" | "failed";
        /** @description A single environment variable's masked value and metadata. */
        EnvironmentVariableEntry: {
            /**
             * @description The masked value of the environment variable (only the last few characters are visible). Null if no value is set.
             * @example ****cret
             */
            value?: string | null;
            /**
             * @description The email address of the user who created the variable. Null if no user is associated.
             * @example dev@example.com
             */
            createdBy?: string | null;
            /**
             * Format: date-time
             * @description The timestamp when the variable was created.
             * @example 2026-04-08T21:47:28.188965Z
             */
            creationDate?: string;
            /**
             * Format: date-time
             * @description The timestamp when the variable was last modified.
             * @example 2026-04-08T21:47:31.307595Z
             */
            lastModified?: string;
            /**
             * @description The email address of the user who last modified the variable. Null if no user is associated.
             * @example dev@example.com
             */
            lastModifiedBy?: string | null;
            publishingStatus?: components["schemas"]["PublishingStatus"];
        };
        /** @description The environment variables for an environment, keyed by variable name. Each value is an {@link EnvironmentVariableEntry} with a masked value and metadata. */
        EnvironmentVariables: {
            [key: string]: components["schemas"]["EnvironmentVariableEntry"];
        };
        /** @description A single environment variable update. A `null` value deletes the variable; a string or number value creates or replaces it. */
        EnvironmentVariableUpdateEntry: {
            /** @description The new value for the variable, or `null` to delete it. */
            value: (string | number) | null;
        };
        /** @description Merge-PATCH request body, keyed by variable name. Present keys are created/replaced, keys with a `null` value are deleted, and omitted keys are left unchanged. */
        EnvironmentVariablesUpdateRequest: {
            [key: string]: components["schemas"]["EnvironmentVariableUpdateEntry"];
        };
    };
    responses: {
        /** @description Your access token is invalid or expired and can't be used to identify a user. */
        "401Unauthorized": {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["ErrorResponse"];
            };
        };
        /** @description You aren't authorized to perform this action. */
        "403Forbidden": {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["ErrorResponse"];
            };
        };
        /** @description The request was malformed or failed validation. */
        "400BadRequest": {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["ErrorResponse"];
            };
        };
        /** @description The requested resource was not found. */
        "404NotFound": {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["ErrorResponse"];
            };
        };
    };
    parameters: {
        /** @description The B2C Commerce organization identifier, e.g. `f_ecom_zzxy_prd`. */
        organizationId: string;
        /** @description The storefront identifier. Must consist only of lowercase letters, numbers, and hyphens, with no leading or trailing hyphens. */
        storefrontId: string;
        /** @description The environment identifier. Must consist only of lowercase letters, numbers, and hyphens, with no leading or trailing hyphens. */
        environmentId: string;
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    getEnvironmentVariables: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description The B2C Commerce organization identifier, e.g. `f_ecom_zzxy_prd`. */
                organizationId: components["parameters"]["organizationId"];
                /** @description The storefront identifier. Must consist only of lowercase letters, numbers, and hyphens, with no leading or trailing hyphens. */
                storefrontId: components["parameters"]["storefrontId"];
                /** @description The environment identifier. Must consist only of lowercase letters, numbers, and hyphens, with no leading or trailing hyphens. */
                environmentId: components["parameters"]["environmentId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Environment variables successfully retrieved. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EnvironmentVariables"];
                };
            };
            401: components["responses"]["401Unauthorized"];
            403: components["responses"]["403Forbidden"];
            404: components["responses"]["404NotFound"];
        };
    };
    updateEnvironmentVariables: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description The B2C Commerce organization identifier, e.g. `f_ecom_zzxy_prd`. */
                organizationId: components["parameters"]["organizationId"];
                /** @description The storefront identifier. Must consist only of lowercase letters, numbers, and hyphens, with no leading or trailing hyphens. */
                storefrontId: components["parameters"]["storefrontId"];
                /** @description The environment identifier. Must consist only of lowercase letters, numbers, and hyphens, with no leading or trailing hyphens. */
                environmentId: components["parameters"]["environmentId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["EnvironmentVariablesUpdateRequest"];
            };
        };
        responses: {
            /** @description Environment variables successfully updated. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            400: components["responses"]["400BadRequest"];
            401: components["responses"]["401Unauthorized"];
            403: components["responses"]["403Forbidden"];
            404: components["responses"]["404NotFound"];
        };
    };
}
