/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/organizations/{organizationId}/storefronts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get storefronts for an organization.
         * @description Retrieves the list of storefronts provisioned for the organization, ordered by creationDate ascending.
         */
        get: operations["getStorefronts"];
        put?: never;
        /**
         * Create a storefront.
         * @description Queues creation of a new storefront. Returns immediately with the storefront resource in the in_progress setup status. Poll the storefront by ID to track provisioning progress.
         */
        post: operations["createStorefront"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/organizations/{organizationId}/storefronts/{storefrontId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get a storefront by ID.
         * @description Retrieves the details of a specific storefront, including its current setup status and assigned sites.
         */
        get: operations["getStorefrontById"];
        put?: never;
        post?: never;
        /**
         * Delete a storefront.
         * @description Queues deletion of the storefront. Returns immediately with the storefront resource in the delete_in_progress setup status. Poll the storefront by ID to track deletion progress.
         */
        delete: operations["deleteStorefront"];
        options?: never;
        head?: never;
        /**
         * Update a storefront.
         * @description Updates a storefront. Every field is optional and only the supplied fields are changed. When `sites` is provided it replaces the storefront's full set of assigned sites—a complete replacement, not an incremental update—so the request body must contain the complete desired set of site IDs.
         */
        patch: operations["updateStorefront"];
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        ErrorResponse: {
            title: string;
            type: string;
            detail: string;
            instance?: string;
        } & {
            [key: string]: unknown;
        };
        /**
         * @description The identifier of a B2C Commerce site.
         * @example RefArch
         */
        SiteId: string;
        /**
         * @description The type of the storefront. `unknown` is a legacy fallback for existing records with no recorded type; it is never a valid value on create.
         * @example storefront_next
         * @enum {string}
         */
        StorefrontType: "storefront_next" | "pwa_kit" | "headless" | "unknown";
        /**
         * @description The type of storefront to create. Only `storefront_next` is currently supported by the create-new-storefront flow.
         * @example storefront_next
         * @enum {string}
         */
        StorefrontCreateType: "storefront_next";
        /**
         * @description The current provisioning/lifecycle status of the storefront.
         * @example success
         * @enum {string}
         */
        StorefrontSetupStatus: "in_progress" | "success" | "backfilled" | "failed" | "delete_in_progress" | "delete_failed" | "deleted" | "unknown";
        /**
         * @description The default AWS region for server-side rendering functions of environments newly created under this storefront. Each value corresponds to the AWS region of the same name with underscores substituted for hyphens (for example, `us_east_2` is the AWS region `us-east-2`).
         * @example us_east_2
         * @enum {string}
         */
        SsrRegion: "us_east_1" | "us_east_2" | "us_west_1" | "us_west_2" | "ap_south_1" | "ap_south_2" | "ap_northeast_2" | "ap_southeast_1" | "ap_southeast_2" | "ap_southeast_3" | "ap_northeast_1" | "ap_northeast_3" | "ca_central_1" | "eu_central_1" | "eu_central_2" | "eu_west_1" | "eu_west_2" | "eu_west_3" | "eu_north_1" | "eu_south_1" | "sa_east_1";
        /** @description A storefront represents a provisioned Storefront Next or PWA Kit Composable storefront, its type, and the sites assigned to it. */
        Storefront: {
            /**
             * @description A storefront identifier that B2C Commerce generates based on the provided storefront name. The storefront ID is unique within the organization. It consists only of lowercase letters, numbers, and hyphens, with no leading or trailing hyphens.
             * @example my-storefront-a1b2c3
             */
            storefrontId: string;
            /**
             * @description The storefront name that you specify when creating a storefront. Must be 64 characters or fewer.
             * @example my-storefront
             */
            storefrontName: string;
            type: components["schemas"]["StorefrontType"];
            setupStatus: components["schemas"]["StorefrontSetupStatus"];
            /**
             * @description The IDs of the existing sites assigned to this storefront. By default a site can be assigned to only one storefront. Storefronts of type `pwa_kit` are exempt from this restriction and may share a site with another storefront.
             * @example [
             *       "RefArch"
             *     ]
             */
            sites?: components["schemas"]["SiteId"][];
            /**
             * Format: date-time
             * @description The timestamp when the storefront was created.
             * @example 2026-04-08T21:47:28.188965Z
             */
            creationDate?: string;
            /**
             * Format: date-time
             * @description The timestamp when the storefront was last modified.
             * @example 2026-04-08T21:47:31.307595Z
             */
            lastModified?: string;
            ssrRegion?: components["schemas"]["SsrRegion"];
            /**
             * @description The default architecture for the server-side rendering function of environments newly created under this storefront. Null when no architecture default is configured.
             * @example arm64
             * @enum {string|null}
             */
            ssrArchitecture?: "x86" | "arm64" | null;
            /**
             * @description Whether cookies are allowed for the storefront. Always enabled for Storefront Next storefronts.
             * @example true
             */
            allowCookies?: boolean;
            /**
             * @description Whether the end-user's User-Agent header is preserved on requests forwarded through the storefront's configured proxies.
             * @example false
             */
            preserveProxyUserAgent?: boolean;
        };
        /** @description Paginated result containing a list of storefronts. */
        StorefrontResult: {
            /**
             * Format: int32
             * @description Maximum number of records returned per request.
             * @example 25
             */
            limit: number;
            /**
             * Format: int32
             * @description Zero-based index of the first record included in the result.
             * @example 0
             */
            offset: number;
            /**
             * Format: int32
             * @description Total number of storefronts matching the request.
             * @example 2
             */
            total: number;
            /** @description The list of storefronts. May be empty. */
            data: components["schemas"]["Storefront"][];
        };
        /** @description Request body for creating a storefront. */
        StorefrontCreateRequest: {
            /**
             * @description The name to assign to the new storefront. Must be unique within the organization.
             * @example my-storefront
             */
            storefrontName: string;
            type: components["schemas"]["StorefrontCreateType"];
            /**
             * @description The IDs of existing sites to assign to the storefront. At least one site is required.
             * @example [
             *       "RefArch"
             *     ]
             */
            sites: components["schemas"]["SiteId"][];
        };
        /** @description Request body for updating a storefront. Every field is optional and only the supplied fields are changed. When `sites` is provided it is a complete replacement of the storefront's site assignment, not an incremental update—supply the full set of site IDs. */
        StorefrontUpdateRequest: {
            /**
             * @description The complete set of site IDs assigned to the storefront, replacing any previous assignment. When provided, at least one site is required.
             * @example [
             *       "RefArch"
             *     ]
             */
            sites?: components["schemas"]["SiteId"][];
            ssrRegion?: components["schemas"]["SsrRegion"];
            /**
             * @description The default architecture for the server-side rendering function of environments newly created under this storefront. Set to null to clear the architecture default.
             * @example arm64
             * @enum {string|null}
             */
            ssrArchitecture?: "x86" | "arm64" | null;
            /**
             * @description Whether cookies are allowed for the storefront. Cannot be modified for Storefront Next storefronts, where cookies are always enabled.
             * @example true
             */
            allowCookies?: boolean;
            /**
             * @description Whether the end-user's User-Agent header is preserved on requests forwarded through the storefront's configured proxies.
             * @example false
             */
            preserveProxyUserAgent?: boolean;
        };
    };
    responses: {
        /** @description Your access token is invalid or expired and can't be used to identify a user. */
        "401Unauthorized": {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["ErrorResponse"];
            };
        };
        /** @description You aren't authorized to perform this action. */
        "403Forbidden": {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["ErrorResponse"];
            };
        };
        /** @description The request was malformed or failed validation. */
        "400BadRequest": {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["ErrorResponse"];
            };
        };
        /** @description The requested resource was not found. */
        "404NotFound": {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["ErrorResponse"];
            };
        };
        /** @description The request conflicts with the current state of the storefront. */
        "409Conflict": {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["ErrorResponse"];
            };
        };
    };
    parameters: {
        /** @description The B2C Commerce organization identifier, e.g. `f_ecom_zzxy_prd`. */
        organizationId: string;
        /** @description The storefront identifier. Must consist only of lowercase letters, numbers, and hyphens, with no leading or trailing hyphens. */
        storefrontId: string;
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    getStorefronts: {
        parameters: {
            query?: {
                /** @description Number of records to retrieve per request. Must be between 1 and 200. Defaults to 25. */
                limit?: number;
                /** @description Zero-based index of the first record to include in the result. */
                offset?: number;
            };
            header?: never;
            path: {
                /** @description The B2C Commerce organization identifier, e.g. `f_ecom_zzxy_prd`. */
                organizationId: components["parameters"]["organizationId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description List of storefronts successfully retrieved. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StorefrontResult"];
                };
            };
            401: components["responses"]["401Unauthorized"];
            403: components["responses"]["403Forbidden"];
        };
    };
    createStorefront: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description The B2C Commerce organization identifier, e.g. `f_ecom_zzxy_prd`. */
                organizationId: components["parameters"]["organizationId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["StorefrontCreateRequest"];
            };
        };
        responses: {
            /** @description Storefront creation successfully queued. */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Storefront"];
                };
            };
            400: components["responses"]["400BadRequest"];
            401: components["responses"]["401Unauthorized"];
            403: components["responses"]["403Forbidden"];
            409: components["responses"]["409Conflict"];
        };
    };
    getStorefrontById: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description The B2C Commerce organization identifier, e.g. `f_ecom_zzxy_prd`. */
                organizationId: components["parameters"]["organizationId"];
                /** @description The storefront identifier. Must consist only of lowercase letters, numbers, and hyphens, with no leading or trailing hyphens. */
                storefrontId: components["parameters"]["storefrontId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Storefront successfully retrieved. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Storefront"];
                };
            };
            401: components["responses"]["401Unauthorized"];
            403: components["responses"]["403Forbidden"];
            404: components["responses"]["404NotFound"];
        };
    };
    deleteStorefront: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description The B2C Commerce organization identifier, e.g. `f_ecom_zzxy_prd`. */
                organizationId: components["parameters"]["organizationId"];
                /** @description The storefront identifier. Must consist only of lowercase letters, numbers, and hyphens, with no leading or trailing hyphens. */
                storefrontId: components["parameters"]["storefrontId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Storefront deletion successfully queued. */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Storefront"];
                };
            };
            401: components["responses"]["401Unauthorized"];
            403: components["responses"]["403Forbidden"];
            404: components["responses"]["404NotFound"];
            409: components["responses"]["409Conflict"];
        };
    };
    updateStorefront: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description The B2C Commerce organization identifier, e.g. `f_ecom_zzxy_prd`. */
                organizationId: components["parameters"]["organizationId"];
                /** @description The storefront identifier. Must consist only of lowercase letters, numbers, and hyphens, with no leading or trailing hyphens. */
                storefrontId: components["parameters"]["storefrontId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["StorefrontUpdateRequest"];
            };
        };
        responses: {
            /** @description Storefront successfully updated. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Storefront"];
                };
            };
            400: components["responses"]["400BadRequest"];
            401: components["responses"]["401Unauthorized"];
            403: components["responses"]["403Forbidden"];
            404: components["responses"]["404NotFound"];
            409: components["responses"]["409Conflict"];
        };
    };
}
