/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/organizations/{organizationId}/storefronts/{storefrontId}/environments/{environmentId}/environment-variables": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get environment variables for an environment.
         * @description Retrieves the environment variables configured for the specified environment. Values are returned masked (only the last few characters are visible) and cannot be read back in plaintext.
         */
        get: operations["getEnvironmentVariables"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * Update environment variables for an environment.
         * @description Updates the environment variables using merge-PATCH semantics: a key present in the request is created or replaced; a key with a `null` value is deleted; a key omitted from the request is left unchanged. Returns 204 No Content on success.
         */
        patch: operations["updateEnvironmentVariables"];
        trace?: never;
    };
    "/organizations/{organizationId}/storefronts/{storefrontId}/environments/{environmentId}/access-control-headers": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get access control headers.
         * @description Retrieves a paginated list of access control headers on the environment. Header values are returned masked and cannot be read back in plaintext.
         */
        get: operations["getAccessControlHeaders"];
        put?: never;
        /**
         * Create an access control header.
         * @description Creates a header-based access control rule on the environment. The created value is returned masked in the response.
         */
        post: operations["createAccessControlHeader"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/organizations/{organizationId}/storefronts/{storefrontId}/environments/{environmentId}/access-control-headers/{accessControlHeaderId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get an access control header by ID.
         * @description Retrieves a single access control header by its identifier. The value is returned masked.
         */
        get: operations["getAccessControlHeader"];
        put?: never;
        post?: never;
        /**
         * Delete an access control header.
         * @description Deletes an access control header by its identifier. Returns 204 No Content on success.
         */
        delete: operations["deleteAccessControlHeader"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/organizations/{organizationId}/storefronts/{storefrontId}/environments/{environmentId}/redirects": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get redirects.
         * @description Retrieves a paginated, orderable list of redirects on the environment.
         */
        get: operations["getRedirects"];
        put?: never;
        /**
         * Create a redirect.
         * @description Creates a redirect on the environment. Returns the created redirect.
         */
        post: operations["createRedirect"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/organizations/{organizationId}/storefronts/{storefrontId}/environments/{environmentId}/redirects/{redirectId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get a redirect by ID.
         * @description Retrieves a single redirect by its identifier.
         */
        get: operations["getRedirect"];
        put?: never;
        post?: never;
        /**
         * Delete a redirect.
         * @description Deletes a redirect by its identifier. Returns 204 No Content on success.
         */
        delete: operations["deleteRedirect"];
        options?: never;
        head?: never;
        /**
         * Update a redirect.
         * @description Partially updates a redirect by its identifier. Only the supplied fields are changed.
         */
        patch: operations["updateRedirect"];
        trace?: never;
    };
    "/organizations/{organizationId}/storefronts/{storefrontId}/environments/{environmentId}/redirects/actions/clone": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Clone redirects from a source environment.
         * @description Copies all redirects from a source environment into the environment in the request path. The source environment must differ from the destination environment. Returns 201 Created with no response body.
         */
        post: operations["cloneRedirects"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        ErrorResponse: {
            title: string;
            type: string;
            detail: string;
            instance?: string;
        } & {
            [key: string]: unknown;
        };
        /**
         * @description The publishing status of an environment variable.
         * @example completed
         * @enum {string}
         */
        PublishingStatus: "pending" | "completed" | "failed";
        /** @description A single environment variable's masked value and metadata. */
        EnvironmentVariableEntry: {
            /**
             * @description The masked value of the environment variable (only the last few characters are visible). Null if no value is set.
             * @example ****cret
             */
            value?: string | null;
            /**
             * @description The email address of the user who created the variable. Null if no user is associated.
             * @example dev@example.com
             */
            createdBy?: string | null;
            /**
             * Format: date-time
             * @description The timestamp when the variable was created.
             * @example 2026-04-08T21:47:28.188965Z
             */
            creationDate?: string;
            /**
             * Format: date-time
             * @description The timestamp when the variable was last modified.
             * @example 2026-04-08T21:47:31.307595Z
             */
            lastModified?: string;
            /**
             * @description The email address of the user who last modified the variable. Null if no user is associated.
             * @example dev@example.com
             */
            lastModifiedBy?: string | null;
            publishingStatus?: components["schemas"]["PublishingStatus"];
        };
        /** @description The environment variables for an environment, keyed by variable name. Each value is an {@link EnvironmentVariableEntry} with a masked value and metadata. */
        EnvironmentVariables: {
            [key: string]: components["schemas"]["EnvironmentVariableEntry"];
        };
        /** @description A single environment variable update. A `null` value deletes the variable; a string or number value creates or replaces it. */
        EnvironmentVariableUpdateEntry: {
            /** @description The new value for the variable, or `null` to delete it. */
            value: (string | number) | null;
        };
        /** @description Merge-PATCH request body, keyed by variable name. Present keys are created/replaced, keys with a `null` value are deleted, and omitted keys are left unchanged. */
        EnvironmentVariablesUpdateRequest: {
            [key: string]: components["schemas"]["EnvironmentVariableUpdateEntry"];
        };
        /** @description A header-based access control rule on the environment. */
        AccessControlHeader: {
            /**
             * Format: uuid
             * @description The unique identifier of the access control header, in UUID format.
             * @example ff832a9e-0e55-11ef-8f23-0242ac110002
             */
            id?: string;
            /**
             * @description The masked header value. Actual values are never returned in clear text.
             * @example ****************by0z
             */
            value?: string;
            /**
             * @description The email address of the user who created the header. Null if no user is associated.
             * @example dev@example.com
             */
            createdBy?: string | null;
            /**
             * Format: date-time
             * @description The timestamp when the header was created.
             * @example 2026-08-24T09:23:28.872916Z
             */
            creationDate?: string;
            publishingStatus?: components["schemas"]["PublishingStatus"];
        };
        /** @description Paginated result containing a list of access control headers. */
        AccessControlHeaderResult: {
            /**
             * Format: int32
             * @description Maximum number of records returned per request.
             * @example 25
             */
            limit: number;
            /**
             * Format: int32
             * @description Zero-based index of the first record included in the result.
             * @example 0
             */
            offset: number;
            /**
             * Format: int32
             * @description Total number of access control headers matching the request.
             * @example 3
             */
            total: number;
            /** @description The list of access control headers. May be empty. */
            data: components["schemas"]["AccessControlHeader"][];
        };
        /** @description Request body to create an access control header. */
        AccessControlHeaderCreateRequest: {
            /**
             * @description The header value.
             * @example jfoWikeaby0z
             */
            value: string;
        };
        /**
         * Format: int32
         * @description The HTTP status code returned for the redirect.
         * @default 301
         * @example 301
         * @enum {integer}
         */
        RedirectHttpStatusCode: 301 | 302;
        /** @description A URL redirect rule on the environment. */
        Redirect: {
            /**
             * Format: uuid
             * @description The unique identifier of the redirect, in UUID format.
             * @example 3f9b1c2d-4e5f-6a7b-8c9d-0e1f2a3b4c5d
             */
            redirectId?: string;
            /**
             * @description The source path that triggers the redirect.
             * @example /spring
             */
            source?: string;
            /**
             * @description The destination path or URL the request is redirected to.
             * @example /summer-newbranding
             */
            destination?: string;
            httpStatusCode?: components["schemas"]["RedirectHttpStatusCode"];
            /**
             * @description Whether the incoming query string is forwarded to the destination.
             * @example false
             */
            forwardQuerystring?: boolean;
            /**
             * @description Whether a trailing wildcard match on the source is forwarded to the destination.
             * @example false
             */
            forwardWildcard?: boolean;
            publishingStatus?: components["schemas"]["PublishingStatus"];
            /**
             * @description The email address of the user who created the redirect. Null if no user is associated.
             * @example dev@example.com
             */
            createdBy?: string | null;
            /**
             * @description The email address of the user who last modified the redirect. Null if no user is associated.
             * @example dev@example.com
             */
            lastModifiedBy?: string | null;
            /**
             * Format: date-time
             * @description The timestamp when the redirect was created.
             * @example 2026-08-24T00:00:00.000Z
             */
            creationDate?: string;
            /**
             * Format: date-time
             * @description The timestamp when the redirect was last modified.
             * @example 2026-08-24T00:00:00.000Z
             */
            lastModified?: string;
        };
        /** @description Paginated result containing a list of redirects. */
        RedirectResult: {
            /**
             * Format: int32
             * @description Maximum number of records returned per request.
             * @example 25
             */
            limit: number;
            /**
             * Format: int32
             * @description Zero-based index of the first record included in the result.
             * @example 0
             */
            offset: number;
            /**
             * Format: int32
             * @description Total number of redirects matching the request.
             * @example 3
             */
            total: number;
            /** @description The list of redirects. May be empty. */
            data: components["schemas"]["Redirect"][];
        };
        /** @description Request body to create a single redirect. */
        RedirectCreateRequest: {
            /**
             * @description The source path that triggers the redirect.
             * @example /spring
             */
            source: string;
            /**
             * @description The destination path or URL the request is redirected to.
             * @example /summer-newbranding
             */
            destination: string;
            httpStatusCode?: components["schemas"]["RedirectHttpStatusCode"];
            /**
             * @description Whether the incoming query string is forwarded to the destination.
             * @default false
             * @example false
             */
            forwardQuerystring: boolean;
            /**
             * @description Whether a trailing wildcard match on the source is forwarded to the destination.
             * @default false
             * @example false
             */
            forwardWildcard: boolean;
        };
        /** @description Request body to partially update a redirect. Only the supplied fields are changed. */
        RedirectUpdateRequest: {
            /**
             * @description The source path that triggers the redirect.
             * @example /spring
             */
            source?: string;
            /**
             * @description The destination path or URL the request is redirected to.
             * @example /summer-2027
             */
            destination?: string;
            httpStatusCode?: components["schemas"]["RedirectHttpStatusCode"];
            /**
             * @description Whether the incoming query string is forwarded to the destination.
             * @example false
             */
            forwardQuerystring?: boolean;
            /**
             * @description Whether a trailing wildcard match on the source is forwarded to the destination.
             * @example false
             */
            forwardWildcard?: boolean;
        };
        /** @description Request body to clone all redirects from a source environment into this environment. */
        RedirectCloneRequest: {
            /**
             * @description The identifier of the environment to copy redirects from. Must differ from the environment in the request path.
             * @example staging
             */
            sourceEnvironmentId: string;
        };
    };
    responses: {
        /** @description Your access token is invalid or expired and can't be used to identify a user. */
        "401Unauthorized": {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["ErrorResponse"];
            };
        };
        /** @description You aren't authorized to perform this action. */
        "403Forbidden": {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["ErrorResponse"];
            };
        };
        /** @description The request was malformed or failed validation. */
        "400BadRequest": {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["ErrorResponse"];
            };
        };
        /** @description The requested resource was not found. */
        "404NotFound": {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["ErrorResponse"];
            };
        };
    };
    parameters: {
        /** @description The B2C Commerce organization identifier, e.g. `f_ecom_zzxy_prd`. */
        organizationId: string;
        /** @description The storefront identifier. Must consist only of lowercase letters, numbers, and hyphens, with no leading or trailing hyphens. */
        storefrontId: string;
        /** @description The environment identifier. Must consist only of lowercase letters, numbers, and hyphens, with no leading or trailing hyphens. */
        environmentId: string;
        /** @description The access control header identifier, in UUID format. */
        accessControlHeaderId: string;
        /** @description Attributes to order the returned access control headers by, in priority order (applied left to right). Append `:asc` or `:desc` to set the direction; when omitted, `:asc` is assumed. Sortable attributes: `creation_date`, `id`, `publishing_status`. */
        accessControlHeaderOrderBy: string[];
        /** @description The redirect identifier, in UUID format. */
        redirectId: string;
        /** @description Attributes to order the returned redirects by, in priority order (applied left to right). Append `:asc` or `:desc` to set the direction; when omitted, `:asc` is assumed. Sortable attributes: `creation_date`, `last_modified`, `source`, `destination`, `last_modified_by`, `http_status_code`, `publishing_status`. */
        redirectOrderBy: string[];
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    getEnvironmentVariables: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description The B2C Commerce organization identifier, e.g. `f_ecom_zzxy_prd`. */
                organizationId: components["parameters"]["organizationId"];
                /** @description The storefront identifier. Must consist only of lowercase letters, numbers, and hyphens, with no leading or trailing hyphens. */
                storefrontId: components["parameters"]["storefrontId"];
                /** @description The environment identifier. Must consist only of lowercase letters, numbers, and hyphens, with no leading or trailing hyphens. */
                environmentId: components["parameters"]["environmentId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Environment variables successfully retrieved. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EnvironmentVariables"];
                };
            };
            401: components["responses"]["401Unauthorized"];
            403: components["responses"]["403Forbidden"];
            404: components["responses"]["404NotFound"];
        };
    };
    updateEnvironmentVariables: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description The B2C Commerce organization identifier, e.g. `f_ecom_zzxy_prd`. */
                organizationId: components["parameters"]["organizationId"];
                /** @description The storefront identifier. Must consist only of lowercase letters, numbers, and hyphens, with no leading or trailing hyphens. */
                storefrontId: components["parameters"]["storefrontId"];
                /** @description The environment identifier. Must consist only of lowercase letters, numbers, and hyphens, with no leading or trailing hyphens. */
                environmentId: components["parameters"]["environmentId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["EnvironmentVariablesUpdateRequest"];
            };
        };
        responses: {
            /** @description Environment variables successfully updated. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            400: components["responses"]["400BadRequest"];
            401: components["responses"]["401Unauthorized"];
            403: components["responses"]["403Forbidden"];
            404: components["responses"]["404NotFound"];
        };
    };
    getAccessControlHeaders: {
        parameters: {
            query?: {
                /** @description Attributes to order the returned access control headers by, in priority order (applied left to right). Append `:asc` or `:desc` to set the direction; when omitted, `:asc` is assumed. Sortable attributes: `creation_date`, `id`, `publishing_status`. */
                orderBy?: components["parameters"]["accessControlHeaderOrderBy"];
                /** @description Number of records to retrieve per request. Must be between 1 and 200. Defaults to 25. */
                limit?: number;
                /** @description Zero-based index of the first record to include in the result. */
                offset?: number;
            };
            header?: never;
            path: {
                /** @description The B2C Commerce organization identifier, e.g. `f_ecom_zzxy_prd`. */
                organizationId: components["parameters"]["organizationId"];
                /** @description The storefront identifier. Must consist only of lowercase letters, numbers, and hyphens, with no leading or trailing hyphens. */
                storefrontId: components["parameters"]["storefrontId"];
                /** @description The environment identifier. Must consist only of lowercase letters, numbers, and hyphens, with no leading or trailing hyphens. */
                environmentId: components["parameters"]["environmentId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description List of access control headers successfully retrieved. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AccessControlHeaderResult"];
                };
            };
            401: components["responses"]["401Unauthorized"];
            403: components["responses"]["403Forbidden"];
            404: components["responses"]["404NotFound"];
        };
    };
    createAccessControlHeader: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description The B2C Commerce organization identifier, e.g. `f_ecom_zzxy_prd`. */
                organizationId: components["parameters"]["organizationId"];
                /** @description The storefront identifier. Must consist only of lowercase letters, numbers, and hyphens, with no leading or trailing hyphens. */
                storefrontId: components["parameters"]["storefrontId"];
                /** @description The environment identifier. Must consist only of lowercase letters, numbers, and hyphens, with no leading or trailing hyphens. */
                environmentId: components["parameters"]["environmentId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AccessControlHeaderCreateRequest"];
            };
        };
        responses: {
            /** @description Access control header successfully created. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AccessControlHeader"];
                };
            };
            400: components["responses"]["400BadRequest"];
            401: components["responses"]["401Unauthorized"];
            403: components["responses"]["403Forbidden"];
            404: components["responses"]["404NotFound"];
        };
    };
    getAccessControlHeader: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description The B2C Commerce organization identifier, e.g. `f_ecom_zzxy_prd`. */
                organizationId: components["parameters"]["organizationId"];
                /** @description The storefront identifier. Must consist only of lowercase letters, numbers, and hyphens, with no leading or trailing hyphens. */
                storefrontId: components["parameters"]["storefrontId"];
                /** @description The environment identifier. Must consist only of lowercase letters, numbers, and hyphens, with no leading or trailing hyphens. */
                environmentId: components["parameters"]["environmentId"];
                /** @description The access control header identifier, in UUID format. */
                accessControlHeaderId: components["parameters"]["accessControlHeaderId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Access control header successfully retrieved. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AccessControlHeader"];
                };
            };
            401: components["responses"]["401Unauthorized"];
            403: components["responses"]["403Forbidden"];
            404: components["responses"]["404NotFound"];
        };
    };
    deleteAccessControlHeader: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description The B2C Commerce organization identifier, e.g. `f_ecom_zzxy_prd`. */
                organizationId: components["parameters"]["organizationId"];
                /** @description The storefront identifier. Must consist only of lowercase letters, numbers, and hyphens, with no leading or trailing hyphens. */
                storefrontId: components["parameters"]["storefrontId"];
                /** @description The environment identifier. Must consist only of lowercase letters, numbers, and hyphens, with no leading or trailing hyphens. */
                environmentId: components["parameters"]["environmentId"];
                /** @description The access control header identifier, in UUID format. */
                accessControlHeaderId: components["parameters"]["accessControlHeaderId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Access control header successfully deleted. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["401Unauthorized"];
            403: components["responses"]["403Forbidden"];
            404: components["responses"]["404NotFound"];
        };
    };
    getRedirects: {
        parameters: {
            query?: {
                /** @description Attributes to order the returned redirects by, in priority order (applied left to right). Append `:asc` or `:desc` to set the direction; when omitted, `:asc` is assumed. Sortable attributes: `creation_date`, `last_modified`, `source`, `destination`, `last_modified_by`, `http_status_code`, `publishing_status`. */
                orderBy?: components["parameters"]["redirectOrderBy"];
                /** @description Number of records to retrieve per request. Must be between 1 and 200. Defaults to 25. */
                limit?: number;
                /** @description Zero-based index of the first record to include in the result. */
                offset?: number;
            };
            header?: never;
            path: {
                /** @description The B2C Commerce organization identifier, e.g. `f_ecom_zzxy_prd`. */
                organizationId: components["parameters"]["organizationId"];
                /** @description The storefront identifier. Must consist only of lowercase letters, numbers, and hyphens, with no leading or trailing hyphens. */
                storefrontId: components["parameters"]["storefrontId"];
                /** @description The environment identifier. Must consist only of lowercase letters, numbers, and hyphens, with no leading or trailing hyphens. */
                environmentId: components["parameters"]["environmentId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description List of redirects successfully retrieved. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RedirectResult"];
                };
            };
            401: components["responses"]["401Unauthorized"];
            403: components["responses"]["403Forbidden"];
            404: components["responses"]["404NotFound"];
        };
    };
    createRedirect: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description The B2C Commerce organization identifier, e.g. `f_ecom_zzxy_prd`. */
                organizationId: components["parameters"]["organizationId"];
                /** @description The storefront identifier. Must consist only of lowercase letters, numbers, and hyphens, with no leading or trailing hyphens. */
                storefrontId: components["parameters"]["storefrontId"];
                /** @description The environment identifier. Must consist only of lowercase letters, numbers, and hyphens, with no leading or trailing hyphens. */
                environmentId: components["parameters"]["environmentId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RedirectCreateRequest"];
            };
        };
        responses: {
            /** @description Redirect successfully created. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Redirect"];
                };
            };
            400: components["responses"]["400BadRequest"];
            401: components["responses"]["401Unauthorized"];
            403: components["responses"]["403Forbidden"];
            404: components["responses"]["404NotFound"];
        };
    };
    getRedirect: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description The B2C Commerce organization identifier, e.g. `f_ecom_zzxy_prd`. */
                organizationId: components["parameters"]["organizationId"];
                /** @description The storefront identifier. Must consist only of lowercase letters, numbers, and hyphens, with no leading or trailing hyphens. */
                storefrontId: components["parameters"]["storefrontId"];
                /** @description The environment identifier. Must consist only of lowercase letters, numbers, and hyphens, with no leading or trailing hyphens. */
                environmentId: components["parameters"]["environmentId"];
                /** @description The redirect identifier, in UUID format. */
                redirectId: components["parameters"]["redirectId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Redirect successfully retrieved. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Redirect"];
                };
            };
            401: components["responses"]["401Unauthorized"];
            403: components["responses"]["403Forbidden"];
            404: components["responses"]["404NotFound"];
        };
    };
    deleteRedirect: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description The B2C Commerce organization identifier, e.g. `f_ecom_zzxy_prd`. */
                organizationId: components["parameters"]["organizationId"];
                /** @description The storefront identifier. Must consist only of lowercase letters, numbers, and hyphens, with no leading or trailing hyphens. */
                storefrontId: components["parameters"]["storefrontId"];
                /** @description The environment identifier. Must consist only of lowercase letters, numbers, and hyphens, with no leading or trailing hyphens. */
                environmentId: components["parameters"]["environmentId"];
                /** @description The redirect identifier, in UUID format. */
                redirectId: components["parameters"]["redirectId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Redirect successfully deleted. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["401Unauthorized"];
            403: components["responses"]["403Forbidden"];
            404: components["responses"]["404NotFound"];
        };
    };
    updateRedirect: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description The B2C Commerce organization identifier, e.g. `f_ecom_zzxy_prd`. */
                organizationId: components["parameters"]["organizationId"];
                /** @description The storefront identifier. Must consist only of lowercase letters, numbers, and hyphens, with no leading or trailing hyphens. */
                storefrontId: components["parameters"]["storefrontId"];
                /** @description The environment identifier. Must consist only of lowercase letters, numbers, and hyphens, with no leading or trailing hyphens. */
                environmentId: components["parameters"]["environmentId"];
                /** @description The redirect identifier, in UUID format. */
                redirectId: components["parameters"]["redirectId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RedirectUpdateRequest"];
            };
        };
        responses: {
            /** @description Redirect successfully updated. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Redirect"];
                };
            };
            400: components["responses"]["400BadRequest"];
            401: components["responses"]["401Unauthorized"];
            403: components["responses"]["403Forbidden"];
            404: components["responses"]["404NotFound"];
        };
    };
    cloneRedirects: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description The B2C Commerce organization identifier, e.g. `f_ecom_zzxy_prd`. */
                organizationId: components["parameters"]["organizationId"];
                /** @description The storefront identifier. Must consist only of lowercase letters, numbers, and hyphens, with no leading or trailing hyphens. */
                storefrontId: components["parameters"]["storefrontId"];
                /** @description The environment identifier. Must consist only of lowercase letters, numbers, and hyphens, with no leading or trailing hyphens. */
                environmentId: components["parameters"]["environmentId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RedirectCloneRequest"];
            };
        };
        responses: {
            /** @description Redirects successfully cloned into the destination environment. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            400: components["responses"]["400BadRequest"];
            401: components["responses"]["401Unauthorized"];
            403: components["responses"]["403Forbidden"];
            404: components["responses"]["404NotFound"];
        };
    };
}
