/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/organizations/{organizationId}/storefronts/{storefrontId}/bundles": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get bundles for a storefront.
         * @description Retrieves a paginated list of bundles uploaded to the specified storefront.
         */
        get: operations["getBundlesForStorefront"];
        put?: never;
        /**
         * Upload a bundle for a storefront.
         * @description Uploads a bundle archive (uncompressed or gzip-compressed .tar file), which must not exceed 400 MB. Bundle configuration is derived from a configuration file inside the archive. Sent as `multipart/form-data`: the archive travels in the `bundle` part, with the remaining request metadata as sibling form fields.
         */
        post: operations["uploadBundleForStorefront"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/organizations/{organizationId}/storefronts/{storefrontId}/environments/{environmentId}/deployments": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get deployments for an environment.
         * @description Retrieves a paginated list of deployments for the specified environment.
         */
        get: operations["getDeploymentsForEnvironment"];
        put?: never;
        /**
         * Create a deployment for an environment.
         * @description Triggers a new deployment of a bundle to the specified environment. Returns immediately with a deployment resource in a queued status. Poll the deployment by ID to track progress.
         */
        post: operations["createDeploymentForEnvironment"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/organizations/{organizationId}/storefronts/{storefrontId}/environments/{environmentId}/deployments/{deploymentId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get a deployment by ID.
         * @description Retrieves the details of a specific deployment, including its current status and progress.
         */
        get: operations["getDeploymentById"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        PaginatedResultBase: {
            /** Format: int32 */
            limit: number;
            /**
             * Format: int32
             * @default 0
             */
            offset: number;
            /**
             * Format: int32
             * @default 0
             */
            total: number;
        };
        ErrorResponse: {
            title: string;
            type: string;
            detail: string;
            instance?: string;
        } & {
            [key: string]: unknown;
        };
        /** @description A versioned build artifact (SSR application package) uploaded to a storefront. */
        Bundle: {
            /**
             * Format: int32
             * @description The unique identifier of the bundle.
             * @example 170
             */
            bundleId?: number;
            /**
             * @description A user-provided message describing the bundle.
             * @example my bundle
             */
            description?: string;
            /**
             * @description The processing status of the bundle.
             * @example ok
             * @enum {string}
             */
            status?: "ok" | "broken" | "preparing";
            /**
             * @description The lifecycle status of the bundle.
             * @example active
             * @enum {string}
             */
            lifecycleStatus?: "active" | "cleanup_requested" | "cleanup_in_progress" | "cleanup_complete" | "cleanup_failed";
            /**
             * @description The email address of the user who uploaded the bundle. Null if no user is associated.
             * @example dev@example.com
             */
            createdBy?: string | null;
            /**
             * Format: date-time
             * @description The timestamp when the bundle was created.
             * @example 2026-04-08T21:47:28.188965Z
             */
            creationDate?: string;
            /**
             * Format: date-time
             * @description The timestamp when the bundle was last modified.
             * @example 2026-04-08T21:47:31.307595Z
             */
            lastModified?: string;
            /**
             * @description The bundle type.
             * @example ssr
             * @enum {string}
             */
            type?: "ssr" | "legacy";
            /** @description SSR configuration parameters for this bundle. Null for non-SSR bundles. */
            ssrParameters?: {
                /**
                 * @description The Node.js runtime version used by this bundle.
                 * @example 24.x
                 */
                runtime?: string;
                /**
                 * @description Human-readable description of the runtime version.
                 * @example NodeJS 24.x
                 */
                runtimeDescription?: string;
                /**
                 * @description The base path for the environment associated with this bundle.
                 * @example ca
                 */
                envBasePath?: string;
            } | null;
            /**
             * @description List of environment identifiers where this bundle is currently deployed.
             * @example [
             *       "production"
             *     ]
             */
            inUseBy?: string[];
            /**
             * @description Whether streaming is enabled for this bundle.
             * @example false
             */
            streamingEnabled?: boolean;
        };
        /** @description Paginated result containing a list of bundles. */
        BundleResult: {
            /** @description List of bundles. */
            data: components["schemas"]["Bundle"][];
        } & components["schemas"]["PaginatedResultBase"];
        /** @description Response returned after a successful bundle upload. */
        BundleUploadResponse: {
            /**
             * Format: int32
             * @description The unique identifier of the uploaded bundle.
             * @example 170
             */
            bundleId?: number;
            /**
             * @description List of warnings generated during bundle processing.
             * @example []
             */
            warnings?: string[];
            /** @description File matching results from bundle analysis. */
            matches?: {
                /**
                 * @description Files matched as SSR-only (server-side only).
                 * @example [
                 *       "ssr.js"
                 *     ]
                 */
                ssrOnly?: string[];
                /**
                 * @description Files matched as SSR-shared (used by both server and client).
                 * @example [
                 *       "shared.js"
                 *     ]
                 */
                ssrShared?: string[];
            };
        };
        /** @description A deployment action that publishes a bundle to an environment. */
        Deployment: {
            /**
             * @description The unique identifier of the deployment, in UUID format.
             * @example b035a4d7-ec6b-4dcd-af8f-3a847b10fed8
             */
            deploymentId?: string;
            /**
             * @description The current status of the deployment.
             * @example finished
             * @enum {string}
             */
            status?: "queued" | "in_progress" | "failed" | "finished";
            /**
             * @description The type of deployment.
             * @example publish
             * @enum {string}
             */
            deploymentType?: "publish" | "reset_bundle" | "push" | "deploy_settings" | "redeploy";
            /**
             * Format: date-time
             * @description The timestamp when the deployment was created.
             * @example 2026-04-08T21:47:31.322339Z
             */
            creationDate?: string;
            /**
             * Format: date-time
             * @description The timestamp when the deployment was last modified.
             * @example 2026-04-08T21:51:55.692688Z
             */
            lastModified?: string;
            /**
             * Format: double
             * @description The duration of the deployment in seconds. Null if the deployment has not finished.
             * @example 76.867967
             */
            duration?: number | null;
            /**
             * @description The email address of the user who triggered the deployment. Null if no user is associated.
             * @example dev@example.com
             */
            createdBy?: string | null;
            /**
             * @description A human-readable message about the deployment's current state.
             * @example Queueing Bundle
             */
            statusMessage?: string;
            /** @description Progress information for the deployment. Null unless an external publish is in progress. */
            progress?: {
                /**
                 * @description A human-readable description of the current deployment stage.
                 * @example Updating CDN
                 */
                description?: string | null;
                /**
                 * Format: int32
                 * @description Percentage of deployment completion.
                 * @example 0
                 */
                percentage?: number | null;
            } | null;
            bundle?: components["schemas"]["Bundle"];
        };
        /** @description Paginated result containing a list of deployments. */
        DeploymentResult: {
            /** @description List of deployments. */
            data: components["schemas"]["Deployment"][];
        } & components["schemas"]["PaginatedResultBase"];
        /** @description Request body to create a new deployment. */
        DeploymentCreateRequest: {
            /**
             * Format: int32
             * @description The identifier of the bundle to deploy.
             * @example 170
             */
            bundleId: number;
        };
        /** @description Request body to upload a bundle, sent as `multipart/form-data`. The archive travels in the `bundle` part, with the remaining request metadata as sibling form fields. */
        BundleUploadRequest: {
            /**
             * Format: binary
             * @description Bundle archive (uncompressed or gzip-compressed .tar file). The uploaded archive must not exceed 400 MB.
             */
            bundle: string;
            /**
             * @description Bundle description (optional metadata).
             * @example Release 2.1.0
             */
            message?: string;
            /**
             * @description Root directory within bundle archive. Files in this directory are used for server-side rendering, published as static assets, or both. Any files in the bundle archive outside of this directory are ignored.
             * @default bld
             * @example bld
             */
            rootDir: string;
            /**
             * @description Path (relative to root directory) of bundle configuration file.
             * @default .mrt/config.json
             * @example .mrt/config.json
             */
            configPath: string;
            /**
             * @description Determines how files in the bundle configuration are matched. If `strict`, all files listed in `ssrOnly` and `ssrShared` fields in the bundle configuration must be present. If `ignore_missing`, missing files in the `ssrOnly` and `ssrShared` fields are ignored.
             * @default strict
             * @example strict
             * @enum {string}
             */
            matchMode: "strict" | "ignore_missing";
        };
    };
    responses: {
        /** @description Your access token is invalid or expired and can't be used to identify a user. */
        "401Unauthorized": {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["ErrorResponse"];
            };
        };
        /** @description You aren't authorized to perform this action. */
        "403Forbidden": {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["ErrorResponse"];
            };
        };
        /** @description The request was malformed or failed validation. */
        "400BadRequest": {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["ErrorResponse"];
            };
        };
        /** @description The requested resource was not found. */
        "404NotFound": {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["ErrorResponse"];
            };
        };
        /** @description The request conflicts with the current state of the resource. */
        "409Conflict": {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["ErrorResponse"];
            };
        };
    };
    parameters: {
        /** @description The B2C Commerce organization identifier, e.g. `f_ecom_zzxy_prd`. */
        organizationId: string;
        /** @description The storefront identifier. Must consist only of lowercase letters, numbers, and hyphens, with no leading or trailing hyphens. */
        storefrontId: string;
        /** @description The environment identifier. Must consist only of lowercase letters, numbers, and hyphens, with no leading or trailing hyphens. */
        environmentId: string;
        /** @description The deployment identifier. */
        deploymentId: string;
        /** @description Maximum number of results to return per page. */
        limit: number;
        /** @description Number of results to skip before returning the page. */
        offset: number;
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    getBundlesForStorefront: {
        parameters: {
            query?: {
                /** @description Maximum number of results to return per page. */
                limit?: components["parameters"]["limit"];
                /** @description Number of results to skip before returning the page. */
                offset?: components["parameters"]["offset"];
            };
            header?: never;
            path: {
                /** @description The B2C Commerce organization identifier, e.g. `f_ecom_zzxy_prd`. */
                organizationId: components["parameters"]["organizationId"];
                /** @description The storefront identifier. Must consist only of lowercase letters, numbers, and hyphens, with no leading or trailing hyphens. */
                storefrontId: components["parameters"]["storefrontId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description List of bundles successfully retrieved. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BundleResult"];
                };
            };
            401: components["responses"]["401Unauthorized"];
            403: components["responses"]["403Forbidden"];
        };
    };
    uploadBundleForStorefront: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description The B2C Commerce organization identifier, e.g. `f_ecom_zzxy_prd`. */
                organizationId: components["parameters"]["organizationId"];
                /** @description The storefront identifier. Must consist only of lowercase letters, numbers, and hyphens, with no leading or trailing hyphens. */
                storefrontId: components["parameters"]["storefrontId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["BundleUploadRequest"];
            };
        };
        responses: {
            /** @description Bundle successfully uploaded. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BundleUploadResponse"];
                };
            };
            400: components["responses"]["400BadRequest"];
            401: components["responses"]["401Unauthorized"];
            403: components["responses"]["403Forbidden"];
        };
    };
    getDeploymentsForEnvironment: {
        parameters: {
            query?: {
                /** @description Maximum number of results to return per page. */
                limit?: components["parameters"]["limit"];
                /** @description Number of results to skip before returning the page. */
                offset?: components["parameters"]["offset"];
            };
            header?: never;
            path: {
                /** @description The B2C Commerce organization identifier, e.g. `f_ecom_zzxy_prd`. */
                organizationId: components["parameters"]["organizationId"];
                /** @description The storefront identifier. Must consist only of lowercase letters, numbers, and hyphens, with no leading or trailing hyphens. */
                storefrontId: components["parameters"]["storefrontId"];
                /** @description The environment identifier. Must consist only of lowercase letters, numbers, and hyphens, with no leading or trailing hyphens. */
                environmentId: components["parameters"]["environmentId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description List of deployments successfully retrieved. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DeploymentResult"];
                };
            };
            401: components["responses"]["401Unauthorized"];
            403: components["responses"]["403Forbidden"];
        };
    };
    createDeploymentForEnvironment: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description The B2C Commerce organization identifier, e.g. `f_ecom_zzxy_prd`. */
                organizationId: components["parameters"]["organizationId"];
                /** @description The storefront identifier. Must consist only of lowercase letters, numbers, and hyphens, with no leading or trailing hyphens. */
                storefrontId: components["parameters"]["storefrontId"];
                /** @description The environment identifier. Must consist only of lowercase letters, numbers, and hyphens, with no leading or trailing hyphens. */
                environmentId: components["parameters"]["environmentId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DeploymentCreateRequest"];
            };
        };
        responses: {
            /** @description Deployment successfully queued. */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Deployment"];
                };
            };
            400: components["responses"]["400BadRequest"];
            401: components["responses"]["401Unauthorized"];
            403: components["responses"]["403Forbidden"];
            404: components["responses"]["404NotFound"];
            409: components["responses"]["409Conflict"];
        };
    };
    getDeploymentById: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description The B2C Commerce organization identifier, e.g. `f_ecom_zzxy_prd`. */
                organizationId: components["parameters"]["organizationId"];
                /** @description The storefront identifier. Must consist only of lowercase letters, numbers, and hyphens, with no leading or trailing hyphens. */
                storefrontId: components["parameters"]["storefrontId"];
                /** @description The environment identifier. Must consist only of lowercase letters, numbers, and hyphens, with no leading or trailing hyphens. */
                environmentId: components["parameters"]["environmentId"];
                /** @description The deployment identifier. */
                deploymentId: components["parameters"]["deploymentId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Deployment successfully retrieved. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Deployment"];
                };
            };
            401: components["responses"]["401Unauthorized"];
            403: components["responses"]["403Forbidden"];
            404: components["responses"]["404NotFound"];
        };
    };
}
