/*
 * Copyright (c) 2025, Salesforce, Inc.
 * SPDX-License-Identifier: Apache-2
 * For full license text, see the license.txt file in the repo root or http://www.apache.org/licenses/LICENSE-2.0
 */
import fs from 'node:fs/promises';
import os from 'node:os';
import path from 'node:path';
import {Args, Flags} from '@oclif/core';
import {input, select} from '@inquirer/prompts';
import {BaseCommand} from '@salesforce/b2c-tooling-sdk/cli';
import {isValidScaffoldName, type ScaffoldCategory} from '@salesforce/b2c-tooling-sdk/scaffold';
import {t, withDocs} from '../../i18n/index.js';

/**
 * Response type for the init command.
 */
interface ScaffoldInitResponse {
  name: string;
  path: string;
  location: 'custom' | 'project' | 'user';
  files: string[];
}

const SCAFFOLD_TEMPLATE = `{
  "name": "{{name}}",
  "displayName": "{{displayName}}",
  "description": "{{description}}",
  "category": "{{category}}",
  "version": "1.0",
  "tags": [],
  "parameters": [
    {
      "name": "exampleParam",
      "prompt": "Enter a value for the example parameter:",
      "type": "string",
      "required": true
    }
  ],
  "files": [
    {
      "template": "example.txt.ejs",
      "destination": "{{exampleParam}}/example.txt"
    }
  ],
  "postInstructions": "Your scaffold has been generated!\\n\\nNext steps:\\n1. Review the generated files\\n2. Customize as needed"
}`;

const EXAMPLE_TEMPLATE = `<%# Example template file %>
<%# Available helpers: kebabCase, camelCase, pascalCase, snakeCase, year, date, uuid %>

This is an example file generated by the <%= name %> scaffold.

Parameter value: <%= exampleParam %>
Generated on: <%= date %>
`;

/**
 * Command to initialize a new custom scaffold.
 */
export default class ScaffoldInit extends BaseCommand<typeof ScaffoldInit> {
  static args = {
    name: Args.string({
      description: 'Name for the new scaffold (kebab-case)',
      required: false,
    }),
  };

  static description = withDocs(
    t('commands.scaffold.init.description', 'Create a new custom scaffold template'),
    '/cli/scaffold.html#b2c-scaffold-init',
  );

  static enableJsonFlag = true;

  static examples = [
    '<%= config.bin %> <%= command.id %> my-scaffold',
    '<%= config.bin %> <%= command.id %> my-scaffold --project',
    '<%= config.bin %> <%= command.id %> my-scaffold --user',
    '<%= config.bin %> <%= command.id %> --output ./scaffolds/custom',
  ];

  static flags = {
    project: Flags.boolean({
      description: 'Create in project scaffolds directory (.b2c/scaffolds/)',
      exclusive: ['user', 'output'],
    }),
    user: Flags.boolean({
      description: 'Create in user scaffolds directory (~/.b2c/scaffolds/)',
      exclusive: ['project', 'output'],
    }),
    output: Flags.string({
      char: 'o',
      description: 'Custom output directory for the scaffold',
      exclusive: ['project', 'user'],
    }),
    force: Flags.boolean({
      char: 'f',
      description: 'Overwrite existing scaffold if it exists',
      default: false,
    }),
  };

  async run(): Promise<ScaffoldInitResponse> {
    let scaffoldName = this.args.name;
    const isTTY = process.stdin.isTTY && process.stdout.isTTY;

    // Prompt for name if not provided
    if (!scaffoldName && isTTY) {
      scaffoldName = await input({
        message: 'What is the scaffold name?',
        validate(value) {
          if (!value) return 'Name is required';
          if (!isValidScaffoldName(value)) {
            return 'Scaffold name must be kebab-case (lowercase letters, numbers, hyphens)';
          }
          return true;
        },
      });
    }

    if (!scaffoldName) {
      this.error('Scaffold name is required');
    }

    if (!isValidScaffoldName(scaffoldName)) {
      this.error('Scaffold name must be kebab-case (lowercase letters, numbers, hyphens)');
    }

    // Determine output location
    let scaffoldDir: string;
    let location: 'custom' | 'project' | 'user';

    if (this.flags.output) {
      scaffoldDir = path.resolve(this.flags.output, scaffoldName);
      location = 'custom';
    } else if (this.flags.user) {
      scaffoldDir = path.join(os.homedir(), '.b2c', 'scaffolds', scaffoldName);
      location = 'user';
    } else if (this.flags.project || !isTTY) {
      scaffoldDir = path.join(process.cwd(), '.b2c', 'scaffolds', scaffoldName);
      location = 'project';
    } else {
      // Interactive location selection
      const selectedLocation = await select({
        message: 'Where should the scaffold be created?',
        choices: [
          {
            name: 'Project (.b2c/scaffolds/)',
            value: 'project',
            description: 'Scaffold available only in this project',
          },
          {
            name: 'User (~/.b2c/scaffolds/)',
            value: 'user',
            description: 'Scaffold available to all your projects',
          },
        ],
      });
      location = selectedLocation as 'project' | 'user';

      scaffoldDir =
        location === 'user'
          ? path.join(os.homedir(), '.b2c', 'scaffolds', scaffoldName)
          : path.join(process.cwd(), '.b2c', 'scaffolds', scaffoldName);
    }

    // Check if scaffold already exists
    try {
      await fs.access(scaffoldDir);
      if (!this.flags.force) {
        this.error(`Scaffold already exists at ${scaffoldDir}. Use --force to overwrite.`);
      }
    } catch {
      // Directory doesn't exist, which is what we want
    }

    // Gather additional info interactively
    let displayName = scaffoldName
      .split('-')
      .map((w) => w.charAt(0).toUpperCase() + w.slice(1))
      .join(' ');
    let description = 'A custom scaffold';
    let category: ScaffoldCategory = 'cartridge';

    if (isTTY && !this.jsonEnabled()) {
      displayName = await input({
        message: 'Display name for the scaffold:',
        default: displayName,
      });

      description = await input({
        message: 'Describe what this scaffold creates:',
        default: description,
      });

      category = (await select({
        message: 'Category for the scaffold:',
        choices: [
          {name: 'Cartridge', value: 'cartridge'},
          {name: 'Custom API', value: 'custom-api'},
          {name: 'Page Designer', value: 'page-designer'},
          {name: 'Job', value: 'job'},
          {name: 'Metadata', value: 'metadata'},
        ],
      })) as ScaffoldCategory;
    }

    // Create the scaffold directory structure
    const filesDir = path.join(scaffoldDir, 'files');
    await fs.mkdir(filesDir, {recursive: true});

    // Generate scaffold.json
    const manifestContent = SCAFFOLD_TEMPLATE.replaceAll('{{name}}', scaffoldName)
      .replaceAll('{{displayName}}', displayName)
      .replaceAll('{{description}}', description)
      .replaceAll('{{category}}', category);

    await fs.writeFile(path.join(scaffoldDir, 'scaffold.json'), manifestContent, 'utf8');

    // Generate example template
    const exampleContent = EXAMPLE_TEMPLATE.replaceAll('{{name}}', scaffoldName);
    await fs.writeFile(path.join(filesDir, 'example.txt.ejs'), exampleContent, 'utf8');

    const createdFiles = ['scaffold.json', 'files/example.txt.ejs'];

    const response: ScaffoldInitResponse = {
      name: scaffoldName,
      path: scaffoldDir,
      location,
      files: createdFiles,
    };

    if (this.jsonEnabled()) {
      return response;
    }

    this.log('');
    this.log(t('commands.scaffold.init.success', 'Scaffold "{{name}}" created successfully!', {name: scaffoldName}));
    this.log('');
    this.log(`Location: ${scaffoldDir}`);
    this.log('');
    this.log('Created files:');
    for (const file of createdFiles) {
      this.log(`  + ${file}`);
    }
    this.log('');
    this.log('Next steps:');
    this.log('  1. Edit scaffold.json to define your parameters');
    this.log('  2. Add template files in the files/ directory');
    this.log('  3. Test with: b2c scaffold generate ' + scaffoldName + ' --dry-run');
    this.log('  4. Validate with: b2c scaffold validate ' + scaffoldDir);

    return response;
  }
}
