packages:
  - packages/*

# Use hoisted node_modules for npm-compatible bundleDependencies
nodeLinker: hoisted

minimumReleaseAge: 2880

minimumReleaseAgeExclude: []

onlyBuiltDependencies:
  - unrs-resolver
  - yarn

trustPolicy: no-downgrade

trustPolicyExclude: []
