packages:
  - packages/*

minimumReleaseAge: 2880

minimumReleaseAgeExclude: []

nodeLinker: hoisted

# Pin exact versions by default when adding dependencies (no ^ or ~ prefix)
savePrefix: ''

onlyBuiltDependencies:
  - unrs-resolver
  - yarn

overrides:
  '@isaacs/brace-expansion@<=5.0.0': '>=5.0.1'
  diff@>=4.0.0 <4.0.4: '>=4.0.4'
  diff@>=5.0.0 <5.2.2: '>=5.2.2'
  esbuild@<=0.24.2: '>=0.25.0'
  fast-xml-parser@>=4.3.6 <=5.3.3: '>=5.3.4'
  hono@<4.11.4: '>=4.11.4'
  hono@<4.11.7: '>=4.11.7'
  js-yaml@>=4.0.0 <4.1.1: '>=4.1.1'
  lodash@>=4.0.0 <=4.17.22: '>=4.17.23'
  mdast-util-to-hast@>=13.0.0 <13.2.1: '>=13.2.1'
  preact@>=10.27.0 <10.27.3: '>=10.27.3'
  qs@<6.14.1: '>=6.14.1'

trustPolicy: no-downgrade

trustPolicyExclude: []
