/*
 * Copyright (c) 2025, Salesforce, Inc.
 * SPDX-License-Identifier: Apache-2
 * For full license text, see the license.txt file in the repo root or http://www.apache.org/licenses/LICENSE-2.0
 */

/**
 * B2C metadata XML validation is delivered by the third-party Red Hat XML
 * extension (`redhat.vscode-xml`, backed by the LemMinX language server), which
 * we treat as a *soft* dependency (not force-installed via extensionDependencies).
 *
 * Association is NAMESPACE-based, not path-based. We bundle an OASIS XML catalog
 * (resources/xsd-catalog.xml) that maps each schema's targetNamespace → its
 * bundled XSD, and register it at runtime through vscode-xml's exported
 * `addXMLCatalogs()` API. B2C metadata XML always declares its namespace, so
 * LemMinX picks the right schema from the document itself regardless of filename
 * or location. This is done fully in-memory over LSP — we never write the user's
 * settings.json (no `xml.catalogs` pollution) and require no Java (catalogs are
 * core LemMinX, honored by the native binary server; only `xml.javaExtensions`
 * SPI JARs would force the Java server). A handful of schemas share a namespace
 * and so cannot be catalogued unambiguously; those are registered as path-glob
 * file associations via `addXMLFileAssociations()`. Both the catalog and the
 * association list are generated by scripts/sync-xsd.mjs into
 * resources/xml-validation.generated.json.
 *
 * Delivery model:
 *  - The `b2c-dx.features.xmlValidation` setting gates the whole integration.
 *  - When vscode-xml is present, we register the catalog + associations on
 *    activation (and again right after a user installs it).
 *  - We prompt to install vscode-xml only when the user actually opens a file
 *    matching a B2C metadata glob — never on startup — and only once (a "Don't
 *    ask again" choice is remembered in globalState).
 *  - The `b2c-dx.xml.setupValidation` command is the manual re-entry point.
 */
import * as fs from 'fs';
import * as vscode from 'vscode';
import {markFeatureUsed} from '../telemetry.js';

/** The extension we depend on (softly) to run XSD validation. */
const XML_EXTENSION_ID = 'redhat.vscode-xml';
const XML_MARKETPLACE_URL = 'https://marketplace.visualstudio.com/items?itemName=redhat.vscode-xml';

/** Feature-gate setting; mirrors the other `b2c-dx.features.*` toggles. */
const FEATURE_SETTING = 'features.xmlValidation';

/** globalState key: user asked us to stop suggesting the XML extension. */
const SUPPRESS_PROMPT_KEY = 'b2c-dx.xmlValidation.suppressInstallPrompt';

/** Build-generated runtime config (see scripts/sync-xsd.mjs). */
const RUNTIME_CONFIG_RELATIVE = 'resources/xml-validation.generated.json';

/** Shape of a file association entry accepted by vscode-xml's addXMLFileAssociations(). */
interface XmlFileAssociation {
  pattern: string;
  systemId: string;
}

interface XmlValidationRuntimeConfig {
  catalog: string;
  fileAssociations: XmlFileAssociation[];
  detectionGlobs: string[];
}

/**
 * The subset of redhat.vscode-xml's exported API we use. Verified against
 * vscode-xml src/api/xmlExtensionApi.ts — these mutate in-memory settings and
 * notify LemMinX over LSP (no settings.json write).
 */
interface XmlExtensionApi {
  addXMLCatalogs(catalogs: string[]): void;
  addXMLFileAssociations(fileAssociations: XmlFileAssociation[]): void;
}

/** True when the XML validation feature is enabled in settings (default on). */
function isFeatureEnabled(): boolean {
  return vscode.workspace.getConfiguration('b2c-dx').get<boolean>('features.xmlValidation', true);
}

/** True when the Red Hat XML extension is installed (enabled or not). */
function isXmlExtensionInstalled(): boolean {
  return vscode.extensions.getExtension(XML_EXTENSION_ID) !== undefined;
}

/**
 * Load the build-generated runtime config. Returns undefined (and logs) if it
 * is missing or malformed, so a packaging slip degrades to the install prompt
 * rather than throwing during activation.
 */
function loadRuntimeConfig(context: vscode.ExtensionContext): XmlValidationRuntimeConfig | undefined {
  const uri = vscode.Uri.joinPath(context.extensionUri, RUNTIME_CONFIG_RELATIVE);
  try {
    const parsed = JSON.parse(fs.readFileSync(uri.fsPath, 'utf8')) as Partial<XmlValidationRuntimeConfig>;
    if (typeof parsed.catalog !== 'string' || !Array.isArray(parsed.detectionGlobs)) return undefined;
    return {
      catalog: parsed.catalog,
      fileAssociations: Array.isArray(parsed.fileAssociations) ? parsed.fileAssociations : [],
      detectionGlobs: parsed.detectionGlobs,
    };
  } catch {
    return undefined;
  }
}

/** Resolve an extension-relative path (as stored in the runtime config) to absolute. */
function resolveExtensionPath(context: vscode.ExtensionContext, relative: string): string {
  const clean = relative.replace(/^\.\//, '');
  return vscode.Uri.joinPath(context.extensionUri, clean).fsPath;
}

/**
 * Register our namespace catalog and collision-fallback associations with a
 * present-and-activated vscode-xml, via its exported API. In-memory only — no
 * settings write. Best-effort: any failure (unexpected API shape, activation
 * error) is logged and swallowed so it never breaks our activation.
 */
async function registerWithXmlExtension(
  context: vscode.ExtensionContext,
  config: XmlValidationRuntimeConfig,
  log?: vscode.OutputChannel,
): Promise<void> {
  const ext = vscode.extensions.getExtension<XmlExtensionApi | undefined>(XML_EXTENSION_ID);
  if (!ext) return;
  try {
    const api = ext.isActive ? ext.exports : await ext.activate();
    if (!api || typeof api.addXMLCatalogs !== 'function') {
      log?.appendLine('[XML] redhat.vscode-xml did not expose addXMLCatalogs(); skipping catalog registration.');
      return;
    }
    api.addXMLCatalogs([resolveExtensionPath(context, config.catalog)]);
    if (config.fileAssociations.length && typeof api.addXMLFileAssociations === 'function') {
      api.addXMLFileAssociations(
        config.fileAssociations.map((a) => ({
          pattern: a.pattern,
          systemId: resolveExtensionPath(context, a.systemId),
        })),
      );
    }
    markFeatureUsed('xmlValidation');
    log?.appendLine(
      `[XML] Registered B2C metadata catalog (namespace-based) + ${config.fileAssociations.length} association(s) with redhat.vscode-xml.`,
    );
  } catch (err) {
    log?.appendLine(
      `[XML] Failed to register catalog with redhat.vscode-xml: ${err instanceof Error ? err.message : String(err)}`,
    );
  }
}

/** Does the given document's path match any contributed B2C metadata XML glob? */
function isB2cMetadataXml(doc: vscode.TextDocument, globs: string[]): boolean {
  if (doc.languageId !== 'xml' && !doc.fileName.toLowerCase().endsWith('.xml')) return false;
  // Match against the workspace-relative path so `**/…` globs behave the same
  // as vscode-xml evaluates them. Falls back to the absolute path when the file
  // lives outside any workspace folder.
  const relative = vscode.workspace.asRelativePath(doc.uri, false);
  return globs.some((glob) => matchGlob(relative, glob) || matchGlob(doc.uri.fsPath, glob));
}

/**
 * Minimal glob matcher for the `**`/`*` subset used by our fileMatch entries
 * (e.g. `**​/sites/*​/promotions.xml`). We avoid pulling in a glob dependency:
 * the patterns are simple and fully under our control in xsd-mappings.json.
 *
 * Exported for unit testing.
 */
export function matchGlob(candidate: string, glob: string): boolean {
  const normalized = candidate.replace(/\\/g, '/');
  const regex = globToRegExp(glob);
  return regex.test(normalized);
}

function globToRegExp(glob: string): RegExp {
  let re = '';
  for (let i = 0; i < glob.length; i++) {
    const char = glob[i];
    if (char === '*') {
      if (glob[i + 1] === '*') {
        // `**` (optionally followed by `/`) matches any number of path segments.
        i++;
        if (glob[i + 1] === '/') i++;
        re += '(?:.*/)?';
      } else {
        // `*` matches within a single path segment.
        re += '[^/]*';
      }
    } else if ('.+?^${}()|[]\\'.includes(char)) {
      re += '\\' + char;
    } else {
      re += char;
    }
  }
  return new RegExp('^' + re + '$');
}

/**
 * Ensure vscode-xml is installed, prompting the user with an Install action.
 * `interactive` = true is the manual command path (always prompts, even when
 * previously suppressed); false is the automatic on-open path (respects the
 * "Don't ask again" choice and offers to remember it).
 */
async function ensureXmlExtension(context: vscode.ExtensionContext, interactive: boolean): Promise<void> {
  if (isXmlExtensionInstalled()) {
    if (interactive) {
      vscode.window.showInformationMessage(
        'B2C DX: Metadata XML validation is active (Red Hat XML extension installed).',
      );
    }
    return;
  }

  const installAction = 'Install';
  const detailAction = 'Learn More';
  const message =
    'B2C DX metadata XML validation needs the Red Hat XML extension (redhat.vscode-xml) to run. Install it now?';

  let choice: string | undefined;
  if (interactive) {
    choice = await vscode.window.showInformationMessage(message, installAction, detailAction);
  } else {
    const dontAskAction = "Don't ask again";
    choice = await vscode.window.showInformationMessage(message, installAction, detailAction, dontAskAction);
    if (choice === dontAskAction) {
      await context.globalState.update(SUPPRESS_PROMPT_KEY, true);
      return;
    }
  }

  if (choice === detailAction) {
    await vscode.env.openExternal(vscode.Uri.parse(XML_MARKETPLACE_URL));
    return;
  }
  if (choice !== installAction) return;

  try {
    await vscode.commands.executeCommand('workbench.extensions.installExtension', XML_EXTENSION_ID);
    markFeatureUsed('xmlValidation');
    // Register our catalog with the freshly-installed extension so validation is
    // live immediately, without requiring a window reload.
    const config = loadRuntimeConfig(context);
    if (config) await registerWithXmlExtension(context, config);
    vscode.window.showInformationMessage(
      'B2C DX: Red Hat XML extension installed. Open a metadata XML file to see inline validation.',
    );
  } catch (err) {
    const detail = err instanceof Error ? err.message : String(err);
    const openMarketplace = 'Open Marketplace';
    const action = await vscode.window.showErrorMessage(
      `B2C DX: Could not install the Red Hat XML extension automatically (${detail}). Install it manually from the Marketplace.`,
      openMarketplace,
    );
    if (action === openMarketplace) {
      await vscode.env.openExternal(vscode.Uri.parse(XML_MARKETPLACE_URL));
    }
  }
}

/**
 * Register the soft vscode-xml dependency: register our namespace catalog with
 * an already-present vscode-xml, expose the manual setup command, and run a
 * non-intrusive on-open listener that suggests installing the XML extension the
 * first time the user opens a B2C metadata XML without it.
 */
export function registerXmlValidation(context: vscode.ExtensionContext, log?: vscode.OutputChannel): void {
  const config = loadRuntimeConfig(context);
  if (!config) {
    log?.appendLine(`[XML] ${RUNTIME_CONFIG_RELATIVE} missing or invalid; XML validation registration skipped.`);
  }

  // If vscode-xml is already installed and the feature is on, register our
  // catalog now so validation works from the first opened metadata XML.
  if (config && isFeatureEnabled() && isXmlExtensionInstalled()) {
    void registerWithXmlExtension(context, config, log);
  }

  // Manual re-entry point — always available regardless of the feature setting,
  // so a user who disabled the feature (or dismissed the prompt) can turn it
  // back on. Clears the suppression flag so the on-open prompt can fire again.
  context.subscriptions.push(
    vscode.commands.registerCommand('b2c-dx.xml.setupValidation', async () => {
      markFeatureUsed('xmlValidation');
      await context.globalState.update(SUPPRESS_PROMPT_KEY, undefined);

      if (!isFeatureEnabled()) {
        const enable = 'Enable';
        const choice = await vscode.window.showInformationMessage(
          'B2C DX: Metadata XML validation is disabled (b2c-dx.features.xmlValidation). Enable it?',
          enable,
        );
        if (choice !== enable) return;
        await vscode.workspace
          .getConfiguration('b2c-dx')
          .update(FEATURE_SETTING, true, vscode.ConfigurationTarget.Workspace);
      }

      await ensureXmlExtension(context, true);
      // Already-installed case: ensureXmlExtension doesn't re-register, so make
      // sure the catalog is registered for this session.
      if (config && isXmlExtensionInstalled()) await registerWithXmlExtension(context, config, log);
    }),
  );

  // Automatic, non-intrusive suggestion. Fires only when the user opens a file
  // matching a B2C metadata glob, the feature is on, vscode-xml is missing, and
  // the user hasn't opted out. One prompt, then it stays quiet.
  const globs = config?.detectionGlobs ?? [];
  let prompted = false;

  const maybePrompt = (doc: vscode.TextDocument | undefined) => {
    if (prompted) return;
    if (!doc) return;
    if (!isFeatureEnabled()) return;
    if (isXmlExtensionInstalled()) return;
    if (context.globalState.get<boolean>(SUPPRESS_PROMPT_KEY)) return;
    if (!isB2cMetadataXml(doc, globs)) return;
    prompted = true;
    markFeatureUsed('xmlValidation');
    void ensureXmlExtension(context, false);
  };

  context.subscriptions.push(
    vscode.workspace.onDidOpenTextDocument((doc) => maybePrompt(doc)),
    vscode.window.onDidChangeActiveTextEditor((editor) => maybePrompt(editor?.document)),
  );

  // Check whatever's already open at activation (best-effort, non-blocking).
  maybePrompt(vscode.window.activeTextEditor?.document);
}
