/*
 * Copyright (c) 2025, Salesforce, Inc.
 * SPDX-License-Identifier: Apache-2
 * For full license text, see the license.txt file in the repo root or http://www.apache.org/licenses/LICENSE-2.0
 */

/**
 * B2C metadata XML validation is delivered by the third-party Red Hat XML
 * extension (`redhat.vscode-xml`): this extension only *contributes* the XSD
 * schemas and the file-glob→schema bindings via `contributes.xmlValidation` in
 * package.json. Those bindings are completely inert — no diagnostics, no cost —
 * unless vscode-xml is installed to consume them.
 *
 * Rather than force-install vscode-xml through `extensionDependencies` (which
 * every user gets, cannot remove, and pays for even if they never open a
 * metadata XML), we treat it as a *soft* dependency:
 *
 *  - The `b2c-dx.features.xmlValidation` setting gates the whole integration.
 *  - We prompt for vscode-xml only when the user actually opens a file that
 *    matches one of our contributed globs — never on startup — and only once
 *    (a "Don't ask again" choice is remembered in globalState).
 *  - The `b2c-dx.xml.setupValidation` command is the manual re-entry point: it
 *    clears the suppression and walks the user through enabling the feature and
 *    installing vscode-xml.
 */
import * as vscode from 'vscode';
import {markFeatureUsed} from '../telemetry.js';

/** The extension we depend on (softly) to run XSD validation. */
const XML_EXTENSION_ID = 'redhat.vscode-xml';
const XML_MARKETPLACE_URL = 'https://marketplace.visualstudio.com/items?itemName=redhat.vscode-xml';

/** Feature-gate setting; mirrors the other `b2c-dx.features.*` toggles. */
const FEATURE_SETTING = 'features.xmlValidation';

/** globalState key: user asked us to stop suggesting the XML extension. */
const SUPPRESS_PROMPT_KEY = 'b2c-dx.xmlValidation.suppressInstallPrompt';

interface XmlValidationEntry {
  fileMatch: string | string[];
  url: string;
}

/** True when the XML validation feature is enabled in settings (default on). */
function isFeatureEnabled(): boolean {
  return vscode.workspace.getConfiguration('b2c-dx').get<boolean>('features.xmlValidation', true);
}

/** True when the Red Hat XML extension is installed (enabled or not). */
function isXmlExtensionInstalled(): boolean {
  return vscode.extensions.getExtension(XML_EXTENSION_ID) !== undefined;
}

/**
 * Read the file-glob patterns this extension contributes for XSD validation
 * straight from our own package.json manifest. This is the single source of
 * truth (generated by scripts/sync-xsd.mjs), so the "is this a B2C metadata
 * XML?" test can never drift from what vscode-xml is actually told to validate.
 */
function getContributedGlobs(context: vscode.ExtensionContext): string[] {
  const contributes = (context.extension.packageJSON as {contributes?: {xmlValidation?: XmlValidationEntry[]}})
    .contributes;
  const entries = contributes?.xmlValidation ?? [];
  const globs: string[] = [];
  for (const entry of entries) {
    if (Array.isArray(entry.fileMatch)) {
      globs.push(...entry.fileMatch);
    } else if (typeof entry.fileMatch === 'string') {
      globs.push(entry.fileMatch);
    }
  }
  return globs;
}

/** Does the given document's path match any contributed B2C metadata XML glob? */
function isB2cMetadataXml(doc: vscode.TextDocument, globs: string[]): boolean {
  if (doc.languageId !== 'xml' && !doc.fileName.toLowerCase().endsWith('.xml')) return false;
  // Match against the workspace-relative path so `**/…` globs behave the same
  // as vscode-xml evaluates them. Falls back to the absolute path when the file
  // lives outside any workspace folder.
  const relative = vscode.workspace.asRelativePath(doc.uri, false);
  return globs.some((glob) => matchGlob(relative, glob) || matchGlob(doc.uri.fsPath, glob));
}

/**
 * Minimal glob matcher for the `**`/`*` subset used by our fileMatch entries
 * (e.g. `**​/sites/*​/promotions.xml`). We avoid pulling in a glob dependency:
 * the patterns are simple and fully under our control in xsd-mappings.json.
 */
function matchGlob(candidate: string, glob: string): boolean {
  const normalized = candidate.replace(/\\/g, '/');
  const regex = globToRegExp(glob);
  return regex.test(normalized);
}

function globToRegExp(glob: string): RegExp {
  let re = '';
  for (let i = 0; i < glob.length; i++) {
    const char = glob[i];
    if (char === '*') {
      if (glob[i + 1] === '*') {
        // `**` (optionally followed by `/`) matches any number of path segments.
        i++;
        if (glob[i + 1] === '/') i++;
        re += '(?:.*/)?';
      } else {
        // `*` matches within a single path segment.
        re += '[^/]*';
      }
    } else if ('.+?^${}()|[]\\'.includes(char)) {
      re += '\\' + char;
    } else {
      re += char;
    }
  }
  return new RegExp('^' + re + '$');
}

/**
 * Ensure vscode-xml is installed, prompting the user with an Install action.
 * `interactive` = true is the manual command path (always prompts, even when
 * previously suppressed); false is the automatic on-open path (respects the
 * "Don't ask again" choice and offers to remember it).
 */
async function ensureXmlExtension(context: vscode.ExtensionContext, interactive: boolean): Promise<void> {
  if (isXmlExtensionInstalled()) {
    if (interactive) {
      vscode.window.showInformationMessage('B2C DX: Metadata XML validation is active (Red Hat XML extension installed).');
    }
    return;
  }

  const installAction = 'Install';
  const detailAction = 'Learn More';
  const message =
    'B2C DX metadata XML validation needs the Red Hat XML extension (redhat.vscode-xml) to run. Install it now?';

  let choice: string | undefined;
  if (interactive) {
    choice = await vscode.window.showInformationMessage(message, installAction, detailAction);
  } else {
    const dontAskAction = "Don't ask again";
    choice = await vscode.window.showInformationMessage(message, installAction, detailAction, dontAskAction);
    if (choice === dontAskAction) {
      await context.globalState.update(SUPPRESS_PROMPT_KEY, true);
      return;
    }
  }

  if (choice === detailAction) {
    await vscode.env.openExternal(vscode.Uri.parse(XML_MARKETPLACE_URL));
    return;
  }
  if (choice !== installAction) return;

  try {
    await vscode.commands.executeCommand('workbench.extensions.installExtension', XML_EXTENSION_ID);
    markFeatureUsed('xmlValidation');
    vscode.window.showInformationMessage(
      'B2C DX: Red Hat XML extension installed. Open a metadata XML file to see inline validation.',
    );
  } catch (err) {
    const detail = err instanceof Error ? err.message : String(err);
    const openMarketplace = 'Open Marketplace';
    const action = await vscode.window.showErrorMessage(
      `B2C DX: Could not install the Red Hat XML extension automatically (${detail}). Install it manually from the Marketplace.`,
      openMarketplace,
    );
    if (action === openMarketplace) {
      await vscode.env.openExternal(vscode.Uri.parse(XML_MARKETPLACE_URL));
    }
  }
}

/**
 * Register the soft vscode-xml dependency: the manual setup command plus a
 * non-intrusive on-open listener that suggests the XML extension the first time
 * the user opens a B2C metadata XML without it installed.
 */
export function registerXmlValidation(context: vscode.ExtensionContext): void {
  // Manual re-entry point — always available regardless of the feature setting,
  // so a user who disabled the feature (or dismissed the prompt) can turn it
  // back on. Clears the suppression flag so the on-open prompt can fire again.
  context.subscriptions.push(
    vscode.commands.registerCommand('b2c-dx.xml.setupValidation', async () => {
      markFeatureUsed('xmlValidation');
      await context.globalState.update(SUPPRESS_PROMPT_KEY, undefined);

      if (!isFeatureEnabled()) {
        const enable = 'Enable';
        const choice = await vscode.window.showInformationMessage(
          'B2C DX: Metadata XML validation is disabled (b2c-dx.features.xmlValidation). Enable it?',
          enable,
        );
        if (choice !== enable) return;
        await vscode.workspace
          .getConfiguration('b2c-dx')
          .update(FEATURE_SETTING, true, vscode.ConfigurationTarget.Workspace);
      }

      await ensureXmlExtension(context, true);
    }),
  );

  // Automatic, non-intrusive suggestion. Fires only when the user opens a file
  // that matches one of our contributed globs, the feature is on, vscode-xml is
  // missing, and the user hasn't opted out. One prompt, then it stays quiet.
  const globs = getContributedGlobs(context);
  let prompted = false;

  const maybePrompt = (doc: vscode.TextDocument | undefined) => {
    if (prompted) return;
    if (!doc) return;
    if (!isFeatureEnabled()) return;
    if (isXmlExtensionInstalled()) return;
    if (context.globalState.get<boolean>(SUPPRESS_PROMPT_KEY)) return;
    if (!isB2cMetadataXml(doc, globs)) return;
    prompted = true;
    markFeatureUsed('xmlValidation');
    void ensureXmlExtension(context, false);
  };

  context.subscriptions.push(
    vscode.workspace.onDidOpenTextDocument((doc) => maybePrompt(doc)),
    vscode.window.onDidChangeActiveTextEditor((editor) => maybePrompt(editor?.document)),
  );

  // Check whatever's already open at activation (best-effort, non-blocking).
  maybePrompt(vscode.window.activeTextEditor?.document);
}
