import LineItem = require('./LineItem');
import ExtensibleObject = require('../object/ExtensibleObject');
import CustomAttributes = require('../object/CustomAttributes');
import Promotion = require('../campaign/Promotion');
import CouponLineItem = require('./CouponLineItem');
import Campaign = require('../campaign/Campaign');
import ABTest = require('../campaign/ABTest');
import ABTestSegment = require('../campaign/ABTestSegment');
import utilMap = require('../util/Map');
import EnumValue = require('../value/EnumValue');
import Discount = require('../campaign/Discount');

declare global {
    module ICustomAttributes {
        interface PriceAdjustment extends ICustomAttributes.LineItem {
        }
    }
}

/**
 * The PriceAdjustment class represents an adjustment to the price of an order. A PriceAdjustment can apply to a
 * ProductLineItem, ShippingLineItem, ProductShippingLineItem, or a LineItemCtnr, and are generally categorized as
 * product-level, shipping-level, or order-level. PriceAdjustments are generated by the B2C Commerce promotions engine
 * when applying discounts. See dw.campaign.PromotionMgr.applyDiscounts. They may also be
 * generated by custom code through the API. See for example
 * dw.order.ProductLineItem.createPriceAdjustment. In the latter case, the PriceAdjustment is called
 * "custom"; in the former case, it is called "system". System price adjustments are associated with the promotion that
 * triggered their creation. If the promotion was coupon-based, then the price adjustment will additionally be
 * associated with a coupon line item in the LineItemCtnr.
 */
declare class PriceAdjustment extends LineItem<ICustomAttributes.PriceAdjustment> {
    /**
     * Returns the B2C Commerce AB-test this price adjustment is associated with. The associated AB-test is determined
     * from the ABTestID attribute which is set by the promotions engine when applying discounts.
     * 
     * If the AB-test has been removed from the system since this price adjustment was created, this method returns
     * null. This method always returns null for custom price adjustments.
     */
    readonly ABTest: ABTest | null;
    /**
     * Returns the ID of the AB-test related to this price adjustment.
     */
    readonly ABTestID: string | null;
    /**
     * Returns the B2C Commerce AB-test segment this price adjustment is associated with. The associated AB-test segment
     * is determined from the ABTestSegmentID attribute which is set by the promotions engine when applying discounts.
     * 
     * If the AB-test, or this segment, has been removed from the system since this price adjustment was created, this
     * method returns null. This method always returns null for custom price adjustments.
     */
    readonly ABTestSegment: ABTestSegment | null;
    /**
     * Returns the ID of the AB-test segment related to this price adjustment.
     */
    readonly ABTestSegmentID: string | null;
    /**
     * A `Discount` instance describing the discount applied to
     * obtain this price-adjustment. This method only returns a non-null value
     * if the price-adjustment was created
     * 
     * - when a discount-plan was applied to a basket, or
     * - as a custom price-adjustment using one of the methods
     * dw.order.ProductLineItem.createPriceAdjustment,
     * dw.order.ShippingLineItem.createShippingPriceAdjustment
     * or dw.order.LineItemCtnr.createPriceAdjustment.
     * 
     * Note an instance of the dw.campaign.Discount subclasses is
     * returned, such as dw.campaign.AmountDiscount or
     * dw.campaign.PriceBookPriceDiscount, use
     * dw.campaign.Discount.getType and the constants in
     * dw.campaign.Discount to distinguish between types. Each subclass
     * provides access to specific properties.
     */
    readonly appliedDiscount: Discount | null;
    /**
     * Returns true if the price adjustment was generated by the B2C Commerce promotions engine when applying a
     * promotion assigned to an AB-test.
     */
    readonly basedOnABTest: boolean;
    /**
     * Returns true if the price adjustment was generated by the B2C Commerce promotions engine when applying a
     * promotion assigned to a Campaign or an AB-test.
     * @deprecated The method has been deprecated since the name implies that there is a related Campaign, which may not
     * be true. Use `!isCustom()` instead.
     */
    readonly basedOnCampaign: boolean;
    /**
     * Identifies if the promotion line item results from a coupon.
     */
    readonly basedOnCoupon: boolean;
    /**
     * Returns the B2C Commerce campaign this price adjustment is associated with. The associated campaign is determined
     * from the campaignID attribute which is set by the promotions engine when applying discounts.
     * 
     * If the campaign has been removed from the system since this price adjustment was created, this method returns
     * null. This method always returns null for custom price adjustments.
     * 
     * Note: If the price adjustment was generated by a B2C Commerce promotion as part of an AB-test, then a Campaign
     * object will be returned, but it is a mock implementation, and not a true Campaign. This behavior is required for
     * backwards compatibility and should not be relied upon as it may change in future releases.
     */
    readonly campaign: Campaign | null;
    /**
     * Returns the ID of the campaign the price adjustment was based on.
     * 
     * Note:If the price adjustment was generated by a B2C Commerce promotion as part of an AB-test, then an ID will be
     * returned but it is not the ID of a true campaign. This behavior is required for backwards compatibility and
     * should not be relied upon as it may change in future releases.
     */
    readonly campaignID: string | null;
    /**
     * Returns the coupon line item related to this price adjustment.
     * If the price adjustment is not based on a coupon, null is returned.
     */
    readonly couponLineItem: CouponLineItem | null;
    /**
     * Returns the name of the user who created the price adjustment.
     * This method returns a value if the price-adjustment was
     * created as a custom price-adjustment using one of the methods
     * dw.order.ProductLineItem.createPriceAdjustment,
     * dw.order.ShippingLineItem.createShippingPriceAdjustment
     * or dw.order.LineItemCtnr.createPriceAdjustment.
     * 
     * If an agent user has created the price adjustment, the agent user's name
     * is returned. Otherwise "Customer" is returned.
     */
    readonly createdBy: string;
    /**
     * Returns true if this PriceAdjustment was added manually by a user.
     * 
     * A manual PriceAdjustment is one which has been added as a result of
     * a user interaction e.g. by a user editing an order.
     * 
     * A non-manual PriceAdjustment is one which has been added for a different
     * reason, e.g. by custom logic which automatically adjusts the price of
     * particular products when certain conditions are met.
     */
    manual: boolean;
    /**
     * Returns the promotion associated with this price adjustment. The
     * associated promotion is determined from the promotionID and campaignID
     * attributes which are set by the promotions engine when applying
     * discounts. Alternatively if the promotion applied as part of an AB-test,
     * then the associated promotion is determined from the promotionID
     * attribute and the hidden attributes, abTestID and abTestGroupID.
     * 
     * If the promotion has been removed from the system since this price
     * adjustment was created, or if the promotion still exists but is not
     * assigned to any campaign or AB-test, this method returns null. If the
     * promotion has been reassigned to a different campaign or AB-test since
     * this price adjustment was created, then the system will return an
     * appropriate Promotion instance. This method always returns null for
     * custom price adjustments.
     */
    readonly promotion: Promotion | null;
    /**
     * Returns the ID of the promotion related to this price adjustment.
     */
    readonly promotionID: string;
    /**
     * Returns a map representing the product line items to which this price
     * adjustment is "related" (in the sense defined below) and the portion of
     * this adjustment's price which applies to each after discount prorating is
     * performed. This information is sometimes useful to display in the
     * storefront but is more often useful for integrating with backend
     * order-management and accounting systems which require all discounts to be
     * itemized.
     * 
     * The definition of "related" product line items depends on the type of
     * promotion which generated this price adjustment:
     * 
     * - For order promotions, price adjustments are prorated across all
     * product line items which are not explicitly excluded by the promotion.
     * Custom order price adjustments apply to all items in the LineItemCtnr.
     * - For Buy-X-Get-Y product promotions, price adjustments are prorated
     * across all items all product line items that are involved in the
     * promotion, meaning that the PLI has one or more items contributing to the
     * qualifying product count (i.e. the item is one of the X) or receiving the
     * discount (i.e. the item is one of the Y).
     * - Other product promotions are not prorated and simply adjust the
     * parent product line item, and so the returned map is of size 1.
     * - For shipping promotions, this method returns an empty map.
     * 
     * Buy-X-Get-Y product promotions are prorated as follows: Each price
     * adjustment generated by the promotion is sequentially prorated upon the
     * related items according to the items' adjusted prices after all non-BOGO
     * product promotions are considered, but before order promotions are
     * considered.
     * 
     * Order promotions are prorated sequentially upon non-excluded items
     * according to the order in which they applied during promotion processing.
     * 
     * The values in the map are inclusive of tax if this price adjustment is
     * based on gross pricing, and exclusive of tax otherwise. The sum of the
     * prorated prices always equals the price of this price adjustment.
     */
    readonly proratedPrices: utilMap<any, any>;
    /**
     * Returns the number of items this price adjustment applies to. This value
     * is always equal to 1 for price adjustments generated by order or shipping
     * promotions. For price adjustments generated by product promotions, this
     * value represents the number of units of the parent product line item to
     * which the adjustment applies. Because promotions may have a maximum
     * number of applications this value may be less than the product line item
     * quantity.
     * 
     * For custom price adjustments, not generated by the promotions engine,
     * this method always returns 0.
     */
    readonly quantity: number;
    /**
     * Returns the reason code of the price adjustment. The list of available
     * reason codes is editable system meta-data. An example for using the
     * reason code is that in a call center application the CSR will explain
     * why he gave a discount to the customer.
     */
    reasonCode: EnumValue;
    private constructor();
    /**
     * Returns the B2C Commerce AB-test this price adjustment is associated with. The associated AB-test is determined
     * from the ABTestID attribute which is set by the promotions engine when applying discounts.
     * 
     * If the AB-test has been removed from the system since this price adjustment was created, this method returns
     * null. This method always returns null for custom price adjustments.
     */
    getABTest(): ABTest | null;
    /**
     * Returns the ID of the AB-test related to this price adjustment.
     */
    getABTestID(): string | null;
    /**
     * Returns the B2C Commerce AB-test segment this price adjustment is associated with. The associated AB-test segment
     * is determined from the ABTestSegmentID attribute which is set by the promotions engine when applying discounts.
     * 
     * If the AB-test, or this segment, has been removed from the system since this price adjustment was created, this
     * method returns null. This method always returns null for custom price adjustments.
     */
    getABTestSegment(): ABTestSegment | null;
    /**
     * Returns the ID of the AB-test segment related to this price adjustment.
     */
    getABTestSegmentID(): string | null;
    /**
     * A `Discount` instance describing the discount applied to
     * obtain this price-adjustment. This method only returns a non-null value
     * if the price-adjustment was created
     * 
     * - when a discount-plan was applied to a basket, or
     * - as a custom price-adjustment using one of the methods
     * dw.order.ProductLineItem.createPriceAdjustment,
     * dw.order.ShippingLineItem.createShippingPriceAdjustment
     * or dw.order.LineItemCtnr.createPriceAdjustment.
     * 
     * Note an instance of the dw.campaign.Discount subclasses is
     * returned, such as dw.campaign.AmountDiscount or
     * dw.campaign.PriceBookPriceDiscount, use
     * dw.campaign.Discount.getType and the constants in
     * dw.campaign.Discount to distinguish between types. Each subclass
     * provides access to specific properties.
     */
    getAppliedDiscount(): Discount | null;
    /**
     * Returns the B2C Commerce campaign this price adjustment is associated with. The associated campaign is determined
     * from the campaignID attribute which is set by the promotions engine when applying discounts.
     * 
     * If the campaign has been removed from the system since this price adjustment was created, this method returns
     * null. This method always returns null for custom price adjustments.
     * 
     * Note: If the price adjustment was generated by a B2C Commerce promotion as part of an AB-test, then a Campaign
     * object will be returned, but it is a mock implementation, and not a true Campaign. This behavior is required for
     * backwards compatibility and should not be relied upon as it may change in future releases.
     */
    getCampaign(): Campaign | null;
    /**
     * Returns the ID of the campaign the price adjustment was based on.
     * 
     * Note:If the price adjustment was generated by a B2C Commerce promotion as part of an AB-test, then an ID will be
     * returned but it is not the ID of a true campaign. This behavior is required for backwards compatibility and
     * should not be relied upon as it may change in future releases.
     */
    getCampaignID(): string | null;
    /**
     * Returns the coupon line item related to this price adjustment.
     * If the price adjustment is not based on a coupon, null is returned.
     */
    getCouponLineItem(): CouponLineItem | null;
    /**
     * Returns the name of the user who created the price adjustment.
     * This method returns a value if the price-adjustment was
     * created as a custom price-adjustment using one of the methods
     * dw.order.ProductLineItem.createPriceAdjustment,
     * dw.order.ShippingLineItem.createShippingPriceAdjustment
     * or dw.order.LineItemCtnr.createPriceAdjustment.
     * 
     * If an agent user has created the price adjustment, the agent user's name
     * is returned. Otherwise "Customer" is returned.
     */
    getCreatedBy(): string;
    /**
     * Returns the promotion associated with this price adjustment. The
     * associated promotion is determined from the promotionID and campaignID
     * attributes which are set by the promotions engine when applying
     * discounts. Alternatively if the promotion applied as part of an AB-test,
     * then the associated promotion is determined from the promotionID
     * attribute and the hidden attributes, abTestID and abTestGroupID.
     * 
     * If the promotion has been removed from the system since this price
     * adjustment was created, or if the promotion still exists but is not
     * assigned to any campaign or AB-test, this method returns null. If the
     * promotion has been reassigned to a different campaign or AB-test since
     * this price adjustment was created, then the system will return an
     * appropriate Promotion instance. This method always returns null for
     * custom price adjustments.
     */
    getPromotion(): Promotion | null;
    /**
     * Returns the ID of the promotion related to this price adjustment.
     */
    getPromotionID(): string;
    /**
     * Returns a map representing the product line items to which this price
     * adjustment is "related" (in the sense defined below) and the portion of
     * this adjustment's price which applies to each after discount prorating is
     * performed. This information is sometimes useful to display in the
     * storefront but is more often useful for integrating with backend
     * order-management and accounting systems which require all discounts to be
     * itemized.
     * 
     * The definition of "related" product line items depends on the type of
     * promotion which generated this price adjustment:
     * 
     * - For order promotions, price adjustments are prorated across all
     * product line items which are not explicitly excluded by the promotion.
     * Custom order price adjustments apply to all items in the LineItemCtnr.
     * - For Buy-X-Get-Y product promotions, price adjustments are prorated
     * across all items all product line items that are involved in the
     * promotion, meaning that the PLI has one or more items contributing to the
     * qualifying product count (i.e. the item is one of the X) or receiving the
     * discount (i.e. the item is one of the Y).
     * - Other product promotions are not prorated and simply adjust the
     * parent product line item, and so the returned map is of size 1.
     * - For shipping promotions, this method returns an empty map.
     * 
     * Buy-X-Get-Y product promotions are prorated as follows: Each price
     * adjustment generated by the promotion is sequentially prorated upon the
     * related items according to the items' adjusted prices after all non-BOGO
     * product promotions are considered, but before order promotions are
     * considered.
     * 
     * Order promotions are prorated sequentially upon non-excluded items
     * according to the order in which they applied during promotion processing.
     * 
     * The values in the map are inclusive of tax if this price adjustment is
     * based on gross pricing, and exclusive of tax otherwise. The sum of the
     * prorated prices always equals the price of this price adjustment.
     */
    getProratedPrices(): utilMap<any, any>;
    /**
     * Returns the number of items this price adjustment applies to. This value
     * is always equal to 1 for price adjustments generated by order or shipping
     * promotions. For price adjustments generated by product promotions, this
     * value represents the number of units of the parent product line item to
     * which the adjustment applies. Because promotions may have a maximum
     * number of applications this value may be less than the product line item
     * quantity.
     * 
     * For custom price adjustments, not generated by the promotions engine,
     * this method always returns 0.
     */
    getQuantity(): number;
    /**
     * Returns the reason code of the price adjustment. The list of available
     * reason codes is editable system meta-data. An example for using the
     * reason code is that in a call center application the CSR will explain
     * why he gave a discount to the customer.
     */
    getReasonCode(): EnumValue;
    /**
     * Returns true if the price adjustment was generated by the B2C Commerce promotions engine when applying a
     * promotion assigned to an AB-test.
     */
    isBasedOnABTest(): boolean;
    /**
     * Returns true if the price adjustment was generated by the B2C Commerce promotions engine when applying a
     * promotion assigned to a Campaign or an AB-test.
     * @deprecated The method has been deprecated since the name implies that there is a related Campaign, which may not
     * be true. Use `!isCustom()` instead.
     */
    isBasedOnCampaign(): boolean;
    /**
     * Identifies if the promotion line item results from a coupon.
     */
    isBasedOnCoupon(): boolean;
    /**
     * Returns true if this PriceAdjustment was created by custom script code.
     */
    isCustom(): boolean;
    /**
     * Returns true if this PriceAdjustment was added manually by a user.
     * 
     * A manual PriceAdjustment is one which has been added as a result of
     * a user interaction e.g. by a user editing an order.
     * 
     * A non-manual PriceAdjustment is one which has been added for a different
     * reason, e.g. by custom logic which automatically adjusts the price of
     * particular products when certain conditions are met.
     */
    isManual(): boolean;
    /**
     * Marks the current PriceAdjustment as manual/non-manual.
     * 
     * Note that only custom PriceAdjustment can be marked as manual/non-manual.
     * 
     * A manual PriceAdjustment is one which has been added as a result of
     * a user interaction e.g. by a user editing an order.
     * 
     * A non-manual PriceAdjustment is one which has been added for a different
     * reason, e.g. by custom logic which automatically adjusts the price of
     * particular products when certain conditions are met.
     * @throws IllegalArgumentException if the adjustment is not custom
     */
    setManual(aFlag: boolean): void;
    /**
     * Set the reason code, using the internal non-localizable value. Standard values are 'PRICE_MATCH',
     * 'BACKORDER' and 'EVEN_EXCHANGE', but the available list is editable system meta-data.
     */
    setReasonCode(reasonCode: string): void;
}

export = PriceAdjustment;
