name: 'B2C WebDAV Upload'
description: 'Upload files to a Salesforce B2C Commerce instance via WebDAV'
branding:
  icon: 'upload'
  color: 'blue'

inputs:
  local-path:
    description: 'Local file or directory to upload'
    required: true
  remote-path:
    description: 'Remote destination path'
    required: true
  root:
    description: 'WebDAV root directory (IMPEX, TEMP, CARTRIDGES, etc.)'
    required: false
    default: 'IMPEX'
  # Auth inputs for standalone use
  client-id:
    description: 'OAuth Client ID (falls back to SFCC_CLIENT_ID env var)'
    required: false
  client-secret:
    description: 'OAuth Client Secret (falls back to SFCC_CLIENT_SECRET env var)'
    required: false
  server:
    description: 'B2C instance hostname (falls back to SFCC_SERVER env var)'
    required: false
  username:
    description: 'WebDAV username (falls back to SFCC_USERNAME env var)'
    required: false
  password:
    description: 'WebDAV password/access key (falls back to SFCC_PASSWORD env var)'
    required: false
  # Setup inputs
  version:
    description: 'CLI version to install if not already set up'
    required: false
    default: 'latest'
  node-version:
    description: 'Node.js version'
    required: false
    default: '22'

outputs:
  result:
    description: 'Upload command JSON output'
    value: ${{ steps.upload.outputs.result }}
  exit-code:
    description: 'Command exit code'
    value: ${{ steps.upload.outputs.exit-code }}

runs:
  using: 'composite'
  steps:
    - name: Ensure CLI is installed
      uses: ./actions/setup
      with:
        version: ${{ inputs.version }}
        node-version: ${{ inputs.node-version }}
        client-id: ${{ inputs.client-id }}
        client-secret: ${{ inputs.client-secret }}
        server: ${{ inputs.server }}
        username: ${{ inputs.username }}
        password: ${{ inputs.password }}

    - name: Upload via WebDAV
      id: upload
      uses: ./actions/run
      with:
        command: "webdav put ${{ inputs.local-path }} ${{ inputs.remote-path }} --root ${{ inputs.root }}"
        json: 'true'
