import Stub = require('./Stub');

/**
 * Represents a web service defined in a WSDL file. The implementation is backed by a JAX-RPC framework.
 * You should use the newer dw.ws package and dw.ws.WebReference2 class instead, which is based on JAX-WS.
 * 
 * Use the Services module in Business Manager to set timeout values, not the methods for this class.
 * The Services module provides better analytics and timeout management.
 * 
 * To create an instance of a WebReference object, in a B2C Commerce Script file, reference a WSDL file in the `webreferences`
 * directory and request the service Stub using one of the get service methods.
 * For example, if your WSDL file is `MyWSDL.wsdl`,
 * to create an instance of WebReference and access the Stub:
 * 
 * ```
 * `
 * var webref : WebReference = webreferences.MyWSDL;
 * var stub : Stub = webref.getDefaultService();
 * `
 * ```
 * 
 * Note: script classes representing your WSDL file are are generated by the platform and then placed in the `WebReferences`
 * package. You do not need to include the `importPackage`
 * statement in your B2C Commerce Script file to use classes in the `WebReferences` package.
 * @see dw.rpc.Stub
 * @see dw.rpc.SOAPUtil
 * @deprecated This class is deprecated, please use webreferences2 instead (see also dw.ws.WebReference2).
 * 
 * In migrating from webreferences to webreferences2 the property `collectionType=indexed` may be helpful.
 * Setting this in the property file for the WSDL will make the generated API more closely resemble the API generated by webreferences.
 */
declare abstract class WebReference {
    /**
     * Returns the default service of the WebReference object. If you have more than one service
     * defined in your WSDL, the default service is the first service alphabetically. If the service
     * has multiple ports defined, the default service uses the SOAP port name that is first alphabetically.
     * @deprecated use webreferences2 instead
     */
    readonly defaultService: Stub;
    private constructor();
    /**
     * Returns the default service of the WebReference object. If you have more than one service
     * defined in your WSDL, the default service is the first service alphabetically. If the service
     * has multiple ports defined, the default service uses the SOAP port name that is first alphabetically.
     * @deprecated use webreferences2 instead
     */
    getDefaultService(): Stub;
    /**
     * Returns a specific service from this WebReference.
     * @deprecated use webreferences2 instead
     */
    getService(service: string, port: string): Stub;
}

export = WebReference;
