# Copyright (c) 2025, Salesforce, Inc.
# SPDX-License-Identifier: Apache-2.0
# For full license text, see the LICENSE file in the repo root or http://www.apache.org/licenses/LICENSE-2.0

from __future__ import annotations

from enum import Enum

from pydantic import AwareDatetime, BaseModel, ConfigDict, Field, RootModel


class ApiStandardsErrorResponse(BaseModel):
    title: str = Field(
        ...,
        description="A short, human-readable summary of the problem\ntype.  It will not change from occurrence to occurrence of the \nproblem, except for purposes of localization\n",
        examples=["You do not have enough credit"],
        max_length=256,
    )
    type: str = Field(
        ...,
        description='A URI reference [RFC3986] that identifies the\nproblem type.  This specification encourages that, when\ndereferenced, it provide human-readable documentation for the\nproblem type (e.g., using HTML [W3C.REC-html5-20141028]).  When\nthis member is not present, its value is assumed to be\n"about:blank". It accepts relative URIs; this means\nthat they must be resolved relative to the document\'s base URI, as\nper [RFC3986], Section 5.\n',
        examples=["NotEnoughMoney"],
        max_length=2048,
    )
    detail: str = Field(
        ...,
        description="A human-readable explanation specific to this occurrence of the problem.",
        examples=["Your current balance is 30, but that costs 50"],
        pattern="^.*$",
    )
    instance: str | None = Field(
        None,
        description="A URI reference that identifies the specific\noccurrence of the problem.  It may or may not yield further\ninformation if dereferenced.  It accepts relative URIs; this means\nthat they must be resolved relative to the document's base URI, as\nper [RFC3986], Section 5.\n",
        examples=["/account/12345/msgs/abc"],
        max_length=2048,
    )


class OrganizationId(RootModel[str]):
    root: str = Field(
        ...,
        description="An identifier for the organization the request is being made by",
        examples=["f_ecom_zzxy_prd"],
        max_length=32,
        min_length=1,
    )


class StorefrontZoneCreateRequest(BaseModel):
    """
    The storefront zone information to be created.
    """

    domainName: str = Field(..., description="Domain name for the site.", examples=["cc-merchant.com"], pattern="^.*$")


class Status(Enum):
    """
    current status of the zone
    """

    active = "active"
    pending = "pending"
    initializing = "initializing"
    moved = "moved"
    deleted = "deleted"
    deactivated = "deactivated"


class StorefrontZoneCreateResponse(BaseModel):
    """
    The response of create zone, includes zone and zone properties.
    """

    zoneId: str = Field(
        ..., description="The zone id tag.", examples=["023e105f4ecef8ad9ca31a8372d0c353"], pattern="^.*$"
    )
    zoneName: str = Field(
        ...,
        description="The domain name for the zone.",
        examples=["stg-zzzz-cc-merchant-com.cc-ecdn.net"],
        pattern="^.*$",
    )
    status: Status = Field(..., description="current status of the zone", examples=["active"])
    createdOn: AwareDatetime = Field(
        ..., description="Date and time of zone creation.", examples=["2014-01-01T05:20:00.12345Z"]
    )


class StorefrontZoneCreateEnvelope(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    data: StorefrontZoneCreateResponse


class MtlsCertificateResponse(BaseModel):
    """
    mTLS certificate information.
    """

    mtlsCertificateId: str | None = Field(
        None,
        description="ID generated by the CDN provider for the certificate.",
        examples=["465a48f6-3d98-4c15-9312-211984ee8629"],
        pattern="^.*$",
    )
    expiresOn: AwareDatetime | None = Field(
        None, description="Expiration date for the mTLS certificate.", examples=["2022-01-12T04:15:57Z"]
    )
    issuer: str | None = Field(
        None,
        description="The certificate authority that issued the mTLS certificate.",
        examples=["DigiCert"],
        pattern="^.*$",
    )
    signature: str | None = Field(
        None, description="The type of hash used for the mTLS certificate.", examples=["SHA256WithRSA"], pattern="^.*$"
    )
    uploadedOn: AwareDatetime | None = Field(
        None, description="Date the mTLS certificate was uploaded.", examples=["2020-01-12T04:15:57Z"]
    )
    ca: bool | None = Field(
        None, description="Indicates whether the mTLS certificate is a CA or leaf certificate.", examples=[True]
    )
    serialNumber: str | None = Field(
        None,
        description="The mTLS certificate serial number.",
        examples=["432217133297895665180570788458463042229861757760"],
        pattern="^.*$",
    )
    mtlsCertificateName: str | None = Field(
        None,
        description="Optional name for the mTLS certificate used for ease of understanding.",
        examples=["mtls_cert_name"],
        pattern="^.*$",
    )
    mtlsAssociatedCodeUploadHostname: str | None = Field(
        None,
        description="Hostname associated with this mTLS certificate.",
        examples=["mtls.cert.salesforce.com"],
        pattern="^.*$",
    )


class MtlsCertificatesResponseEnvelope(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    data: list[MtlsCertificateResponse]


class MtlsCertificateRequest(BaseModel):
    """
    mTLS certificate request information.
    """

    model_config = ConfigDict(
        extra="forbid",
    )
    certificate: str = Field(
        ...,
        description="Public key for the CA certificate in mTLS.",
        examples=[
            "-----BEGIN CERTIFICATE-----\nMIIDtTCCAp2gAwIBAgIJAMHAwfXZ5PWMA0GCSqGSIb3DQEBCwUAMEUxCzAJBgNV\nBAYTAkFVMRMwEQYDVQQIEwpTb21lLVN0YXRlMSEwHwYDVQQKExhJbnRlcm5ldCBX\naWRnaXRzIFB0eSBMdGQwHhcNMTYwODI0MTY0MzAxWhcNMTYxMTIyMTY0MzAxWjBF\nMQswCQYDVQQGEwJBVTETMBEGA1UECBMKU29tZS1TdGF0ZTEhMB8GA1UEChMYSW50\nZXJuZXQgV2lkZ2l0cyBQdHkgTHRkMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIB\nCgKCAQEAwQHoetcl9+5ikGzV6cMzWtWPJHqXT3wpbEkRU9Yz7lgvddmGdtcGbg/1\nCGZu0jJGkMoppoUo4c3dts3iwqRYmBikUP77wwY2QGmDZw2FvkJCJlKnabIRuGvB\nKwzESIXgKk2016aTP6/dAjEHyo6SeoK8lkIySUvK0fyOVlsiEsCmOpidtnKX/a+5\n0GjB79CJH4ER2lLVZnhePFR/zUOyPxZQQ4naHf7yu/b5jhO0f8fwt+pyFxIXjbEI\ndZliWRkRMtzrHOJIhrmJ2A1J7iOrirbbwillwjjNVUWPf3IJ3M12S9pEewooaeO2\nizNTERcG9HzAacbVRn2Y2SWIyT/18QIDAQABo4GnMIGkMB0GA1UdDgQWBBT/LbE4\n9rWf288N6sJA5BRb6FJIGDB1BgNVHSMEbjBsgBT/LbE49rWf288N6sJA5BRb6FJI\nGKFJpEcwRTELMAkGA1UEBhMCQVUxEzARBgNVBAgTClNvbWUtU3RhdGUxITAfBgNV\nBAoTGEludGVybmV0IFdpZGdpdHMgUHR5IEx0ZIIJAMHAwfXZ5/PWMAwGA1UdEwQF\nMAMBAf8wDQYJKoZIhvcNAQELBQADggEBAHHFwl0tH0quUYZYO0dZYt4R7SJ0pCm2\n2satiyzHl4OnXcHDpekAo7/a09c6Lz6AU83cKy/+x3/djYHXWba7HpEu0dR3ugQP\nMlr4zrhd9xKZ0KZKiYmtJH+ak4OM4L3FbT0owUZPyjLSlhMtJVcoRp5CJsjAMBUG\nSvD8RX+T01wzox/Qb+lnnNnOlaWpqu8eoOenybxKp1a9ULzIVvN/LAcc+14vioFq\n2swRWtmocBAs8QR9n4uvbpiYvS8eYueDCWMM4fvFfBhaDZ3N9IbtySh3SpFdQDhw\nYbjM2rxXiyLGxB4Bol7QTv4zHif7Zt89FReT/NBy4rzaskDJY5L6xmY=\n-----END CERTIFICATE-----"
        ],
        pattern="^.*$",
    )
    privateKey: str = Field(
        ...,
        description="Private key of the CA certificate in mTLS.",
        examples=[
            "-----BEGIN RSA PRIVATE KEY-----\nMIIEowIBAAKCAQEAwQHoetcl9+5ikGzV6cMzWtWPJHqXT3wpbEkRU9Yz7lgvddmG\ndtcGbg/1CGZu0jJGkMoppoUo4c3dts3iwqRYmBikUP77wwY2QGmDZw2FvkJCJlKn\nabIRuGvBKwzESIXgKk2016aTP6/dAjEHyo6SeoK8lkIySUvK0fyOVlsiEsCmOpid\ntnKX/a+50GjB79CJH4ER2lLVZnhePFR/zUOyPxZQQ4naHf7yu/b5jhO0f8fwt+py\nFxIXjbEIdZliWRkRMtzrHOJIhrmJ2A1J7iOrirbbwillwjjNVUWPf3IJ3M12S9pE\newooaeO2izNTERcG9HzAacbVRn2Y2SWIyT/18QIDAQABAoIBACbhTYXBZYKmYPCb\nHBR1IBlCQA2nLGf0qRuJNJZg5iEzXows/6tc8YymZkQE7nolapWsQ+upk2y5Xdp/\naxiuprIs9JzkYK8Ox0r+dlwCG1kSW+UAbX0bQ/qUqlsTvU6muVuMP8vZYHxJ3wmb\n+ufRBKztPTQ/rYWaYQcgC0RWI20HTFBMxlTAyNxYNWzX7RKFkGVVyB9RsAtmcc8g\n+j4OdosbfNoJPS0HeIfNpAznDfHKdxDk2Yc1tV6RHBrC1ynyLE9+TaflIAdo2MVv\nKLMLq51GqYKtgJFIlBRPQqKoyXdz3fGvXrTkf/WY9QNq0J1Vk5ERePZ54mN8iZB7\n9lwy/AkCgYEA6FXzosxswaJ2wQLeoYc7ceaweX/SwTvxHgXzRyJIIT0eJWgx13Wo\n/WA3Iziimsjf6qE+SI/8laxPp2A86VMaIt3Z3mJN/CqSVGw8LK2AQst+OwdPyDMu\niacE8lj/IFGC8mwNUAb9CzGU3JpU4PxxGFjS/eMtGeRXCWkK4NE+G08CgYEA1Kp9\nN2JrVlqUz+gAX+LPmE9OEMAS9WQSQsfCHGogIFDGGcNf7+uwBM7GAaSJIP01zcoe\nVAgWdzXCv3FLhsaZoJ6RyLOLay5phbu1iaTr4UNYm5WtYTzMzqh8l1+MFFDl9xDB\nvULuCIIrglM5MeS/qnSg1uMoH2oVPj9TVst/ir8CgYEAxrI7Ws9Zc4Bt70N1As+U\nlySjaEVZCMkqvHJ6TCuVZFfQoE0r0whdLdRLU2PsLFP+q7qaeZQqgBaNSKeVcDYR\n9B+nY/jOmQoPewPVsp/vQTCnE/R81spu0mp0YI6cIheT1Z9zAy322svcc43JaWB7\nmEbeqyLOP4Z4qSOcmghZBSECgYACvR9Xs0DGn+wCsW4vze/2ei77MD4OQvepPIFX\ndFZtlBy5ADcgE9z0cuVB6CiL8DbdK5kwY9pGNr8HUCI03iHkW6Zs+0L0YmihfEVe\nPG19PSzK9CaDdhD9KFZSbLyVFmWfxOt50H7YRTTiPMgjyFpfi5j2q348yVT0tEQS\nfhRqaQKBgAcWPokmJ7EbYQGeMbS7HC8eWO/RyamlnSffdCdSc7ue3zdVJxpAkQ8W\nqu80pEIF6raIQfAf8MXiiZ7auFOSnHQTXUbhCpvDLKi0Mwq3G8Pl07l+2s6dQG6T\nlv6XTQaMyf6n1yjzL+fzDrH3qXMxHMO/b13EePXpDMpY7HQpoLDi\n-----END RSA PRIVATE KEY-----"
        ],
        pattern="^.*$",
    )
    name: str = Field(
        ..., description="Certificate name used for ease of understanding.", examples=["mtls_cert_name"], pattern="^.*$"
    )


class MtlsCertificateResponseEnvelope(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    data: MtlsCertificateResponse


class Zone(RootModel[str]):
    root: str = Field(..., examples=["zone_1234567890abcdef"], pattern="^.*$")


class PageShieldNotificationWebhookResponse(BaseModel):
    """
    Page shield notification for the webhook response.
    """

    model_config = ConfigDict(
        extra="forbid",
    )
    id: str = Field(..., description="Webhook ID.", examples=["webhook_1234567890abcdef"], pattern="^.*$")
    name: str = Field(..., description="Webhook name.", examples=["Security Alert Webhook"], pattern="^.*$")
    webhookUrl: str = Field(
        ..., description="Webhook URL.", examples=["https://example.com/webhook/security"], pattern="^.*$"
    )
    type: str = Field(..., description="Webhook type.", examples=["security_alert"], pattern="^.*$")
    createdAt: AwareDatetime = Field(
        ..., description="Timestamp of webhook creation.", examples=["2023-01-01T00:00:00Z"]
    )
    lastSuccess: AwareDatetime | None = Field(
        None, description="Timestamp of the last successful notification.", examples=["2023-01-01T12:00:00Z"]
    )
    lastFailure: AwareDatetime | None = Field(
        None, description="Timestamp of the last failed notification.", examples=["2023-01-01T18:00:00Z"]
    )
    zones: list[Zone] | None = Field(None, description="Zone IDs on which to filter notifications alerts.")


class PageShieldNotificationWebhookListEnvelope(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    data: list[PageShieldNotificationWebhookResponse]


class PageShieldNotificationWebhookRequest(BaseModel):
    """
    Page shield notification for the webhook request.
    """

    model_config = ConfigDict(
        extra="forbid",
    )
    webhookUrl: str = Field(
        ..., description="Webhook URL.", examples=["https://example.com/webhook/security"], pattern="^.*$"
    )
    secret: str | None = Field(
        None, description="Webhook optional secret.", examples=["webhook_secret_123"], pattern="^.*$"
    )
    zones: list[Zone] | None = Field(None, description="Zone names on which to filter notifications alerts.")


class PageShieldNotificationWebhookEnvelope(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    data: PageShieldNotificationWebhookResponse


class Action(Enum):
    """
    Action taken when expression matches allow or log.
    """

    allow = "allow"
    log = "log"


class PageShieldPolicyResponse(BaseModel):
    """
    Page shield policy response.
    """

    model_config = ConfigDict(
        extra="forbid",
    )
    action: Action | None = Field(
        None, description="Action taken when expression matches allow or log.", examples=["allow"]
    )
    description: str | None = Field(
        None,
        description="Description for the policy.",
        examples=["Allow scripts from trusted CDN sources"],
        pattern="^.*$",
    )
    enabled: bool | None = Field(None, description="Enable/disable the policy.", examples=[True])
    expression: str | None = Field(
        None,
        description="Expression of the policy.",
        examples=['http.request.uri.path contains "/trusted-cdn/"'],
        pattern="^.*$",
    )
    value: str | None = Field(None, description="Policy to be applied.", examples=["script-src"], pattern="^.*$")
    id: str | None = Field(None, description="Policy ID", examples=["policy_1234567890abcdef"], pattern="^.*$")


class PageShieldPoliciesListEnvelope(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    data: list[PageShieldPolicyResponse]


class PageShieldPolicyRequest(BaseModel):
    """
    Page shield policy request object.
    """

    model_config = ConfigDict(
        extra="forbid",
    )
    action: Action | None = Field(
        None, description="Action taken when expression matches allow or log.", examples=["allow"]
    )
    description: str | None = Field(
        None,
        description="Description for the policy.",
        examples=["Allow scripts from trusted CDN sources"],
        pattern="^.*$",
    )
    enabled: bool | None = Field(None, description="Enable/disable the policy.", examples=[True])
    expression: str | None = Field(
        None,
        description="Expression of the policy.",
        examples=['http.request.uri.path contains "/trusted-cdn/"'],
        pattern="^.*$",
    )
    value: str | None = Field(None, description="Policy to be applied.", examples=["script-src"], pattern="^.*$")


class PageShieldPoliciesEnvelope(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    data: PageShieldPolicyResponse


class PageShieldScriptVersion(BaseModel):
    """
    Version details for the JavaScript script.
    """

    model_config = ConfigDict(
        extra="forbid",
    )
    hash: str | None = Field(
        None, description="The computed hash of the analyzed script.", examples=["1243453456abc"], pattern="^.*$"
    )
    jsIntegrityScore: int | None = Field(
        None, description="The integrity score of the JavaScript content.", examples=[1]
    )
    obfuscationScore: int | None = Field(
        None, description="The obfuscation score of the JavaScript content.", examples=[2]
    )
    dataflowScore: int | None = Field(None, description="The dataflow score of the JavaScript content.", examples=[1])
    malwareScore: int | None = Field(None, description="The malware score of the JavaScript content.", examples=[1])
    cryptoMiningScore: int | None = Field(
        None, description="The crypto mining score of the JavaScript content.", examples=[1]
    )
    mageCartScore: int | None = Field(None, description="The Magecart score of the JavaScript content.", examples=[2])
    fetchedAt: AwareDatetime | None = Field(
        None, description="The timestamp of when the script was last fetched.", examples=["2023-01-01T00:00:00Z"]
    )
    isMaliciousCode: bool = Field(
        ..., description="Indicates whether the script has been reported as malicious.", examples=[False]
    )


class MaliciousDomainCategory(RootModel[str]):
    root: str = Field(..., examples=["Malware"], pattern="^.*$")


class MaliciousUrlCategory(RootModel[str]):
    root: str = Field(..., examples=["Malware"], pattern="^.*$")


class PageUrl(RootModel[str]):
    root: str = Field(..., examples=["blog.test.salesforce.com/page1"], pattern="^.*$")


class PageShieldScriptResponse(BaseModel):
    """
    Response of Page Shield script object.
    """

    model_config = ConfigDict(
        extra="forbid",
    )
    id: str | None = Field(
        None, description="Page Shield script ID.", examples=["12345678901234asdfasfasdf"], pattern="^.*$"
    )
    url: str | None = Field(
        None,
        description="Page Shield script URL.",
        examples=[
            "https://sfdc-test.net/on/demandware.static/Sites-SiteNemesis-Site/-/en_US//lib/jquery/ui/jquery-ui.min.js"
        ],
        pattern="^.*$",
    )
    host: str | None = Field(
        None,
        description="Hostname where the script was detected by Page Shield.",
        examples=["sfdc-test.net"],
        pattern="^.*$",
    )
    addedAt: AwareDatetime | None = Field(
        None, description="Date the script was added to Page Shield.", examples=["2022-01-01T05:20:00Z"]
    )
    firstSeenAt: AwareDatetime | None = Field(
        None, description="Date the script was detected by Page Shield.", examples=["2022-01-01T05:20:00Z"]
    )
    lastSeenAt: AwareDatetime | None = Field(
        None, description="Date the script was recently detected by Page Shield.", examples=["2022-01-01T05:20:00Z"]
    )
    fetchedAt: AwareDatetime | None = Field(
        None, description="The timestamp when the script was last fetched.", examples=["2022-01-01T05:20:00Z"]
    )
    domainReportedMalicious: bool | None = Field(None, description="Reported domain is malicious.", examples=[False])
    hash: str | None = Field(
        None, description="The computed hash of the analyzed script.", examples=["1243453456abc"], pattern="^.*$"
    )
    cryptoMiningScore: int | None = Field(
        None, description="The crypto mining score of the JavaScript content.", examples=[1]
    )
    dataflowScore: int | None = Field(None, description="The dataflow score of the JavaScript content.", examples=[1])
    jsIntegrityScore: int | None = Field(
        None, description="The integrity score of the JavaScript content.", examples=[1]
    )
    mageCartScore: int | None = Field(None, description="The Magecart score of the JavaScript content.", examples=[2])
    malwareScore: int | None = Field(None, description="The malware score of the JavaScript content.", examples=[1])
    obfuscationScore: int | None = Field(
        None, description="The obfuscation score of the JavaScript content.", examples=[2]
    )
    maliciousDomainCategories: list[MaliciousDomainCategory] | None = Field(
        None, description="Malicious domain category.", examples=[["Malware"]]
    )
    maliciousUrlCategories: list[MaliciousUrlCategory] | None = Field(
        None, description="Malicious URL category.", examples=[["Malware"]]
    )
    urlContainsCdnCgiPath: bool | None = Field(None, description="URL contains CDN CGI path.", examples=[False])
    urlReportedMalicious: bool | None = Field(None, description="Reported URL is malicious.", examples=[False])
    pageUrls: list[PageUrl] | None = Field(
        None, description="Page URLs", examples=[["blog.test.salesforce.com/page1", "blog.test.salesforce.com/page2"]]
    )
    firstPageUrl: str | None = Field(
        None, description="First page URL for the JavaScript.", examples=["blog.test.salesforce.com"], pattern="^.*$"
    )
    status: str | None = Field(
        None,
        description="The current status of the script. Possible values are active, inactive, or infrequent.",
        examples=["active"],
        pattern="^.*$",
    )
    versions: list[PageShieldScriptVersion] | None = Field(None, description="List of script versions.")


class PageShieldScriptListEnvelope(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    data: list[PageShieldScriptResponse]


class PageShieldScriptEnvelope(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    data: PageShieldScriptResponse


class Status1(Enum):
    """
    Status of the zone for eg "Pending" , "Active"
    """

    active = "active"
    pending = "pending"
    initializing = "initializing"
    moved = "moved"
    deleted = "deleted"
    deactivated = "deactivated"


class Zone2(BaseModel):
    """
    Zone is the container for hostnames and various CDN settings/properties. Each zone is tied to a single origin.
    """

    model_config = ConfigDict(
        extra="forbid",
    )
    zoneId: str = Field(..., description="Identity of the zone.", examples=["example1-zone-Id"], max_length=100)
    name: str = Field(
        ...,
        description="Name given to the zone. This needs to be a DNS domain name for eg example.com",
        examples=["example1.com"],
        max_length=100,
    )
    status: Status1 = Field(..., description='Status of the zone for eg "Pending" , "Active"', examples=["pending"])


class ZonesEnvelope(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    data: list[Zone2]


class Action2(Enum):
    """
    The action to apply to WAF group
    """

    block = "block"
    challenge = "challenge"
    monitor = "monitor"
    default = "default"


class Mode(Enum):
    """
    Mode of the waf rule - on vs off
    """

    on = "on"
    off = "off"


class WafGroup(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    groupId: str | None = Field(None, examples=["372e67954025e0ba6aaa6d586b9e0b60"], max_length=100)
    action: Action2 | None = Field(None, description="The action to apply to WAF group", examples=["block"])
    mode: Mode = Field(..., description="Mode of the waf rule - on vs off", examples=["on"])
    description: str | None = Field(
        None,
        description="Description of the WAF Group.",
        examples=["Test WAF Group to protect against SQL injection"],
        pattern="^.*$",
    )


class WafGroupsEnvelope(BaseModel):
    data: list[WafGroup]


class WafGroupEnvelope(BaseModel):
    data: WafGroup | None = None


class Action3(Enum):
    """
    The action to apply to WAF rule
    """

    block = "block"
    challenge = "challenge"
    monitor = "monitor"
    disable = "disable"
    default = "default"


class DefaultAction(Enum):
    """
    The action to apply to WAF rule
    """

    block = "block"
    challenge = "challenge"
    monitor = "monitor"
    disable = "disable"


class WafRule(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    ruleId: str | None = Field(None, examples=["892e67954025e0ba6atefd586b9e58b3"], pattern="^.*$")
    groupId: str | None = Field(None, examples=["372e67954025e0ba6aaa6d586b9e0b60"], max_length=100)
    action: Action3 = Field(..., description="The action to apply to WAF rule", examples=["block"])
    defaultAction: DefaultAction | None = Field(None, description="The action to apply to WAF rule", examples=["block"])
    description: str | None = Field(
        None,
        description="Description of the WAF Group.",
        examples=["Test WAF Rule to protect against SQL injection"],
        pattern="^.*$",
    )


class WafRulesEnvelope(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    data: list[WafRule]


class WafRuleEnvelope(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    data: WafRule


class BrotliCompression(Enum):
    """
    Brotli compression setting of a zone.
    """

    on = "on"
    off = "off"


class Http2Prioritization(Enum):
    """
    Http2 prioritization setting for a zone.
    """

    on = "on"
    off = "off"


class Webp(Enum):
    """
    Support for the WebP image format when using image modification for a zone. The WebP image format can be used with supported clients for added performance benefits. Setting this property to `on` will return an error when the `polish` property is set to `off`.
    """

    on = "on"
    off = "off"


class Polish(Enum):
    """
    The level of polish (image quality) used for image modification. The value `lossless` corresponds to **Polish Level Basic** in the UI, and the value `lossy` corresponds to **Polish Level Basic+JPEG.** To disable image modification, set this property to `off`. Setting this property to `off` will prevent you from setting the `webp` property to `on`.
    """

    off = "off"
    lossless = "lossless"
    lossy = "lossy"


class EarlyHints(Enum):
    """
    Early Hints for a zone.
    """

    on = "on"
    off = "off"


class Http3(Enum):
    """
    Http3 for a zone.
    """

    on = "on"
    off = "off"


class Http2ToOrigin(Enum):
    """
    Http2 to Origin for a zone.
    """

    on = "on"
    off = "off"


class SpeedSetting(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    brotliCompression: BrotliCompression | None = Field(
        "off", description="Brotli compression setting of a zone.", examples=["off"]
    )
    http2Prioritization: Http2Prioritization | None = Field(
        "off", description="Http2 prioritization setting for a zone.", examples=["off"]
    )
    webp: Webp | None = Field(
        "off",
        description="Support for the WebP image format when using image modification for a zone. The WebP image format can be used with supported clients for added performance benefits. Setting this property to `on` will return an error when the `polish` property is set to `off`.",
        examples=["off"],
    )
    polish: Polish | None = Field(
        "off",
        description="The level of polish (image quality) used for image modification. The value `lossless` corresponds to **Polish Level Basic** in the UI, and the value `lossy` corresponds to **Polish Level Basic+JPEG.** To disable image modification, set this property to `off`. Setting this property to `off` will prevent you from setting the `webp` property to `on`.",
        examples=["off"],
    )
    earlyHints: EarlyHints | None = Field("off", description="Early Hints for a zone.", examples=["off"])
    http3: Http3 | None = Field("off", description="Http3 for a zone.", examples=["off"])
    http2ToOrigin: Http2ToOrigin | None = Field("off", description="Http2 to Origin for a zone.", examples=["off"])


class SpeedSettingsEnvelope(BaseModel):
    data: SpeedSetting


class Hsts(BaseModel):
    """
    The security header for a zone.
    """

    model_config = ConfigDict(
        extra="forbid",
    )
    enabled: bool | None = Field(None, description="Enable strict transport security.", examples=[True])
    includeSubdomains: bool | None = Field(
        None, description="Include all subdomains for strict transport security.", examples=[True]
    )
    maxAge: float | None = Field(
        None, description="Max age in seconds of the strict transport security.", examples=[31536000]
    )
    preload: bool | None = Field(
        None, description="Preload any URLs that are included in the response headers.", examples=[False]
    )


class SecurityLevel(Enum):
    """
    Security profile for your zone, which will automatically adjust each of the security settings.
    """

    off = "off"
    essentially_off = "essentially_off"
    low = "low"
    medium = "medium"
    high = "high"
    under_attack = "under_attack"


class SecuritySetting(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    hsts: Hsts | None = Field(
        None,
        description="The security header for a zone.",
        examples=[{"enabled": True, "includeSubdomains": True, "maxAge": 31536000, "preload": False}],
    )
    securityLevel: SecurityLevel | None = Field(
        None,
        description="Security profile for your zone, which will automatically adjust each of the security settings.",
        examples=["medium"],
    )
    tls13Enabled: bool | None = Field(None, description="Enable Crypto TLS 1.3 feature for this zone.", examples=[True])
    wafEnabled: bool | None = Field(
        None,
        description="Enable WAF (OWASP) protection for this zone. Not applicable for zones using WAFv2.",
        examples=[True],
    )
    alwaysUseHttps: bool = Field(..., description="Redirect all http requests to https.", examples=[True])


class SecuritySettingsEnvelope(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    data: SecuritySetting


class Tag(RootModel[str]):
    root: str = Field(..., examples=["product-123"], pattern="^.*$")


class CachePurgeRequest(BaseModel):
    """
    Request for doing a cache purge
    """

    model_config = ConfigDict(
        extra="forbid",
    )
    path: str | None = Field(
        None,
        description='Path for clearing the cache. Allowed paths follow the format "<hostname>/dw/shop/*/products", "<hostname>/dw/image/v2/{realm}_{instance}/*", "<hostname>/worker.js", "<hostname>/mobify*" or "<hostname>/callback*". Regular expressions and wildcards are not supported in the path.',
        examples=["www.sfcc-ecdn-test5.net/dw/shop/v21_9/products"],
        pattern="^.*$",
    )
    tags: list[Tag] | None = Field(
        None,
        description="List of cache tags to purge. When specified, all cached content associated with these tags will be purged.",
        examples=[["product-123", "category-456"]],
    )


class CachePurgeResponse(BaseModel):
    """
    Response from a cache purge request
    """

    model_config = ConfigDict(
        extra="forbid",
    )
    cachePurged: bool = Field(..., description="The name of the list.", examples=[False])
    details: str = Field(
        ..., description="Details of errors if any.", examples=["1084 : Unable to purge '<url>'."], pattern="^.*$"
    )


class CachePurgeResponseEnvelope(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    data: CachePurgeResponse


class OCAPICachingToggleRequest(BaseModel):
    """
    Request to enable or disable API Caching Page rule
    """

    enableOCAPICachingPageRule: bool = Field(
        ..., description="True to enable API Caching Page rule, false to disable.", examples=[True]
    )


class DCVDelegationRecord(BaseModel):
    """
    eCDN automatic renewal certificate DCV delegation records.
    """

    model_config = ConfigDict(
        extra="forbid",
    )
    dcvCname: str | None = Field(
        None,
        description="DNS CNAME for Domain Control Validation.",
        examples=["_acme-challenge.example.com"],
        pattern="^.*$",
    )
    dcvCnameValue: str | None = Field(
        None,
        description="DNS CNAME value for Domain Control Validation.",
        examples=["abc123def456ghi789.acme-validation.com"],
        pattern="^.*$",
    )


class Host(RootModel[str]):
    root: str = Field(..., examples=["example.com"], pattern="^.*$")


class Status2(Enum):
    """
    Current status of the certificate.
    """

    ACTIVE = "ACTIVE"
    EXPIRED = "EXPIRED"
    DELETED = "DELETED"
    PENDING = "PENDING"
    INITIALIZING = "INITIALIZING"
    PENDING_VALIDATION = "PENDING_VALIDATION"
    PENDING_ISSUANCE = "PENDING_ISSUANCE"
    PENDING_DEPLOYMENT = "PENDING_DEPLOYMENT"
    PENDING_DELETION = "PENDING_DELETION"
    VALIDATION_TIMED_OUT = "VALIDATION_TIMED_OUT"
    DEPLOYMENT_TIMED_OUT = "DEPLOYMENT_TIMED_OUT"
    DELETION_TIMED_OUT = "DELETION_TIMED_OUT"
    INITIALIZING_TIMED_OUT = "INITIALIZING_TIMED_OUT"
    PENDING_EXPIRATION = "PENDING_EXPIRATION"
    ISSUANCE_TIMED_OUT = "ISSUANCE_TIMED_OUT"


class CertificateType(Enum):
    """
    Indicates certificate is custom cert uploaded by customer or automatic renewal certificate by eCDN.
    """

    custom = "custom"
    automatic = "automatic"
    custom_legacy = "custom_legacy"


class CertificateAuthority(Enum):
    """
    Indicates certificate issuer for automatic renewal certificate by eCDN.
    """

    google = "google"
    lets_encrypt = "lets_encrypt"
    digicert = "digicert"


class CertificateValidation(Enum):
    """
    Indicates certificate validation type for automatic renewal certificate by eCDN.
    """

    http = "http"
    txt = "txt"


class CertificateVerificationStatus(Enum):
    """
    Current status of certificate verification.
    """

    ACTIVE = "ACTIVE"
    EXPIRED = "EXPIRED"
    PENDING = "PENDING"
    INITIALIZING = "INITIALIZING"
    PENDING_VALIDATION = "PENDING_VALIDATION"
    PENDING_ISSUANCE = "PENDING_ISSUANCE"
    PENDING_DEPLOYMENT = "PENDING_DEPLOYMENT"


class WildcardCertificateVerificationStatus(Enum):
    """
    Current status of certificate verification.
    """

    ACTIVE = "ACTIVE"
    EXPIRED = "EXPIRED"
    PENDING = "PENDING"
    INITIALIZING = "INITIALIZING"
    PENDING_VALIDATION = "PENDING_VALIDATION"
    PENDING_ISSUANCE = "PENDING_ISSUANCE"
    PENDING_DEPLOYMENT = "PENDING_DEPLOYMENT"


class CustomHostnameStatus(Enum):
    """
    Current status of custom hostname validation.
    """

    ACTIVE = "ACTIVE"
    EXPIRED = "EXPIRED"
    DELETED = "DELETED"
    PENDING = "PENDING"
    INITIALIZING = "INITIALIZING"
    PENDING_VALIDATION = "PENDING_VALIDATION"
    PENDING_ISSUANCE = "PENDING_ISSUANCE"
    PENDING_DEPLOYMENT = "PENDING_DEPLOYMENT"
    PENDING_DELETION = "PENDING_DELETION"
    MOVED = "MOVED"


class Certificate(BaseModel):
    """
    The certificate information
    """

    model_config = ConfigDict(
        extra="forbid",
    )
    certificateId: str = Field(
        ...,
        description="Id generated by CDN provider for the certificate.",
        examples=["f90712123fb02287348dd34c0a282bb9"],
        pattern="^.*$",
    )
    hosts: list[Host] | None = Field(
        None, description="List of hosts the certificate applies to.", examples=[["example.com", "www.example.com"]]
    )
    expiresOn: AwareDatetime | None = Field(
        None, description="Date of expiration for the certificate.", examples=["2025-12-31T23:59:59Z"]
    )
    uploadedOn: AwareDatetime | None = Field(
        None, description="Date the certificate was uploaded.", examples=["2024-01-01T00:00:00Z"]
    )
    issuer: str | None = Field(
        None,
        description="The certificate authority that issued the certificate.",
        examples=["Let's Encrypt Authority X3"],
        pattern="^.*$",
    )
    signature: str | None = Field(
        None, description="The type of hash used for the certificate.", examples=["SHA256"], pattern="^.*$"
    )
    status: Status2 = Field(..., description="Current status of the certificate.", examples=["ACTIVE"])
    minTlsVersion: str | None = Field(
        None,
        description="Minimum TLS Version only allows HTTPS connections from visitors that support the selected TLS protocol version or newer.",
        examples=["1.2"],
        pattern="^.*$",
    )
    certificateType: CertificateType = Field(
        ...,
        description="Indicates certificate is custom cert uploaded by customer or automatic renewal certificate by eCDN.",
        examples=["custom"],
    )
    certificateAuthority: CertificateAuthority | None = Field(
        None,
        description="Indicates certificate issuer for automatic renewal certificate by eCDN.",
        examples=["lets_encrypt"],
    )
    certificateValidation: CertificateValidation | None = Field(
        None,
        description="Indicates certificate validation type for automatic renewal certificate by eCDN.",
        examples=["http"],
    )
    certificateVerificationTXTName: str | None = Field(
        None,
        description="eCDN automatic renewal certificate verification txt name.",
        examples=["_acme-challenge.example.com"],
        pattern="^.*$",
    )
    certificateVerificationTXTValue: str | None = Field(
        None,
        description="eCDN automatic renewal certificate verification txt value.",
        examples=["abc123def456ghi789"],
        pattern="^.*$",
    )
    certificateVerificationStatus: CertificateVerificationStatus | None = Field(
        None, description="Current status of certificate verification.", examples=["ACTIVE"]
    )
    wildcardHostname: bool | None = Field(
        None, description="Set to true for a wildcard custom hostname.", examples=[False]
    )
    wildcardCertificateVerificationTXTName: str | None = Field(
        None,
        description="eCDN automatic renewal certificate verification txt name.",
        examples=["_acme-challenge.wildcard.example.com"],
        pattern="^.*$",
    )
    wildcardCertificateVerificationTXTValue: str | None = Field(
        None,
        description="eCDN automatic renewal certificate verification txt value.",
        examples=["wildcard_abc123def456"],
        pattern="^.*$",
    )
    wildcardCertificateVerificationStatus: WildcardCertificateVerificationStatus | None = Field(
        None, description="Current status of certificate verification.", examples=["ACTIVE"]
    )
    customHostnameVerificationTXTName: str | None = Field(
        None,
        description="Custom Hostname verification txt name.",
        examples=["_acme-challenge.custom.example.com"],
        pattern="^.*$",
    )
    customHostnameVerificationTXTValue: str | None = Field(
        None, description="Custom Hostname verification txt value.", examples=["custom_abc123def456"], pattern="^.*$"
    )
    customHostnameId: str | None = Field(
        None,
        description="Custom hostname associated with the zone",
        examples=["f90712123fb02287348dd34c0a282bb9"],
        pattern="^.*$",
    )
    customHostname: str | None = Field(
        None, description="Custom hostname associated with the zone", examples=["custom.example.com"], pattern="^.*$"
    )
    customHostnameStatus: CustomHostnameStatus | None = Field(
        None, description="Current status of custom hostname validation.", examples=["ACTIVE"]
    )
    dcvDelegationRecords: list[DCVDelegationRecord] | None = Field(
        None, description="eCDN automatic renewal certificate DCV delegation records"
    )


class CertificatesEnvelope(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    data: list[Certificate]


class CertificateRequest(BaseModel):
    """
    Certificate request information
    """

    model_config = ConfigDict(
        extra="forbid",
    )
    hostname: str = Field(
        ..., description="Hostname that certificate needs to be applied to.", examples=["example.com"], pattern="^.*$"
    )
    bundleMethod: str | None = Field(
        None,
        description="Bundle method of the custom certificate chain for verification.",
        examples=["ubiquitous"],
        pattern="^.*$",
    )
    certificateType: str | None = Field(
        None,
        description="Indicates certificate is custom or automatic certificate renewal by eCDN. Optional field, if nothing specified the default value is custom. Valid values are custom or automatic.",
        examples=["custom"],
        pattern="^.*$",
    )
    certificate: str | None = Field(
        None,
        description="Public key of the custom certificate. Required if the certificateType value is custom.",
        examples=[
            "-----BEGIN CERTIFICATE-----\nMIIDtTCCAp2gAwIBAgIJAMHAwfXZ5PWMA0GCSqGSIb3DQEBCwUAMEUxCzAJBgNV\nBAYTAkFVMRMwEQYDVQQIEwpTb21lLVN0YXRlMSEwHwYDVQQKExhJbnRlcm5ldCBX\naWRnaXRzIFB0eSBMdGQwHhcNMTYwODI0MTY0MzAxWhcNMTYxMTIyMTY0MzAxWjBF\nMQswCQYDVQQGEwJBVTETMBEGA1UECBMKU29tZS1TdGF0ZTEhMB8GA1UEChMYSW50\nZXJuZXQgV2lkZ2l0cyBQdHkgTHRkMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIB\nCgKCAQEAwQHoetcl9+5ikGzV6cMzWtWPJHqXT3wpbEkRU9Yz7lgvddmGdtcGbg/1\nCGZu0jJGkMoppoUo4c3dts3iwqRYmBikUP77wwY2QGmDZw2FvkJCJlKnabIRuGvB\nKwzESIXgKk2016aTP6/dAjEHyo6SeoK8lkIySUvK0fyOVlsiEsCmOpidtnKX/a+5\n0GjB79CJH4ER2lLVZnhePFR/zUOyPxZQQ4naHf7yu/b5jhO0f8fwt+pyFxIXjbEI\ndZliWRkRMtzrHOJIhrmJ2A1J7iOrirbbwillwjjNVUWPf3IJ3M12S9pEewooaeO2\nizNTERcG9HzAacbVRn2Y2SWIyT/18QIDAQABo4GnMIGkMB0GA1UdDgQWBBT/LbE4\n9rWf288N6sJA5BRb6FJIGDB1BgNVHSMEbjBsgBT/LbE49rWf288N6sJA5BRb6FJI\nGKFJpEcwRTELMAkGA1UEBhMCQVUxEzARBgNVBAgTClNvbWUtU3RhdGUxITAfBgNV\nBAoTGEludGVybmV0IFdpZGdpdHMgUHR5IEx0ZIIJAMHAwfXZ5/PWMAwGA1UdEwQF\nMAMBAf8wDQYJKoZIhvcNAQELBQADggEBAHHFwl0tH0quUYZYO0dZYt4R7SJ0pCm2\n2satiyzHl4OnXcHDpekAo7/a09c6Lz6AU83cKy/+x3/djYHXWba7HpEu0dR3ugQP\nMlr4zrhd9xKZ0KZKiYmtJH+ak4OM4L3FbT0owUZPyjLSlhMtJVcoRp5CJsjAMBUG\nSvD8RX+T01wzox/Qb+lnnNnOlaWpqu8eoOenybxKp1a9ULzIVvN/LAcc+14vioFq\n2swRWtmocBAs8QR9n4uvbpiYvS8eYueDCWMM4fvFfBhaDZ3N9IbtySh3SpFdQDhw\nYbjM2rxXiyLGxB4Bol7QTv4zHif7Zt89FReT/NBy4rzaskDJY5L6xmY=\n-----END CERTIFICATE-----"
        ],
        pattern="^.*$",
    )
    privateKey: str | None = Field(
        None,
        description="Private key associated with the custom certificate. Required if the `certificateType` value is custom.",
        examples=[
            "-----BEGIN RSA PRIVATE KEY-----\nMIIEowIBAAKCAQEAwQHoetcl9+5ikGzV6cMzWtWPJHqXT3wpbEkRU9Yz7lgvddmG\ndtcGbg/1CGZu0jJGkMoppoUo4c3dts3iwqRYmBikUP77wwY2QGmDZw2FvkJCJlKn\nabIRuGvBKwzESIXgKk2016aTP6/dAjEHyo6SeoK8lkIySUvK0fyOVlsiEsCmOpid\ntnKX/a+50GjB79CJH4ER2lLVZnhePFR/zUOyPxZQQ4naHf7yu/b5jhO0f8fwt+py\nFxIXjbEIdZliWRkRMtzrHOJIhrmJ2A1J7iOrirbbwillwjjNVUWPf3IJ3M12S9pE\newooaeO2izNTERcG9HzAacbVRn2Y2SWIyT/18QIDAQABAoIBACbhTYXBZYKmYPCb\nHBR1IBlCQA2nLGf0qRuJNJZg5iEzXows/6tc8YymZkQE7nolapWsQ+upk2y5Xdp/\naxiuprIs9JzkYK8Ox0r+dlwCG1kSW+UAbX0bQ/qUqlsTvU6muVuMP8vZYHxJ3wmb\n+ufRBKztPTQ/rYWaYQcgC0RWI20HTFBMxlTAyNxYNWzX7RKFkGVVyB9RsAtmcc8g\n+j4OdosbfNoJPS0HeIfNpAznDfHKdxDk2Yc1tV6RHBrC1ynyLE9+TaflIAdo2MVv\nKLMLq51GqYKtgJFIlBRPQqKoyXdz3fGvXrTkf/WY9QNq0J1Vk5ERePZ54mN8iZB7\n9lwy/AkCgYEA6FXzosxswaJ2wQLeoYc7ceaweX/SwTvxHgXzRyJIIT0eJWgx13Wo\n/WA3Iziimsjf6qE+SI/8laxPp2A86VMaIt3Z3mJN/CqSVGw8LK2AQst+OwdPyDMu\niacE8lj/IFGC8mwNUAb9CzGU3JpU4PxxGFjS/eMtGeRXCWkK4NE+G08CgYEA1Kp9\nN2JrVlqUz+gAX+LPmE9OEMAS9WQSQsfCHGogIFDGGcNf7+uwBM7GAaSJIP01zcoe\nVAgWdzXCv3FLhsaZoJ6RyLOLay5phbu1iaTr4UNYm5WtYTzMzqh8l1+MFFDl9xDB\nvULuCIIrglM5MeS/qnSg1uMoH2oVPj9TVst/ir8CgYEAxrI7Ws9Zc4Bt70N1As+U\nlySjaEVZCMkqvHJ6TCuVZFfQoE0r0whdLdRLU2PsLFP+q7qaeZQqgBaNSKeVcDYR\n9B+nY/jOmQoPewPVsp/vQTCnE/R81spu0mp0YI6cIheT1Z9zAy322svcc43JaWB7\nmEbeqyLOP4Z4qSOcmghZBSECgYACvR9Xs0DGn+wCsW4vze/2ei77MD4OQvepPIFX\ndFZtlBy5ADcgE9z0cuVB6CiL8DbdK5kwY9pGNr8HUCI03iHkW6Zs+0L0YmihfEVe\nPG19PSzK9CaDdhD9KFZSbLyVFmWfxOt50H7YRTTiPMgjyFpfi5j2q348yVT0tEQS\nfhRqaQKBgAcWPokmJ7EbYQGeMbS7HC8eWO/RyamlnSffdCdSc7ue3zdVJxpAkQ8W\nqu80pEIF6raIQfAf8MXiiZ7auFOSnHQTXUbhCpvDLKi0Mwq3G8Pl07l+2s6dQG6T\nlv6XTQaMyf6n1yjzL+fzDrH3qXMxHMO/b13EePXpDMpY7HQpoLDi\n-----END RSA PRIVATE KEY-----"
        ],
        pattern="^.*$",
    )
    certificateAuthority: str | None = Field(
        None,
        description="Certificate authority only for automatic certificate renewal by eCDN. Required if the `certificateType` value is automatic. Valid values are `google` or `lets_encrypt`.",
        examples=["lets_encrypt"],
        pattern="^.*$",
    )
    certificateValidation: str | None = Field(
        None,
        description="Certificate validation type is optional only for `certificateType` automatic, default value is `http`. Valid values are `http` or `txt`.",
        examples=["http"],
        pattern="^.*$",
    )
    wildcardHostname: bool | None = Field(
        None, description="Set to true for a wildcard custom hostname.", examples=[False]
    )


class CertificateEnvelope(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    data: Certificate


class CustomHostnameStatus1(Enum):
    """
    Current status of the custom hostname.
    """

    PENDING = "PENDING"
    ACTIVE = "ACTIVE"
    MOVED = "MOVED"
    DELETED = "DELETED"


class CustomHostnameValidationResponse(BaseModel):
    """
    Custom hostname validation information.
    """

    model_config = ConfigDict(
        extra="forbid",
    )
    customHostnameId: str = Field(
        ...,
        description="Identifier generated by the CDN provider for the custom hostname.",
        examples=["a439eb1f-5e71-4544-bb29-54d18ax62277"],
        pattern="^.*$",
    )
    customHostname: str = Field(
        ..., description="Name of the custom hostname", examples=["test.example.com"], pattern="^.*$"
    )
    customHostnameVerificationTXTName: str = Field(
        ...,
        description="Custom hostname verification txt name.",
        examples=["_acme-challenge.test.example.com"],
        pattern="^.*$",
    )
    customHostnameVerificationTXTValue: str = Field(
        ...,
        description="Custom hostname verification txt value.",
        examples=["DBCtxdyQSyo9eXxys-uGVCwPFHLsc8_lu11QetQz4IA"],
        pattern="^.*$",
    )
    customHostnameStatus: CustomHostnameStatus1 = Field(
        ..., description="Current status of the custom hostname.", examples=["ACTIVE"]
    )


class CustomHostnameValidationEnvelope(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    data: CustomHostnameValidationResponse


class MRTRules(BaseModel):
    """
    A rule in an MRT ruleset.
    """

    model_config = ConfigDict(
        extra="forbid",
    )
    id: str = Field(..., description="The ID of the rule.", examples=["12345678901234asdfasfasdf"], pattern="^.*$")
    expression: str = Field(
        ...,
        description="The expression that determines the rule's routing behavior.",
        examples=[
            '(http.host eq "dev-customer.salesforce.com" and not ( http.request.uri.path matches "^/path1/.*" or http.request.uri.path matches "^.*/path2/.*/products/.*"))'
        ],
        pattern="^.*$",
    )
    description: str | None = Field(
        None,
        description="The description of the rule.",
        examples=["Phased rollout rule for dev-customer.salesforce.com"],
        pattern="^.*$",
    )
    lastUpdated: AwareDatetime = Field(
        ..., description="Date when the rule was last updated.", examples=["2022-01-01T05:20:00Z"]
    )
    ref: str = Field(
        ..., description="The ref of the rule.", examples=["12345678901234asdfasfasdf1234567"], pattern="^.*$"
    )
    enabled: bool = Field(..., description="Whether or not the rule is enabled.", examples=[True])
    mrtHostname: str = Field(
        ...,
        description="Managed runtime hostname this rule targets.",
        examples=["customer-pwa-hybrid.mobify-storefront.com"],
        pattern="^.*$",
    )


class MRTRuleset(BaseModel):
    """
    An MRT ruleset. Defines a list of MRT rules that will route certain storefront requests to the managed runtime instance.
    """

    model_config = ConfigDict(
        extra="forbid",
    )
    id: str = Field(..., description="The ID of the ruleset.", examples=["12345678901234asdfasfasdf"], pattern="^.*$")
    name: str = Field(..., description="The name of the ruleset.", examples=["MRT Rules"], pattern="^.*$")
    lastUpdated: AwareDatetime = Field(
        ..., description="Date when the ruleset was last updated.", examples=["2022-01-01T05:20:00Z"]
    )
    rules: list[MRTRules] = Field(..., description="The rules defined by the ruleset.")


class MRTRulesResponse(BaseModel):
    """
    Response for MRT rules. MRT rules are a way to route certain storefront requests to the managed runtime instance.
    """

    model_config = ConfigDict(
        extra="forbid",
    )
    ruleset: MRTRuleset


class MRTRulesResponseEnvelope(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    data: MRTRulesResponse


class Expression(RootModel[str]):
    root: str = Field(
        ...,
        examples=[
            '(http.host eq "dev-customer.salesforce.com" and not ( http.request.uri.path matches "^/path1/.*" or http.request.uri.path matches "^.*/path2/.*/products/.*"))'
        ],
        pattern="^.*$",
    )


class Description(RootModel[str]):
    root: str = Field(..., examples=["Phased rollout rule for dev-customer.salesforce.com"], pattern="^.*$")


class MRTRulesPostRequest(BaseModel):
    """
    POST request for creating MRT rules. MRT rules are a way to route certain storefront requests to the managed runtime instance.
    """

    model_config = ConfigDict(
        extra="forbid",
    )
    mrtHostname: str = Field(
        ...,
        description="The customer's MRT instance hostname.",
        examples=["customer-react-project-production.mobify-storefront.com"],
        pattern="^.*$",
    )
    expressions: list[Expression] = Field(
        ...,
        description="An array containing the expressions for each MRT rule.",
        examples=[
            [
                '(http.host eq "dev-customer.salesforce.com" and not ( http.request.uri.path matches "^/path1/.*" or http.request.uri.path matches "^.*/path2/.*/products/.*"))'
            ]
        ],
    )
    descriptions: list[Description] | None = Field(
        None,
        description="An array containing the descriptions for each MRT rule. The number of descriptions provided must match the number of expressions provided. Optional.",
        examples=[["Phased rollout rule for dev-customer.salesforce.com"]],
    )


class MRTRulesetPatchRequest(BaseModel):
    """
    PATCH request for updating the MRT environment hostname or adding MRT rules to route to an existing MRT environment.
    """

    model_config = ConfigDict(
        extra="forbid",
    )
    oldMrtHostname: str | None = Field(
        None,
        description="The customer's current MRT instance hostname.",
        examples=["customer-react-projec-production.mobify-storefront.com"],
        pattern="^.*$",
    )
    mrtHostname: str = Field(
        ...,
        description="The customer's MRT instance hostname.",
        examples=["customer-react-projec-production.mobify-storefront.com"],
        pattern="^.*$",
    )
    expressions: list[Expression] | None = Field(
        None,
        description="An array containing the expressions for each MRT rule.",
        examples=[
            [
                '(http.host eq "dev-customer.salesforce.com" and not ( http.request.uri.path matches "^/path1/.*" or http.request.uri.path matches "^.*/path2/.*/products/.*"))'
            ]
        ],
    )
    descriptions: list[Description] | None = Field(
        None,
        description="An array containing the descriptions for each MRT rule. The number of descriptions provided must match the number of expressions provided. Optional.",
        examples=[["Phased rollout rule for dev-customer.salesforce.com"]],
    )


class MRTRulePatchRequest(BaseModel):
    """
    PATCH request for updating an MRT rule. You may use the PATCH request to update the rule's expression and description as well as disable/enable the rule.
    """

    model_config = ConfigDict(
        extra="forbid",
    )
    enabled: bool | None = Field(None, description="Whether or not the rule is enabled.", examples=[True])
    expression: str | None = Field(
        None,
        description="The expression that determines the MRT rule's routing behavior.",
        examples=[
            '(http.host eq "dev-customer.salesforce.com" and not ( http.request.uri.path matches "^/path1/.*" or http.request.uri.path matches "^.*/path2/.*/products/.*"))'
        ],
        pattern="^.*$",
    )
    description: str | None = Field(
        None,
        description="The description of the rule. Optional.",
        examples=["Phased rollout rule for dev-customer.salesforce.com"],
        pattern="^.*$",
    )


class LogpushOwnershipPostRequest(BaseModel):
    """
    POST request for creating new Logpush Ownership.
    """

    model_config = ConfigDict(
        extra="forbid",
    )
    destinationPath: str = Field(
        ...,
        description="Uniquely identifies a resource (such as an s3 bucket) where data will be pushed. Additional configuration parameters supported by the destination may be included. You can use the special string {DATE} in the URL path to separate logs into daily subdirectories; for example s3://customer-bucket/logs/{DATE}?region=us-east-1&sse=AES256. The name of the directory will be replaced with the date in YYYYMMDD format (e.g. 20220215) when the logs are stored.",
        examples=["s3://customer-bucket/site-name/{DATE}?region=us-east-1&sse=AES256"],
        pattern="^.*$",
    )


class Data(BaseModel):
    """
    The customer's new Logpush Ownership.
    """

    destinationPath: str = Field(
        ...,
        description="Destination where logs will be sent (S3 bucket only).",
        examples=["s3://customer-bucket/site-name/{DATE}?region=us-east-1&sse=AES256"],
        pattern="^.*$",
    )
    fileName: str = Field(
        ...,
        description="File path where the ownership challenge file is written.",
        examples=["site-name/20230101/ownership-challenge-d12345678.txt"],
        pattern="^.*$",
    )


class LogpushOwnershipPostResponse(BaseModel):
    """
    POST response for created new Logpush Ownership.
    """

    model_config = ConfigDict(
        extra="forbid",
    )
    data: Data = Field(..., description="The customer's new Logpush Ownership.")


class LogType(Enum):
    """
    Type of logs; available log types are `http_requests`, `firewall_events`, and `page_shield_events`.
    """

    http_requests = "http_requests"
    firewall_events = "firewall_events"
    page_shield_events = "page_shield_events"


class LogField(RootModel[str]):
    root: str = Field(..., examples=["ClientRequestBytes"], pattern="^.*$")


class LogpushResponse(BaseModel):
    """
    Logpush job response
    """

    model_config = ConfigDict(
        extra="forbid",
    )
    jobId: int | None = Field(None, description="Unique ID of the job.", examples=[123456])
    name: str | None = Field(
        None,
        description="Logpush job name; the name cannot be changed after the job is created.",
        examples=["my-logpush-job"],
        pattern="^.*$",
    )
    logType: LogType | None = Field(
        None,
        description="Type of logs; available log types are `http_requests`, `firewall_events`, and `page_shield_events`.",
        examples=["http_requests"],
    )
    filter: str | None = Field(
        None,
        description="Filter provides a way to customize which logs you want to receive. Filters are added as escaped JSON strings formatted. If the filter is not displayed, it indicates that all logs should be included.",
        examples=['{"where":{"key":"ClientRequestPath","operator":"contains","value":"/example-path"}}'],
        pattern="^.*$",
    )
    logFields: list[LogField] | None = Field(
        None,
        description="List of log fields. Depending on the type of log, the list of fields that you would like to see in the logs may vary.",
        examples=[["ClientRequestBytes", "ClientRequestHost", "ClientRequestMethod"]],
    )
    destinationPath: str | None = Field(
        None,
        description="Uniquely identifies s3 bucket for logs.",
        examples=["s3://customer-bucket/site-name/{DATE}?region=us-east-1&sse=AES256"],
        pattern="^.*$",
    )
    enabled: bool | None = Field(
        None, description="Flag that indicates if the job is enabled or disabled.", examples=[False]
    )
    lastComplete: AwareDatetime | None = Field(
        None,
        description="The last time that the log has been successfully transmitted to the destination.",
        examples=["2023-01-02T00:00:00Z"],
    )
    lastError: AwareDatetime | None = Field(
        None,
        description="The last time the job failed. If empty, the job has either never failed or has run successfully at least once since the last failure.",
        examples=["2023-01-01T10:00:00Z"],
    )
    errorMessage: str | None = Field(
        None,
        description="Provide details for the last failure message. If this field is empty, it indicates that the job successfully transmitted logs to the destination.",
        examples=["No permissions to write to destination bucket"],
        pattern="^.*$",
    )
    createdOn: AwareDatetime | None = Field(None, description="Job creation time.", examples=["2023-01-01T00:00:27Z"])


class LogpushJobsEnvelope(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    data: list[LogpushResponse]


class LogType1(Enum):
    """
    Type of logs. Available log types are `http_requests`, `firewall_events`, and `page_shield_events`.
    """

    http_requests = "http_requests"
    firewall_events = "firewall_events"
    page_shield_events = "page_shield_events"


class LogpushCreateRequest(BaseModel):
    """
    Request for create Logpush job.
    """

    model_config = ConfigDict(
        extra="forbid",
    )
    destinationPath: str = Field(
        ...,
        description="Uniquely identifies s3 bucket for logs. Additional configuration parameters like region can be included. The string {DATE} in the URL path to separate logs into daily subdirectories; for example `s3://customer-bucket/logs/{DATE}?region=us-east-1&sse=AES256` The name of the directory will be replaced with the date in YYYYMMDD format (e.g. 20220215) when the logs are stored.",
        examples=["s3://customer-bucket/site-name/{DATE}?region=us-east-1&sse=AES256"],
        pattern="^.*$",
    )
    name: str = Field(
        ...,
        description="Logpush job name; the name cannot be changed after the job is created.",
        examples=["my-logpush-job"],
        pattern="^.*$",
    )
    filter: str | None = Field(
        None,
        description="Filter provides a way to customize which logs you want to receive. Filters are added as escaped JSON strings formatted. Default will include all logs.",
        examples=['{"where":{"key":"ClientRequestPath","operator":"contains","value":"/example-path"}}'],
        pattern="^.*$",
    )
    logFields: list[LogField] = Field(
        ...,
        description="List of log fields. Depending on the type of log, the list of fields that you would like to see in the logs may vary.",
        examples=[["ClientRequestBytes", "ClientRequestHost", "ClientRequestMethod"]],
    )
    ownershipChallengeToken: str | None = Field(
        None,
        description="Ownership token to proves the ownership of the destinationPath.",
        examples=["abc00000000000000000000"],
        pattern="^.*$",
    )
    logType: LogType1 = Field(
        ...,
        description="Type of logs. Available log types are `http_requests`, `firewall_events`, and `page_shield_events`.",
        examples=["http_requests"],
    )


class LogpushEnvelope(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    data: LogpushResponse


class LogpushUpdateRequest(BaseModel):
    """
    Request for update Logpush job
    """

    model_config = ConfigDict(
        extra="forbid",
    )
    enabled: bool | None = Field(
        None, description="Flag that indicates if the job is enabled or disabled.", examples=[True]
    )
    filter: str | None = Field(
        None,
        description="Provides customized selection for logs you want to receive. Filters are added as escaped, formatted JSON strings. By default, all logs are included.",
        examples=['{"where":{"key":"ClientRequestPath","operator":"contains","value":"/example-path"}}'],
        pattern="^.*$",
    )
    logFields: list[LogField] | None = Field(
        None,
        description="List of log fields. Depending on the log type, the list of fields that you can specify to be displayed in the log might vary.",
        examples=[["ClientRequestBytes", "ClientRequestHost", "ClientRequestMethod"]],
    )


class Sensitivity(Enum):
    """
    Sensitivity for traditional (owasp) rule package.
    """

    low = "low"
    medium = "medium"
    high = "high"
    off = "off"


class ActionMode(Enum):
    """
    The default action that is taken for rules under traditional(owasp) firewall package.
    """

    simulate = "simulate"
    challenge = "challenge"
    block = "block"


class WAFRulePackage(BaseModel):
    id: str = Field(..., examples=["a25a9a7e9c00afc1fb2e0245519d725b"], max_length=32)
    name: str = Field(
        ..., description="Name of the firewall package", examples=["OWASP Top 10 Protection"], pattern="^.*$"
    )
    description: str = Field(
        ...,
        description="Summary of purpose/function of firewall package",
        examples=["Protection against OWASP Top 10 vulnerabilities"],
        pattern="^.*$",
    )
    detection_mode: str = Field(
        ...,
        description="How the rules within the package are evaluated during the course of a request. When a package uses anomaly detection, each rule is given a score when triggered. If the total score of all triggered rules exceeds the sensitivity defined on the package, the action defined on the package is taken. Traditional detection decides which action to take when it is triggered by the request. If multiple rules are triggered, the action with highest protection is used. For example, a block action beats a challenge.",
        examples=["traditional"],
        pattern="^.*$",
    )
    zone_id: str = Field(
        ...,
        description="Zone identifier with which this rule package is associated.",
        examples=["zone_1234567890abcdef"],
        pattern="^.*$",
    )
    sensitivity: Sensitivity = Field(
        ..., description="Sensitivity for traditional (owasp) rule package.", examples=["medium"]
    )
    action_mode: ActionMode = Field(
        ...,
        description="The default action that is taken for rules under traditional(owasp) firewall package.",
        examples=["block"],
    )


class WAFRulePackageEnvelope(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    data: WAFRulePackage


class WafPackagePatchRequest(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    sensitivity: Sensitivity = Field(
        ..., description="Sensitivity for traditional (owasp) rule package.", examples=["medium"]
    )
    action_mode: ActionMode = Field(
        ...,
        description="The default action that is taken for rules under traditional(owasp) firewall package.",
        examples=["block"],
    )


class Action4(RootModel[str]):
    root: str = Field(..., examples=["block"], pattern="^.*$")


class CustomRule(BaseModel):
    """
    A custom rule.
    """

    ruleId: str = Field(
        ..., description="The ID of the custom rule.", examples=["2c0fc9fa937b11eaa1b71c4d701ab86e"], pattern="^.*$"
    )
    description: str = Field(
        ...,
        description="The description of the custom rule.",
        examples=["Block traffic for malformed URL requests."],
        pattern="^.*$",
    )
    expression: str = Field(
        ...,
        description="The expression that determines the custom rule's behavior.",
        examples=['(http.request.uri.path matches \\"^/path1/.*\\")'],
        pattern="^.*$",
    )
    actions: list[Action4] = Field(..., description="The action(s) applied by the custom rule.", examples=[["block"]])
    lastUpdated: AwareDatetime = Field(
        ..., description="Date when the custom rule was last updated.", examples=["2022-01-01T05:20:00Z"]
    )
    enabled: bool = Field(..., description="Whether or not the custom rule is enabled.", examples=[True])


class CustomRulesEnvelope(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    data: list[CustomRule]


class RulePosition(BaseModel):
    """
    Used to specify the position of a rule.
    """

    before: str | None = Field(
        None,
        description="Insert the current rule before this ruleId.",
        examples=["2c0fc9fa937b11eaa1b71c4d701ab86e"],
        pattern="^.*$",
    )
    after: str | None = Field(
        None,
        description="Insert the current rule after this ruleId.",
        examples=["2c0fc9fa937b11eaa1b71c4d701ab86e"],
        pattern="^.*$",
    )


class CustomRulesPostRequest(BaseModel):
    """
    Create a custom rule.
    """

    description: str = Field(
        ...,
        description="A description of the custom rule.",
        examples=["Block traffic for malformed URL requests"],
        pattern="^.*$",
    )
    expression: str = Field(
        ...,
        description="The expression that determines the custom rule's behavior.",
        examples=['(http.request.uri.path matches \\"^/path1/.*\\")'],
        pattern="^.*$",
    )
    actions: list[Action4] = Field(..., description="The action(s) applied by the custom rule.", examples=[["block"]])
    enabled: bool | None = Field(None, description="Whether or not the custom rule is enabled.", examples=[True])
    position: RulePosition | None = None


class CustomRuleEnvelope(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    data: CustomRule


class RuleId(RootModel[str]):
    root: str = Field(..., examples=["ffffe61cf25e4ec49c34b029ff3060f7"], pattern="^.*$")


class CustomRulesPatchOrderRequest(BaseModel):
    """
    Update the order of all existing custom rules.
    """

    ruleIds: list[RuleId] = Field(
        ...,
        description="An array of ruleIds representing the new order of custom rules.",
        examples=[["ffffe61cf25e4ec49c34b029ff3060f7", "2c0fc9fa937b11eaa1b71c4d701ab86e"]],
    )


class CustomRulesPatchRequest(BaseModel):
    """
    Update a custom rule.
    """

    description: str | None = Field(
        None,
        description="A description of the custom rule.",
        examples=["Block traffic for malformed URL requests"],
        pattern="^.*$",
    )
    expression: str | None = Field(
        None,
        description="The expression that determines the custom rule's behavior.",
        examples=['(http.request.uri.path matches \\"^/path1/.*\\")'],
        pattern="^.*$",
    )
    actions: list[Action4] | None = Field(
        None, description="The action(s) applied by the custom rule.", examples=[["block"]]
    )
    enabled: bool | None = Field(None, description="Whether or not the custom rule is enabled.", examples=[True])
    position: RulePosition | None = None


class Characteristic(RootModel[str]):
    root: str = Field(..., examples=["cf.unique_visitor_id"], pattern="^.*$")


class RateLimitingRule(BaseModel):
    """
    A rate limiting rule.
    """

    ruleId: str = Field(
        ...,
        description="The ID of the rate limiting rule.",
        examples=["2c0fc9fa937b11eaa1b71c4d701ab86e"],
        pattern="^.*$",
    )
    description: str = Field(
        ..., description="The description of the rate limiting rule.", examples=["Rate limit /path1."], pattern="^.*$"
    )
    expression: str = Field(
        ...,
        description="The expression that defines when to evaluate the rate limiting rule.",
        examples=['(http.request.uri.path matches "^/path1/.*")'],
        pattern="^.*$",
    )
    characteristics: list[Characteristic] = Field(
        ...,
        description="Set of parameters defining how to group requests when tracking the request rate.",
        examples=[["cf.unique_visitor_id"]],
    )
    action: str = Field(
        ...,
        description='The action applied by the rate limiting rule. Valid actions are "block", "managed_challenge", "js_challenge", "legacy_captcha", and "log".',
        examples=["block"],
        pattern="^.*$",
    )
    period: int = Field(
        ...,
        description="The period of time to consider when evaluating the request rate (in seconds). Valid values are 10, 60, 120, 300, and 600.",
        examples=[60],
    )
    requestsPerPeriod: int = Field(
        ..., description="The limit for the number of requests in the specified period of time.", examples=[50]
    )
    mitigationTimeout: int = Field(
        ...,
        description="After the rate is reached, the rate limiting rule applies the rule action to further requests for the period of time defined in this field (in seconds). When set to 0, the rule throttles requests over the maximum configured rate. When greater than 0, the action is presented for the selected duration after the configured rate is exceeded. Valid values are 0, 60, 120, 300, 600, 3600, and 86400.",
        examples=[600],
    )
    countingExpression: str | None = Field(
        None,
        description="The expression that defines what kind of requests we want to rate limit.",
        examples=['(http.request.uri.path matches "^/path1/.*" and http.response.code eq 400)'],
        pattern="^.*$",
    )
    lastUpdated: AwareDatetime = Field(
        ..., description="Date when the rate limiting rule was last updated.", examples=["2022-01-01T05:20:00Z"]
    )
    enabled: bool = Field(..., description="Whether or not the rate limiting rule is enabled.", examples=[True])


class RateLimitingRulesEnvelope(BaseModel):
    data: list[RateLimitingRule]


class RateLimitingRulesPostRequest(BaseModel):
    """
    Create a rate limiting rule.
    """

    description: str = Field(
        ..., description="The description of the rate limiting rule.", examples=["Rate limit /path1."], pattern="^.*$"
    )
    expression: str = Field(
        ...,
        description="The expression that defines when to evaluate the rate limiting rule.",
        examples=['(http.request.uri.path matches "^/path1/.*")'],
        pattern="^.*$",
    )
    characteristics: list[Characteristic] = Field(
        ...,
        description="Set of parameters defining how to group requests when tracking the request rate.",
        examples=[["cf.unique_visitor_id"]],
    )
    action: str = Field(
        ...,
        description='The action applied by the rate limiting rule. Valid actions are "block", "managed_challenge", "js_challenge", "legacy_captcha", and "log".',
        examples=["block"],
        pattern="^.*$",
    )
    period: int = Field(
        ...,
        description="The period of time to consider when evaluating the request rate (in seconds). Valid values are 10, 60, 120, 300, and 600.",
        examples=[60],
    )
    requestsPerPeriod: int = Field(
        ..., description="The limit for the number of requests in the specified period of time.", examples=[50]
    )
    mitigationTimeout: int = Field(
        ...,
        description="After the rate is reached, the rate limiting rule applies the rule action to further requests for the period of time defined in this field (in seconds). When set to 0, the rule throttles requests over the maximum configured rate. When greater than 0, the action is presented for the selected duration after the configured rate is exceeded. Valid values are 0, 60, 120, 300, 600, 3600, and 86400.",
        examples=[600],
    )
    countingExpression: str | None = Field(
        None,
        description="The expression that defines what kind of requests we want to rate limit.",
        examples=['(http.request.uri.path matches "^/path1/.*" and http.response.code eq 400)'],
        pattern="^.*$",
    )
    enabled: bool | None = Field(None, description="Whether or not the rate limiting rule is enabled.", examples=[True])
    position: RulePosition | None = None


class RateLimitingRuleEnvelope(BaseModel):
    data: RateLimitingRule


class RateLimitingRulesPatchRequest(BaseModel):
    """
    Update a rate limiting rule.
    """

    description: str | None = Field(
        None, description="The description of the rate limiting rule.", examples=["Rate limit /path1."], pattern="^.*$"
    )
    expression: str | None = Field(
        None,
        description="The expression that defines when to evaluate the rate limiting rule.",
        examples=['(http.request.uri.path matches "^/path1/.*")'],
        pattern="^.*$",
    )
    characteristics: list[Characteristic] | None = Field(
        None,
        description="Set of parameters defining how to group requests when tracking the request rate.",
        examples=[["cf.unique_visitor_id"]],
    )
    action: str | None = Field(
        None,
        description='The action applied by the rate limiting rule. Valid actions are "block", "managed_challenge", "js_challenge", "legacy_captcha", and "log".',
        examples=["block"],
        pattern="^.*$",
    )
    period: int | None = Field(
        None,
        description="The period of time to consider when evaluating the request rate (in seconds). Valid values are 10, 60, 120, 300, and 600.",
        examples=[60],
    )
    requestsPerPeriod: int | None = Field(
        None, description="The limit for the number of requests in the specified period of time.", examples=[50]
    )
    mitigationTimeout: int | None = Field(
        None,
        description="After the rate is reached, the rate limiting rule applies the rule action to further requests for the period of time defined in this field (in seconds). When set to 0, the rule throttles requests over the maximum configured rate. When greater than 0, the action is presented for the selected duration after the configured rate is exceeded. Valid values are 0, 60, 120, 300, 600, 3600, and 86400.",
        examples=[600],
    )
    countingExpression: str | None = Field(
        None,
        description="The expression that defines what kind of requests we want to rate limit.",
        examples=['(http.request.uri.path matches "^/path1/.*" and http.response.code eq 400)'],
        pattern="^.*$",
    )
    enabled: bool | None = Field(None, description="Whether or not the rate limiting rule is enabled.", examples=[True])
    position: RulePosition | None = None


class WAFManagedRuleset(BaseModel):
    """
    A WAF managed ruleset.
    """

    model_config = ConfigDict(
        extra="forbid",
    )
    name: str = Field(
        ..., description="The name of the WAF managed ruleset.", examples=["OWASP Core Ruleset"], pattern="^.*$"
    )
    rulesetId: str = Field(
        ...,
        description="The ID of the WAF managed ruleset.",
        examples=["4814384a9e5d4991b9815dcfc25d2f1f"],
        pattern="^.*$",
    )
    action: str = Field(
        ..., description="The action applied by the WAF managed ruleset.", examples=["default"], pattern="^.*$"
    )
    anomalyScore: str | None = Field(
        None,
        description="The anomaly score threshold of the WAF managed ruleset. Only applicable for the OWASP Core Ruleset.",
        examples=["low"],
        pattern="^.*$",
    )
    anomalyScoreThreshold: int | None = Field(
        None,
        description="The numerical value of the anomaly score threshold of the WAF managed ruleset. Only applicable for the OWASP Core Ruleset.",
        examples=[60],
    )
    paranoiaLevel: int | None = Field(
        None,
        description="The paranoia level of the WAF managed ruleset. Higher paranoia levels activate more aggressive rules. Only applicable for the OWASP Core Ruleset.",
        examples=[1],
    )
    enabled: bool = Field(..., description="Whether or not the WAF managed ruleset is enabled.", examples=[True])


class WAFManagedRulesetsEnvelope(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    data: list[WAFManagedRuleset]


class WAFManagedRulesetRequest(BaseModel):
    """
    A WAF managed ruleset request body.
    """

    model_config = ConfigDict(
        extra="forbid",
    )
    action: str | None = Field(
        None, description="The action applied by the WAF managed ruleset.", examples=["default"], pattern="^.*$"
    )
    anomalyScore: str | None = Field(
        None,
        description="The anomaly score threshold of the WAF managed ruleset. Only applicable for the OWASP Core Ruleset.",
        examples=["low"],
        pattern="^.*$",
    )
    paranoiaLevel: int | None = Field(
        None,
        description="The paranoia level of the WAF managed ruleset. Higher paranoia levels activate more aggressive rules. Only applicable for the OWASP Core Ruleset.",
        examples=[1],
    )
    enabled: bool | None = Field(
        None, description="Whether or not the WAF managed ruleset is enabled.", examples=[True]
    )


class WAFManagedRulesetEnvelope(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    data: WAFManagedRuleset


class Category(RootModel[str]):
    root: str = Field(..., examples=["broken-access-control"], pattern="^.*$")


class WAFManagedRule(BaseModel):
    """
    A WAF managed rule.
    """

    model_config = ConfigDict(
        extra="forbid",
    )
    ruleId: str = Field(
        ...,
        description="The ID of the WAF managed rule.",
        examples=["5de7edfa648c4d6891dc3e7f84534ffa"],
        pattern="^.*$",
    )
    action: str = Field(
        ..., description="The action applied by the WAF managed rule.", examples=["block"], pattern="^.*$"
    )
    score: int | None = Field(
        None,
        description="The score of the WAF managed rule. Only applicable for the OWASP Managed Ruleset.",
        examples=[5],
    )
    categories: list[Category] = Field(
        ...,
        description="A list of categories describing the function of the WAF managed rule.",
        examples=[["broken-access-control", "wordpress"]],
    )
    description: str = Field(
        ...,
        description="The description of the WAF managed rule.",
        examples=["Wordpress - Broken Access Control"],
        pattern="^.*$",
    )
    lastUpdated: AwareDatetime = Field(
        ..., description="Date when the WAF managed rule was last updated.", examples=["2024-01-01T05:20:00Z"]
    )
    enabled: bool = Field(..., description="Whether or not the WAF managed rule is enabled.", examples=[True])


class WAFManagedRulesEnvelope(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    data: list[WAFManagedRule]


class WAFManagedRuleRequest(BaseModel):
    """
    A PATCH request for updating a WAF managed rule.
    """

    model_config = ConfigDict(
        extra="forbid",
    )
    action: str | None = Field(
        None, description="The action applied by the WAF managed rule.", examples=["block"], pattern="^.*$"
    )
    enabled: bool | None = Field(None, description="Whether or not the WAF managed rule is enabled.", examples=[True])


class WAFManagedRuleEnvelope(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    data: WAFManagedRule


class OriginHeaderModification(BaseModel):
    """
    An origin header modification rule.
    """

    headerName: str = Field(
        ...,
        description="The name of the header forwarded to the origin.",
        examples=["x-sfdc-access-control"],
        pattern="^.*$",
    )
    headerValue: str = Field(
        ...,
        description="The masked value of the header forwarded to the origin.",
        examples=["****************789"],
        pattern="^.*$",
    )
    lastUpdated: AwareDatetime = Field(
        ..., description="Date when the rule was last updated.", examples=["2022-01-01T05:20:00Z"]
    )


class OriginHeaderModificationEnvelope(BaseModel):
    data: OriginHeaderModification


class OriginHeaderModificationPutRequest(BaseModel):
    """
    Put request for creating/updating the origin header modification.
    """

    headerValue: str = Field(
        ..., description="The value of the header forwarded to the origin.", examples=["123456789"], pattern="^.*$"
    )
    headerName: str | None = Field(
        None,
        description="The name of the header forwarded to the origin. Cannot be modified for the MRT origin.",
        examples=["x-sfdc-access-control"],
        pattern="^.*$",
    )


class Cipher(RootModel[str]):
    root: str = Field(..., examples=["ECDHE-ECDSA-AES128-GCM-SHA256"], pattern="^.*$")


class CipherSuiteType(Enum):
    """
    Classification of the ciphers in the suite.
    """

    Compatible = "Compatible"
    Modern = "Modern"
    Custom = "Custom"
    Legacy = "Legacy"


class CipherSuitesResponse(BaseModel):
    """
    Cipher suites information.
    """

    model_config = ConfigDict(
        extra="forbid",
    )
    ciphers: list[Cipher] = Field(
        ...,
        description="List of zone level ciphers in the suite.",
        examples=[["ECDHE-ECDSA-AES128-GCM-SHA256", "ECDHE-RSA-AES128-GCM-SHA256"]],
    )
    cipherSuiteType: CipherSuiteType = Field(
        ..., description="Classification of the ciphers in the suite.", examples=["Modern"]
    )


class CipherSuitesEnvelope(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    data: CipherSuitesResponse


class CipherSuiteType1(Enum):
    """
    Classification of all ciphers in the suite.
    """

    Compatible = "Compatible"
    Modern = "Modern"
    Custom = "Custom"
    Legacy = "Legacy"


class CipherSuitesRequest(BaseModel):
    """
    Cipher suites information.
    """

    model_config = ConfigDict(
        extra="forbid",
    )
    ciphers: list[Cipher] | None = Field(
        None,
        description="List of zone level ciphers in the suite.",
        examples=[["ECDHE-ECDSA-AES128-GCM-SHA256", "ECDHE-RSA-AES128-GCM-SHA256"]],
    )
    cipherSuiteType: CipherSuiteType1 = Field(
        ..., description="Classification of all ciphers in the suite.", examples=["Modern"]
    )
