# Copyright (c) 2025, Salesforce, Inc.
# SPDX-License-Identifier: Apache-2.0
# For full license text, see the LICENSE file in the repo root or http://www.apache.org/licenses/LICENSE-2.0
"""Generate the Python SDK API reference as VitePress Markdown.

Python analog of the docs site's ``docs:api`` (TypeDoc) step. Source docstrings are
read statically with ``griffe`` (the package is never imported) and rendered to one
Markdown page per public barrel module under ``docs/python/api/``, plus a
``sidebar.json`` consumed by ``docs/.vitepress/config.mts``.

The output is committed so the docs build does not need a Python toolchain; the
Python SDK CI job runs ``--check`` to fail when the committed pages are stale.

Usage::

    python scripts/generate_api_docs.py          # regenerate
    python scripts/generate_api_docs.py --check  # exit 1 if out of date
"""

from __future__ import annotations

import argparse
import json
import re
import sys
import tempfile
from dataclasses import dataclass
from pathlib import Path
from typing import Any

import griffe

PACKAGE_ROOT = Path(__file__).resolve().parent.parent
REPO_ROOT = PACKAGE_ROOT.parent.parent
OUTPUT_DIR = REPO_ROOT / "docs" / "python" / "api"
SITE_PREFIX = "/python/api"
PACKAGE = "b2c_tooling_sdk"


@dataclass(frozen=True)
class Page:
    module: str
    slug: str
    title: str
    # False renders only the module docstring (the top-level package re-exports
    # everything documented on the subpackage pages; ``sync`` mirrors them).
    members: bool = True


PAGES = [
    Page("b2c_tooling_sdk", "package", "Top-level package", members=False),
    Page("b2c_tooling_sdk.auth", "auth", "auth"),
    Page("b2c_tooling_sdk.config", "config", "config"),
    Page("b2c_tooling_sdk.instance", "instance", "instance"),
    Page("b2c_tooling_sdk.clients", "clients", "clients"),
    Page("b2c_tooling_sdk.errors", "errors", "errors"),
    Page("b2c_tooling_sdk.logging", "logging", "logging"),
    Page("b2c_tooling_sdk.operations.code", "operations/code", "operations.code"),
    Page("b2c_tooling_sdk.operations.jobs", "operations/jobs", "operations.jobs"),
    Page("b2c_tooling_sdk.operations.sites", "operations/sites", "operations.sites"),
    Page("b2c_tooling_sdk.operations.catalogs", "operations/catalogs", "operations.catalogs"),
    Page("b2c_tooling_sdk.operations.bm_users", "operations/bm_users", "operations.bm_users"),
    Page("b2c_tooling_sdk.operations.bm_roles", "operations/bm_roles", "operations.bm_roles"),
    Page("b2c_tooling_sdk.operations.users", "operations/users", "operations.users"),
    Page("b2c_tooling_sdk.operations.roles", "operations/roles", "operations.roles"),
    Page("b2c_tooling_sdk.operations.orgs", "operations/orgs", "operations.orgs"),
    Page("b2c_tooling_sdk.operations.ods", "operations/ods", "operations.ods"),
    Page("b2c_tooling_sdk.operations.metrics", "operations/metrics", "operations.metrics"),
    Page("b2c_tooling_sdk.operations.logs", "operations/logs", "operations.logs"),
    Page("b2c_tooling_sdk.slas", "slas", "slas"),
    Page("b2c_tooling_sdk.sync", "sync", "sync", members=False),
]

HEADER = "<!-- Generated by python/b2c-tooling-sdk/scripts/generate_api_docs.py. Do not edit. -->"


# ---------------------------------------------------------------------------
# Symbol index (for cross-references)
# ---------------------------------------------------------------------------


def _resolve(obj: Any) -> Any | None:
    try:
        return obj.final_target if obj.is_alias else obj
    except (griffe.AliasResolutionError, griffe.CyclicAliasError):
        return None


def _exports(module: Any) -> list[tuple[str, Any]]:
    out = []
    for name in module.exports or []:
        name = str(name)
        member = module.members.get(name)
        target = _resolve(member) if member is not None else None
        if target is None or target.is_module:
            continue
        out.append((name, target))
    return out


class SymbolIndex:
    """Maps each documented object to the page/anchor that documents it."""

    def __init__(self) -> None:
        self.by_path: dict[str, tuple[Page, str]] = {}
        self.by_name: dict[str, list[tuple[Page, str]]] = {}
        self.used: dict[str, set[str]] = {}

    def add(self, path: str, name: str, page: Page) -> None:
        if path in self.by_path:
            return
        # Slugs are lowercase, so e.g. ``foo_bar`` and ``FOO_BAR`` collide; suffix like VitePress does.
        used = self.used.setdefault(page.slug, set())
        base = anchor = _anchor(name)
        suffix = 1
        while anchor in used:
            anchor = f"{base}-{suffix}"
            suffix += 1
        used.add(anchor)
        self.by_path[path] = (page, anchor)
        self.by_name.setdefault(name, []).append((page, anchor))

    def link(self, ref: str, current: Page) -> str | None:
        ref = ref.lstrip("~.").removesuffix("()")
        hit = self.by_path.get(ref)
        if hit is None:
            candidates = self.by_name.get(ref.split(".")[-1], [])
            if not candidates and "." in ref:
                # ``Class.method`` references
                candidates = self.by_name.get(".".join(ref.split(".")[-2:]), [])
            if not candidates:
                return None
            hit = next((c for c in candidates if c[0] == current), candidates[0])
        page, anchor = hit
        return f"{SITE_PREFIX}/{page.slug}#{anchor}"


# ---------------------------------------------------------------------------
# Docstring (reST-ish) -> Markdown
# ---------------------------------------------------------------------------

ROLE_RE = re.compile(r":(?:py:)?(?:func|class|meth|attr|data|mod|exc|obj|const):`([^`]+)`")
LITERAL_RE = re.compile(r"``(.+?)``")


def _escape_prose(text: str) -> str:
    """Escape characters Vue/VitePress would interpret, outside code spans."""
    parts = re.split(r"(`[^`]*`)", text)
    for i in range(0, len(parts), 2):
        parts[i] = re.sub(r"<(?=[A-Za-z/!])", "&lt;", parts[i]).replace("{{", "&#123;&#123;")
    return "".join(parts)


def _inline(text: str, index: SymbolIndex, page: Page) -> str:
    def role(match: re.Match[str]) -> str:
        ref = match.group(1)
        label = ref
        explicit = re.match(r"(.+?)\s*<(.+)>$", ref)
        if explicit:
            label, ref = explicit.group(1), explicit.group(2)
        elif ref.startswith("~"):
            label = ref.lstrip("~").split(".")[-1]
        url = index.link(ref, page)
        return f"[`{label}`]({url})" if url else f"`{label}`"

    text = LITERAL_RE.sub(lambda m: f"`{m.group(1)}`", text)
    text = ROLE_RE.sub(role, text)
    return _escape_prose(text)


def _dedent(lines: list[str]) -> list[str]:
    indents = [len(line) - len(line.lstrip()) for line in lines if line.strip()]
    cut = min(indents) if indents else 0
    return [line[cut:] for line in lines]


def _take_indented(lines: list[str], start: int, base_indent: int) -> tuple[list[str], int]:
    """Collect the indented block following a ``::`` / directive line."""
    i = start
    block: list[str] = []
    while i < len(lines) and not lines[i].strip():
        i += 1
    while i < len(lines) and (not lines[i].strip() or len(lines[i]) - len(lines[i].lstrip()) > base_indent):
        block.append(lines[i])
        i += 1
    while block and not block[-1].strip():
        block.pop()
    return _dedent(block), i


def rst_to_md(text: str, index: SymbolIndex, page: Page) -> str:
    lines = text.splitlines()
    out: list[str] = []
    i = 0
    while i < len(lines):
        line = lines[i]
        stripped = line.strip()
        indent = len(line) - len(line.lstrip())

        directive = re.match(r"\.\. code-block::\s*(\w*)", stripped)
        if directive:
            block, i = _take_indented(lines, i + 1, indent)
            out += [f"```{directive.group(1) or 'python'}", *block, "```"]
            continue

        if stripped.endswith("::") and i + 1 < len(lines):
            lead = stripped[:-2].rstrip()
            if lead:
                out.append(" " * indent + _inline(lead + ":", index, page))
            block, i = _take_indented(lines, i + 1, indent)
            out += ["", "```python", *block, "```"]
            continue

        if stripped.startswith(">>>"):
            block = []
            while i < len(lines) and lines[i].strip():
                block.append(lines[i])
                i += 1
            out += ["```python", *_dedent(block), "```"]
            continue

        if (
            stripped
            and i + 1 < len(lines)
            and re.fullmatch(r"([-=~^])\1{2,}", lines[i + 1].strip())
            and len(lines[i + 1].strip()) >= len(stripped)
        ):
            out.append(f"**{_inline(stripped, index, page)}**")
            i += 2
            continue

        out.append(_inline(line, index, page))
        i += 1
    return "\n".join(out).strip()


def _cell(text: str) -> str:
    return " ".join(text.split()).replace("|", "\\|")


def _render_sections(obj: Any, index: SymbolIndex, page: Page) -> list[str]:
    docstring = obj.docstring
    if docstring is None:
        return []
    out: list[str] = []
    for section in docstring.parsed:
        kind = section.kind.value
        if kind == "text":
            out += [rst_to_md(section.value, index, page), ""]
        elif kind == "parameters":
            out += ["**Parameters**", "", "| Name | Type | Description |", "| --- | --- | --- |"]
            for param in section.value:
                annotation = f"`{_cell(str(param.annotation))}`" if param.annotation else ""
                description = _cell(_inline(param.description, index, page))
                out.append(f"| `{param.name}` | {annotation} | {description} |")
            out.append("")
        elif kind == "attributes":
            out += ["**Attributes**", "", "| Name | Type | Description |", "| --- | --- | --- |"]
            for attr in section.value:
                annotation = f"`{_cell(str(attr.annotation))}`" if attr.annotation else ""
                out.append(f"| `{attr.name}` | {annotation} | {_cell(_inline(attr.description, index, page))} |")
            out.append("")
        elif kind == "returns":
            for ret in section.value:
                out += [f"**Returns:** {_inline(' '.join(ret.description.split()), index, page)}", ""]
        elif kind == "raises":
            out += ["**Raises**", ""]
            for exc in section.value:
                out.append(
                    f"- {_type_ref(exc.annotation, index, page)} — {_inline(' '.join(exc.description.split()), index, page)}"
                )
            out.append("")
    return out


# ---------------------------------------------------------------------------
# Object rendering
# ---------------------------------------------------------------------------


def _signature(obj: Any, name: str) -> str:
    if obj.is_function:
        prefix = "async def" if "async" in obj.labels else "def"
        return f"{prefix} {obj.signature()}".replace(f"def {obj.name}(", f"def {name}(", 1)
    if obj.is_class:
        bases = ", ".join(str(base) for base in obj.bases)
        return f"class {name}({bases})" if bases else f"class {name}"
    annotation = f": {obj.annotation}" if obj.annotation is not None else ""
    value = f" = {obj.value}" if obj.value is not None else ""
    if len(value) > 200:
        value = " = ..."
    return f"{name}{annotation}{value}"


def _code(signature: str) -> list[str]:
    return ["```python", signature, "```", ""]


def _anchor(name: str) -> str:
    # Match VitePress's slugify: its link plugin rewrites cross-page ``#hash``
    # fragments this way (but leaves explicit ``{#id}`` heading attributes alone).
    return re.sub(r"[^a-z0-9]+", "-", name.lower()).strip("-")


def _class_fields(cls: Any) -> list[Any]:
    return [
        member
        for name, member in cls.members.items()
        if not member.is_alias and member.is_attribute and not name.startswith("_")
    ]


def _class_methods(cls: Any) -> list[Any]:
    return [
        member
        for name, member in cls.members.items()
        if not member.is_alias and member.is_function and not name.startswith("_") and member.docstring is not None
    ]


def _fields_table(fields: list[Any], index: SymbolIndex, page: Page) -> list[str]:
    rows = []
    for field in fields:
        annotation = f"`{_cell(str(field.annotation))}`" if field.annotation is not None else ""
        default = f"`{_cell(str(field.value))}`" if field.value is not None and len(str(field.value)) <= 60 else ""
        summary = _cell(_inline(field.docstring.value, index, page)) if field.docstring else ""
        rows.append((f"`{field.name}`", annotation, default, summary))
    columns = [
        ("Name", True),
        ("Type", True),
        ("Default", any(r[2] for r in rows)),
        ("Description", any(r[3] for r in rows)),
    ]
    keep = [i for i, (_, shown) in enumerate(columns) if shown]
    out = ["**Fields**", "", "| " + " | ".join(columns[i][0] for i in keep) + " |", "|" + " --- |" * len(keep)]
    out += ["| " + " | ".join(row[i] for i in keep) + " |" for row in rows]
    return [*out, ""]


def _type_ref(annotation: Any, index: SymbolIndex, page: Page) -> str:
    url = index.link(str(annotation), page)
    return f"[`{annotation}`]({url})" if url else f"`{annotation}`"


def render_object(name: str, obj: Any, index: SymbolIndex, page: Page) -> list[str]:
    out = [f"### {name} {{#{index.by_path[obj.path][1]}}}", ""]
    out += _code(_signature(obj, name))
    out += _render_sections(obj, index, page)

    if obj.is_class:
        documented = {
            attr.name
            for section in (obj.docstring.parsed if obj.docstring else [])
            if section.kind.value == "attributes"
            for attr in section.value
        }
        fields = [
            field
            for field in _class_fields(obj)
            if field.name not in documented and (field.annotation is not None or field.docstring is not None)
        ]
        if fields:
            out += _fields_table(fields, index, page)
        for method in _class_methods(obj):
            label = "property" if "property" in method.labels else "method"
            anchor = index.by_path[f"{obj.path}.{method.name}"][1]
            out += [f'#### {method.name} <Badge type="info" text="{label}" /> {{#{anchor}}}', ""]
            if label == "property":
                annotation = f" -> {method.returns}" if method.returns else ""
                out += _code(f"{method.name}{annotation}")
            else:
                out += _code(_signature(method, method.name))
            out += _render_sections(method, index, page)
    return out


def _first_line(obj: Any) -> str:
    if obj.docstring is None:
        return ""
    return obj.docstring.value.strip().split("\n\n")[0].replace("\n", " ")


def render_page(page: Page, module: Any, index: SymbolIndex, canonical: dict[str, Page]) -> str:
    out = [
        "---",
        "editLink: false",
        "lastUpdated: false",
        "outline: [2, 3]",
        "---",
        "",
        HEADER,
        "",
        f"# {page.module}",
        "",
    ]
    if module.docstring:
        out += [rst_to_md(module.docstring.value, index, page), ""]
    if not page.members:
        return "\n".join(out).rstrip() + "\n"

    groups: dict[str, list[tuple[str, Any]]] = {"Classes": [], "Functions": [], "Attributes": []}
    reexports: list[tuple[str, Any]] = []
    for name, target in _exports(module):
        if canonical.get(target.path) is not page:
            reexports.append((name, target))
        elif target.is_class:
            groups["Classes"].append((name, target))
        elif target.is_function:
            groups["Functions"].append((name, target))
        else:
            groups["Attributes"].append((name, target))

    for heading, items in groups.items():
        if not items:
            continue
        out += [f"## {heading}", ""]
        for name, target in items:
            out += render_object(name, target, index, page)
    if reexports:
        out += ["## Re-exports", "", "Also exported from this module; documented elsewhere:", ""]
        for name, target in reexports:
            url = index.link(target.path, page)
            out.append(f"- [`{name}`]({url})")
        out.append("")
    return "\n".join(out).rstrip() + "\n"


def render_index(modules: dict[str, Any]) -> str:
    out = [
        "---",
        "editLink: false",
        "lastUpdated: false",
        "---",
        "",
        HEADER,
        "",
        "# API Reference",
        "",
        "Generated from the `b2c_tooling_sdk` source docstrings. Each page documents one",
        "public barrel module; import from these paths.",
        "",
        "| Module | Summary |",
        "| --- | --- |",
    ]
    for page in PAGES:
        summary = _cell(_escape_prose(LITERAL_RE.sub(r"`\1`", _first_line(modules[page.module]))))
        out.append(f"| [`{page.module}`]({SITE_PREFIX}/{page.slug}) | {summary} |")
    return "\n".join(out) + "\n"


def generate(output_dir: Path) -> None:
    package = griffe.load(
        PACKAGE,
        search_paths=[str(PACKAGE_ROOT / "src")],
        docstring_parser=griffe.Parser.sphinx,
        resolve_aliases=True,
        resolve_external=False,
    )
    modules = {
        page.module: package if page.module == PACKAGE else package[page.module[len(PACKAGE) + 1 :]] for page in PAGES
    }

    index = SymbolIndex()
    canonical: dict[str, Page] = {}
    for page in PAGES:
        if not page.members:
            continue
        for name, target in _exports(modules[page.module]):
            canonical.setdefault(target.path, page)
            if canonical[target.path] is page:
                index.add(target.path, name, page)
                if target.is_class:
                    for method in _class_methods(target):
                        method_name = f"{name}.{method.name}"
                        index.add(f"{target.path}.{method.name}", method_name, page)

    for stale in output_dir.rglob("*.md"):
        stale.unlink()
    output_dir.mkdir(parents=True, exist_ok=True)
    (output_dir / "index.md").write_text(render_index(modules))
    for page in PAGES:
        target_file = output_dir / f"{page.slug}.md"
        target_file.parent.mkdir(parents=True, exist_ok=True)
        target_file.write_text(render_page(page, modules[page.module], index, canonical))

    sidebar = [{"text": "Overview", "link": f"{SITE_PREFIX}/"}] + [
        {"text": page.title, "link": f"{SITE_PREFIX}/{page.slug}"} for page in PAGES
    ]
    (output_dir / "sidebar.json").write_text(json.dumps(sidebar, indent=2) + "\n")


def _snapshot(directory: Path) -> dict[str, str]:
    return {
        str(path.relative_to(directory)): path.read_text() for path in sorted(directory.rglob("*")) if path.is_file()
    }


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument("--check", action="store_true", help="fail if the committed pages are out of date")
    args = parser.parse_args()

    if not args.check:
        generate(OUTPUT_DIR)
        print(f"Wrote API reference to {OUTPUT_DIR.relative_to(REPO_ROOT)}")
        return 0

    with tempfile.TemporaryDirectory() as tmp:
        generate(Path(tmp))
        expected = _snapshot(Path(tmp))
    actual = _snapshot(OUTPUT_DIR) if OUTPUT_DIR.exists() else {}
    if expected != actual:
        stale = sorted(set(expected) ^ set(actual) | {k for k in expected if actual.get(k) != expected[k]})
        print("Python API reference is out of date. Run: make api-docs", file=sys.stderr)
        for name in stale:
            print(f"  {name}", file=sys.stderr)
        return 1
    print("Python API reference is up to date.")
    return 0


if __name__ == "__main__":
    sys.exit(main())
