# Copyright (c) 2025, Salesforce, Inc.
# SPDX-License-Identifier: Apache-2.0
# For full license text, see the LICENSE file in the repo root or http://www.apache.org/licenses/LICENSE-2.0
"""HTTP clients for B2C Commerce APIs.

Mirrors the ``clients`` subpath of the TypeScript SDK. Provides the core
:class:`HttpClient` (openapi-fetch analog with :class:`ClientResult`), the shared
middleware chain, the OCAPI and WebDAV clients, the SCAPI/OCAPI dual-backend
utilities, the typed domain clients (SLAS, ODS, MRT, Account Manager, SCAPI Jobs/
Sites/Catalogs/Scripts/Merchant-Users/Merchant-Roles/Schemas, Custom APIs, CDN
Zones, Preferences, Metrics, Granular Replications), the middleware registry,
TLS/mTLS transport helpers, and API error-message utilities.

Importing this package auto-registers the User-Agent middleware providers (see
:mod:`b2c_tooling_sdk.clients.user_agent`).
"""

from __future__ import annotations

from b2c_tooling_sdk.clients._core import (
    ClientResult,
    HttpClient,
    Middleware,
    MiddlewareRequestContext,
    MiddlewareResponseContext,
)
from b2c_tooling_sdk.clients.am_api import (
    ROLE_TENANT_FILTER_PATTERN,
    AccountManagerApiClient,
    AccountManagerApiClientsClient,
    AccountManagerClient,
    AccountManagerClientConfig,
    AccountManagerOrganization,
    AccountManagerOrgsClient,
    AccountManagerRole,
    AccountManagerRolesClient,
    AccountManagerUser,
    AccountManagerUsersClient,
    APIClientCollection,
    APIClientCreate,
    ApiClientExpandOption,
    APIClientUpdate,
    ListApiClientsOptions,
    ListOrgsOptions,
    ListRolesOptions,
    ListUsersOptions,
    OrganizationCollection,
    OrgMapping,
    RoleCollection,
    RoleMapping,
    UserCollection,
    UserCreate,
    UserExpandOption,
    UserState,
    UserUpdate,
    change_api_client_password,
    create_account_manager_api_clients_client,
    create_account_manager_client,
    create_account_manager_orgs_client,
    create_account_manager_roles_client,
    create_account_manager_users_client,
    create_api_client,
    create_user,
    delete_api_client,
    delete_user,
    fetch_role_mapping,
    find_user_by_login,
    get_api_client,
    get_role,
    get_user,
    is_valid_role_tenant_filter,
    list_api_clients,
    list_roles,
    list_users,
    purge_user,
    reset_user,
    resolve_from_internal_role,
    resolve_to_internal_role,
    update_api_client,
    update_user,
)
from b2c_tooling_sdk.clients.cdn_zones import (
    CDN_ZONES_READ_SCOPES,
    CDN_ZONES_RW_SCOPES,
    CdnZonesClient,
    CdnZonesClientConfig,
    CdnZonesClientOptions,
    CdnZonesError,
    Zone,
    ZonesEnvelope,
    create_cdn_zones_client,
)
from b2c_tooling_sdk.clients.custom_apis import (
    CUSTOM_APIS_DEFAULT_SCOPES,
    ORGANIZATION_ID_PREFIX,
    SCAPI_TENANT_SCOPE_PREFIX,
    CustomApisClient,
    CustomApisClientConfig,
    build_tenant_scope,
    create_custom_apis_client,
    normalize_tenant_id,
    to_organization_id,
)
from b2c_tooling_sdk.clients.dual_backend_factory import (
    DualBackendConfig,
    DualBackendCtors,
    ScapiBackendCtorConfig,
    create_dual_backend,
)
from b2c_tooling_sdk.clients.error_utils import (
    OCAPI_DEPRECATED_MESSAGE,
    OcapiDeprecatedError,
    get_api_error_message,
    is_ocapi_deprecated_fault,
    ocapi_deprecated_message,
    throw_ocapi_error,
)
from b2c_tooling_sdk.clients.granular_replications import (
    ContentAssetItemPrivate,
    ContentAssetItemShared,
    GranularReplicationsClient,
    GranularReplicationsClientConfig,
    GranularReplicationsError,
    PriceTableItem,
    ProductItem,
    PublishIdResponse,
    PublishProcessListResponse,
    PublishProcessResponse,
    create_granular_replications_client,
)
from b2c_tooling_sdk.clients.metrics import (
    METRICS_DEFAULT_SCOPES,
    Metric,
    MetricDataPoint,
    MetricDataSeries,
    MetricsClient,
    MetricsClientConfig,
    MetricsDataResponse,
    MetricsError,
    create_metrics_client,
)
from b2c_tooling_sdk.clients.middleware import (
    SCOPE_MODE_HEADER,
    ScopeCascade,
    create_auth_middleware,
    create_extra_params_middleware,
    create_logging_middleware,
    create_rate_limit_middleware,
    create_scapi_auth_middleware,
    create_user_agent_middleware,
)
from b2c_tooling_sdk.clients.middleware_registry import (
    HttpClientType,
    HttpMiddlewareProvider,
    MiddlewareRegistry,
    UnifiedMiddleware,
    global_middleware_registry,
)
from b2c_tooling_sdk.clients.mrt import (
    DEFAULT_MRT_ORIGIN,
    MrtClient,
    MrtClientConfig,
    create_mrt_client,
)
from b2c_tooling_sdk.clients.mrt_b2c import (
    DEFAULT_MRT_B2C_ORIGIN,
    B2COrgInfo,
    B2CTargetInfo,
    MrtB2CClient,
    MrtB2CClientConfig,
    PatchedB2CTargetInfo,
    create_mrt_b2c_client,
)
from b2c_tooling_sdk.clients.ocapi import DEFAULT_API_VERSION, OcapiClient, create_ocapi_client
from b2c_tooling_sdk.clients.ods import OdsClient, OdsClientConfig, create_ods_client
from b2c_tooling_sdk.clients.preferences import (
    PREFERENCES_READ_SCOPES,
    PREFERENCES_RW_SCOPES,
    CustomPreference,
    CustomPreferenceList,
    OrganizationPreferences,
    PreferenceInstanceType,
    PreferencesClient,
    PreferencesClientConfig,
    PreferencesClientOptions,
    PreferencesError,
    PreferenceValue,
    PreferenceValueSearchResult,
    SitePreferences,
    create_preferences_client,
)
from b2c_tooling_sdk.clients.preferences import SearchRequest as PreferencesSearchRequest
from b2c_tooling_sdk.clients.scapi_backend_utils import (
    SAFE_SCAPI_FALLBACK_STATUSES,
    SCAPI_CAPABILITY_BASELINE_RELEASE,
    ApiBackendPreference,
    BackendBase,
    ResolveBackendOptions,
    ScapiCapabilityUnsupportedError,
    ScapiRequestError,
    ScapiUserAuthUnsupportedError,
    assert_ocapi_compatibility_allowed,
    assert_scapi_admin_auth_supported,
    create_scapi_request_error,
    is_fallback_trigger,
    is_invalid_scope_error,
    resolve_scapi_or_ocapi,
    scapi_capability_unsupported_message,
    scapi_unavailable_message,
    with_scopes,
)
from b2c_tooling_sdk.clients.scapi_catalogs import (
    SCAPI_CATALOGS_CASCADE,
    ScapiCatalogsClient,
    ScapiCatalogsClientConfig,
    create_scapi_catalogs_client,
)
from b2c_tooling_sdk.clients.scapi_catalogs import Catalog as ScapiCatalog
from b2c_tooling_sdk.clients.scapi_catalogs import Catalogs as ScapiCatalogs
from b2c_tooling_sdk.clients.scapi_client_factory import (
    BuildScapiClientOptions,
    ScapiClientConfig,
    build_scapi_client,
)
from b2c_tooling_sdk.clients.scapi_fallback_backend import create_fallback_backend
from b2c_tooling_sdk.clients.scapi_jobs import (
    SCAPI_JOBS_CASCADE,
    ExecutionStatus,
    ExitStatus,
    JobExecution,
    JobExecutionSearchResult,
    JobParameter,
    JobStepExecution,
    ScapiJobsClient,
    ScapiJobsClientConfig,
    create_scapi_jobs_client,
)
from b2c_tooling_sdk.clients.scapi_merchant_roles import (
    SCAPI_MERCHANT_ROLES_READ_SCOPES,
    SCAPI_MERCHANT_ROLES_RW_SCOPES,
    Role,
    RolePermissions,
    RoleSearch,
    ScapiMerchantRolesClient,
    ScapiMerchantRolesClientConfig,
    create_scapi_merchant_roles_client,
)
from b2c_tooling_sdk.clients.scapi_merchant_users import (
    SCAPI_MERCHANT_USERS_READ_SCOPES,
    SCAPI_MERCHANT_USERS_RW_SCOPES,
    ScapiMerchantUsersClient,
    ScapiMerchantUsersClientConfig,
    User,
    UserSearch,
    UserUpdateRequest,
    create_scapi_merchant_users_client,
)
from b2c_tooling_sdk.clients.scapi_schemas import (
    SCAPI_SCHEMAS_DEFAULT_SCOPES,
    OpenApiSchema,
    ScapiSchemasClient,
    ScapiSchemasClientConfig,
    ScapiSchemasError,
    SchemaListItem,
    SchemaListResult,
    create_scapi_schemas_client,
)
from b2c_tooling_sdk.clients.scapi_scope_tier import ScopeTier, ScopeTierManager
from b2c_tooling_sdk.clients.scapi_scripts import (
    SCAPI_SCRIPTS_READ_SCOPES,
    SCAPI_SCRIPTS_RW_SCOPES,
    CodeVersion,
    ScapiScriptsClient,
    ScapiScriptsClientConfig,
    create_scapi_scripts_client,
)
from b2c_tooling_sdk.clients.scapi_sites import (
    SCAPI_SITES_CASCADE,
    ScapiSitesClient,
    ScapiSitesClientConfig,
    SiteCustomCartridges,
    create_scapi_sites_client,
)
from b2c_tooling_sdk.clients.scapi_sites import Site as ScapiSite
from b2c_tooling_sdk.clients.scapi_sites import Sites as ScapiSites
from b2c_tooling_sdk.clients.scapi_sites import SiteSearchResult as ScapiSiteSearchResult
from b2c_tooling_sdk.clients.slas_admin import SlasClient, SlasClientConfig, create_slas_client
from b2c_tooling_sdk.clients.tls import TlsOptions, create_tls_transport
from b2c_tooling_sdk.clients.user_agent import (
    get_user_agent,
    reset_user_agent,
    set_user_agent,
    user_agent_provider,
)
from b2c_tooling_sdk.clients.webdav import PropfindEntry, WebDavClient

__all__ = [
    "CDN_ZONES_READ_SCOPES",
    "CDN_ZONES_RW_SCOPES",
    "CUSTOM_APIS_DEFAULT_SCOPES",
    "DEFAULT_API_VERSION",
    "DEFAULT_MRT_B2C_ORIGIN",
    "DEFAULT_MRT_ORIGIN",
    "METRICS_DEFAULT_SCOPES",
    "OCAPI_DEPRECATED_MESSAGE",
    "ORGANIZATION_ID_PREFIX",
    "PREFERENCES_READ_SCOPES",
    "PREFERENCES_RW_SCOPES",
    "ROLE_TENANT_FILTER_PATTERN",
    "SAFE_SCAPI_FALLBACK_STATUSES",
    "SCAPI_CAPABILITY_BASELINE_RELEASE",
    "SCAPI_CATALOGS_CASCADE",
    "SCAPI_JOBS_CASCADE",
    "SCAPI_MERCHANT_ROLES_READ_SCOPES",
    "SCAPI_MERCHANT_ROLES_RW_SCOPES",
    "SCAPI_MERCHANT_USERS_READ_SCOPES",
    "SCAPI_MERCHANT_USERS_RW_SCOPES",
    "SCAPI_SCHEMAS_DEFAULT_SCOPES",
    "SCAPI_SCRIPTS_READ_SCOPES",
    "SCAPI_SCRIPTS_RW_SCOPES",
    "SCAPI_SITES_CASCADE",
    "SCAPI_TENANT_SCOPE_PREFIX",
    "SCOPE_MODE_HEADER",
    "APIClientCollection",
    "APIClientCreate",
    "APIClientUpdate",
    "AccountManagerApiClient",
    "AccountManagerApiClientsClient",
    "AccountManagerClient",
    "AccountManagerClientConfig",
    "AccountManagerOrganization",
    "AccountManagerOrgsClient",
    "AccountManagerRole",
    "AccountManagerRolesClient",
    "AccountManagerUser",
    "AccountManagerUsersClient",
    "ApiBackendPreference",
    "ApiClientExpandOption",
    "BackendBase",
    "B2COrgInfo",
    "B2CTargetInfo",
    "BuildScapiClientOptions",
    "CdnZonesClient",
    "CdnZonesClientConfig",
    "CdnZonesClientOptions",
    "CdnZonesError",
    "ClientResult",
    "CodeVersion",
    "ContentAssetItemPrivate",
    "ContentAssetItemShared",
    "CustomApisClient",
    "CustomApisClientConfig",
    "CustomPreference",
    "CustomPreferenceList",
    "DualBackendConfig",
    "DualBackendCtors",
    "ExecutionStatus",
    "ExitStatus",
    "GranularReplicationsClient",
    "GranularReplicationsClientConfig",
    "GranularReplicationsError",
    "HttpClient",
    "HttpClientType",
    "HttpMiddlewareProvider",
    "JobExecution",
    "JobExecutionSearchResult",
    "JobParameter",
    "JobStepExecution",
    "ListApiClientsOptions",
    "ListOrgsOptions",
    "ListRolesOptions",
    "ListUsersOptions",
    "Metric",
    "MetricDataPoint",
    "MetricDataSeries",
    "MetricsClient",
    "MetricsClientConfig",
    "MetricsDataResponse",
    "MetricsError",
    "Middleware",
    "MiddlewareRegistry",
    "MiddlewareRequestContext",
    "MiddlewareResponseContext",
    "MrtB2CClient",
    "MrtB2CClientConfig",
    "MrtClient",
    "MrtClientConfig",
    "OcapiClient",
    "OcapiDeprecatedError",
    "OdsClient",
    "OdsClientConfig",
    "OpenApiSchema",
    "OrgMapping",
    "OrganizationCollection",
    "OrganizationPreferences",
    "PatchedB2CTargetInfo",
    "PreferenceInstanceType",
    "PreferenceValue",
    "PreferenceValueSearchResult",
    "PreferencesClient",
    "PreferencesClientConfig",
    "PreferencesClientOptions",
    "PreferencesError",
    "PreferencesSearchRequest",
    "PriceTableItem",
    "ProductItem",
    "PropfindEntry",
    "PublishIdResponse",
    "PublishProcessListResponse",
    "PublishProcessResponse",
    "ResolveBackendOptions",
    "Role",
    "RoleCollection",
    "RoleMapping",
    "RolePermissions",
    "RoleSearch",
    "ScapiBackendCtorConfig",
    "ScapiCapabilityUnsupportedError",
    "ScapiCatalog",
    "ScapiCatalogs",
    "ScapiCatalogsClient",
    "ScapiCatalogsClientConfig",
    "ScapiClientConfig",
    "ScapiJobsClient",
    "ScapiJobsClientConfig",
    "ScapiMerchantRolesClient",
    "ScapiMerchantRolesClientConfig",
    "ScapiMerchantUsersClient",
    "ScapiMerchantUsersClientConfig",
    "ScapiRequestError",
    "ScapiSchemasClient",
    "ScapiSchemasClientConfig",
    "ScapiSchemasError",
    "ScapiScriptsClient",
    "ScapiScriptsClientConfig",
    "ScapiSite",
    "ScapiSiteSearchResult",
    "ScapiSites",
    "ScapiSitesClient",
    "ScapiSitesClientConfig",
    "ScapiUserAuthUnsupportedError",
    "SchemaListItem",
    "SchemaListResult",
    "ScopeCascade",
    "ScopeTier",
    "ScopeTierManager",
    "SiteCustomCartridges",
    "SitePreferences",
    "SlasClient",
    "SlasClientConfig",
    "TlsOptions",
    "UnifiedMiddleware",
    "User",
    "UserCollection",
    "UserCreate",
    "UserExpandOption",
    "UserSearch",
    "UserState",
    "UserUpdate",
    "UserUpdateRequest",
    "WebDavClient",
    "Zone",
    "ZonesEnvelope",
    "assert_ocapi_compatibility_allowed",
    "assert_scapi_admin_auth_supported",
    "build_scapi_client",
    "build_tenant_scope",
    "change_api_client_password",
    "create_account_manager_api_clients_client",
    "create_account_manager_client",
    "create_account_manager_orgs_client",
    "create_account_manager_roles_client",
    "create_account_manager_users_client",
    "create_api_client",
    "create_auth_middleware",
    "create_cdn_zones_client",
    "create_custom_apis_client",
    "create_dual_backend",
    "create_extra_params_middleware",
    "create_fallback_backend",
    "create_granular_replications_client",
    "create_logging_middleware",
    "create_metrics_client",
    "create_mrt_b2c_client",
    "create_mrt_client",
    "create_ocapi_client",
    "create_ods_client",
    "create_preferences_client",
    "create_rate_limit_middleware",
    "create_scapi_auth_middleware",
    "create_scapi_catalogs_client",
    "create_scapi_jobs_client",
    "create_scapi_merchant_roles_client",
    "create_scapi_merchant_users_client",
    "create_scapi_request_error",
    "create_scapi_schemas_client",
    "create_scapi_scripts_client",
    "create_scapi_sites_client",
    "create_slas_client",
    "create_tls_transport",
    "create_user",
    "create_user_agent_middleware",
    "delete_api_client",
    "delete_user",
    "fetch_role_mapping",
    "find_user_by_login",
    "get_api_client",
    "get_api_error_message",
    "get_role",
    "get_user",
    "get_user_agent",
    "global_middleware_registry",
    "is_fallback_trigger",
    "is_invalid_scope_error",
    "is_ocapi_deprecated_fault",
    "is_valid_role_tenant_filter",
    "list_api_clients",
    "list_roles",
    "list_users",
    "normalize_tenant_id",
    "ocapi_deprecated_message",
    "purge_user",
    "reset_user",
    "reset_user_agent",
    "resolve_from_internal_role",
    "resolve_scapi_or_ocapi",
    "resolve_to_internal_role",
    "scapi_capability_unsupported_message",
    "scapi_unavailable_message",
    "set_user_agent",
    "throw_ocapi_error",
    "to_organization_id",
    "update_api_client",
    "update_user",
    "user_agent_provider",
    "with_scopes",
]
