/*
 * Copyright (c) 2025, Salesforce, Inc.
 * SPDX-License-Identifier: Apache-2
 * For full license text, see the license.txt file in the repo root or http://www.apache.org/licenses/LICENSE-2.0
 */
/**
 * Writes an {@link OpenShellSetup} to disk and applies it with the `openshell`
 * and `docker` command line tools.
 *
 * @module openshell/apply
 */
import {execFile} from 'node:child_process';
import {existsSync} from 'node:fs';
import * as fs from 'node:fs/promises';
import path from 'node:path';

import {OPENSHELL_SAFETY_CONFIG_PATH, type OpenShellSetup} from './setup.js';

/** Result of running an external command. */
export interface CommandResult {
  code: number;
  stdout: string;
  stderr: string;
}

/**
 * Runs an external command without a shell. Secrets are passed only through
 * `env`, never as arguments, so they do not appear in process listings or
 * printed commands.
 */
export type CommandRunner = (command: string, args: string[], env?: Record<string, string>) => Promise<CommandResult>;

/** Default {@link CommandRunner} using `child_process.execFile` (no shell). */
export const runCommand: CommandRunner = (command, args, env) =>
  new Promise((resolve) => {
    execFile(command, args, {env: {...process.env, ...env}, maxBuffer: 16 * 1024 * 1024}, (error, stdout, stderr) => {
      const code = error ? (typeof error.code === 'number' ? error.code : 127) : 0;
      resolve({code, stdout: String(stdout), stderr: String(stderr)});
    });
  });

/** Paths of the files written by {@link writeOpenShellFiles}. */
export interface OpenShellFiles {
  dir: string;
  policy: string;
  dockerfile: string;
  script: string;
  profiles: Record<string, string>;
  /** Safety Mode configuration uploaded to the sandbox, if any */
  safetyConfig?: string;
  /** False when an existing policy file was kept */
  policyWritten: boolean;
  /** True when a kept policy file differs from the generated policy */
  policyDiffers: boolean;
}

/** Options shared by {@link writeOpenShellFiles} and {@link applyOpenShellSetup}. */
export interface OpenShellApplyOptions {
  /** Container image for the sandbox */
  image: string;
  /** Dockerfile content used when the image must be built */
  dockerfile: string;
}

/** A step run by {@link applyOpenShellSetup}. */
export interface OpenShellStep {
  /** Short description of the step */
  description: string;
  /** The equivalent shell command */
  command: string;
}

/** Error thrown when an `openshell` or `docker` command fails. */
export class OpenShellCommandError extends Error {
  constructor(
    readonly command: string,
    readonly result: CommandResult,
  ) {
    super(`Command failed (${result.code}): ${command}\n${(result.stderr || result.stdout).trim()}`);
    this.name = 'OpenShellCommandError';
  }
}

function quote(arg: string): string {
  return /^[\w@%+=:,./-]+$/.test(arg) ? arg : `'${arg.replaceAll("'", String.raw`'\''`)}'`;
}

function formatCommand(command: string, args: string[]): string {
  return [command, ...args].map((a) => quote(a)).join(' ');
}

/** Formats a command with one flag per line, for readability in scripts. */
function formatMultiline(command: string, args: string[]): string {
  const parts: string[] = [];
  for (const arg of args) {
    if (arg.startsWith('--') && parts.length > 0) parts.push(' \\\n  ');
    else if (parts.length > 0) parts.push(' ');
    parts.push(quote(arg));
  }
  return `${command} ${parts.join('')}`;
}

function sandboxCreateArgs(setup: OpenShellSetup, files: OpenShellFiles, image: string): string[] {
  return [
    'sandbox',
    'create',
    '--name',
    setup.sandboxName,
    '--from',
    image,
    '--policy',
    files.policy,
    ...setup.providers.flatMap((p) => ['--provider', p.name]),
    '--no-auto-providers',
    ...Object.entries(setup.env).flatMap(([key, value]) => ['--env', `${key}=${value}`]),
    ...(files.safetyConfig
      ? ['--upload', `${files.safetyConfig}:${OPENSHELL_SAFETY_CONFIG_PATH}`, '--no-git-ignore']
      : []),
    '--detach',
  ];
}

/**
 * Renders the shell commands that create the sandbox from scratch. Written
 * next to the generated files so the setup can be reviewed or run by hand.
 */
export function formatOpenShellScript(setup: OpenShellSetup, files: OpenShellFiles, image: string): string {
  const lines = [
    '#!/usr/bin/env bash',
    `# Creates the OpenShell sandbox "${setup.sandboxName}". Generated by \`b2c setup openshell\`.`,
    ...(setup.providers.length > 0
      ? [
          '# Export these secrets in your shell (or load them from a secret manager) first:',
          ...setup.providers.map((p) => `#   ${p.envVar}`),
        ]
      : []),
    'set -euo pipefail',
    '',
    formatCommand('docker', ['build', '-t', image, files.dir]),
    ...Object.values(files.profiles).map((file) => formatCommand('openshell', ['profile', 'import', '--file', file])),
    ...setup.providers.map((p) =>
      formatCommand('openshell', ['provider', 'create', '--name', p.name, '--type', p.type, '--credential', p.envVar]),
    ),
    formatMultiline('openshell', sandboxCreateArgs(setup, files, image)),
    '',
  ];
  return lines.join('\n');
}

/**
 * Writes the profiles, policy, Dockerfile, and setup script to `dir`.
 * An existing policy file is kept unless `force` is set, so edits to it
 * survive re-runs.
 */
export async function writeOpenShellFiles(
  setup: OpenShellSetup,
  dir: string,
  options: OpenShellApplyOptions & {force?: boolean},
): Promise<OpenShellFiles> {
  const absDir = path.resolve(dir);
  await fs.mkdir(path.join(absDir, 'profiles'), {recursive: true});

  const profiles: Record<string, string> = {};
  for (const profile of setup.profiles) {
    const file = path.join(absDir, 'profiles', `${profile.id}.yaml`);
    await fs.writeFile(file, profile.content);
    profiles[profile.id] = file;
  }

  const policy = path.join(absDir, 'policy.yaml');
  const policyWritten = Boolean(options.force) || !existsSync(policy);
  if (policyWritten) {
    await fs.writeFile(policy, setup.policy);
  }
  const policyDiffers = !policyWritten && (await fs.readFile(policy, 'utf8')) !== setup.policy;

  const dockerfile = path.join(absDir, 'Dockerfile');
  await fs.writeFile(dockerfile, options.dockerfile);

  const safetyConfig = path.join(absDir, 'safety.json');
  if (setup.safetyConfig) {
    await fs.writeFile(safetyConfig, setup.safetyConfig);
  } else {
    await fs.rm(safetyConfig, {force: true});
  }

  const files: OpenShellFiles = {
    dir: absDir,
    policy,
    dockerfile,
    script: path.join(absDir, 'setup.sh'),
    profiles,
    safetyConfig: setup.safetyConfig ? safetyConfig : undefined,
    policyWritten,
    policyDiffers,
  };
  await fs.writeFile(files.script, formatOpenShellScript(setup, files, options.image), {mode: 0o755});
  return files;
}

/** Options for {@link applyOpenShellSetup}. */
export interface ApplyOpenShellSetupOptions extends OpenShellApplyOptions {
  /** Secret values keyed by environment variable name (e.g. `SFCC_CLIENT_SECRET`) */
  secrets: Record<string, string | undefined>;
  /** Build the image when it is missing (default true) */
  build?: boolean;
  /** Create the sandbox, or update the policy of an existing one (default true) */
  sandbox?: boolean;
  /** Delete and recreate an existing sandbox (to apply provider or environment changes) */
  recreate?: boolean;
  /** Called before each step runs */
  onStep?: (step: OpenShellStep) => void;
  /** Command runner (for testing) */
  run?: CommandRunner;
}

/**
 * Applies the setup, converging on the desired state so it can be re-run:
 *
 * 1. Checks that the OpenShell gateway is reachable.
 * 2. Builds the sandbox image if it does not exist.
 * 3. Imports each provider profile, or updates it if it exists.
 * 4. Creates each provider, or updates its secret if it exists.
 * 5. Creates the sandbox, or applies the policy and Safety Mode configuration
 *    to the existing sandbox.
 *
 * @returns The steps that were run
 */
export async function applyOpenShellSetup(
  setup: OpenShellSetup,
  files: OpenShellFiles,
  options: ApplyOpenShellSetupOptions,
): Promise<OpenShellStep[]> {
  const run = options.run ?? runCommand;
  const steps: OpenShellStep[] = [];

  const runStep = async (description: string, command: string, args: string[], env?: Record<string, string>) => {
    const step = {description, command: formatCommand(command, args)};
    options.onStep?.(step);
    const result = await run(command, args, env);
    if (result.code !== 0) throw new OpenShellCommandError(step.command, result);
    steps.push(step);
  };
  const succeeds = async (command: string, args: string[]): Promise<boolean> => (await run(command, args)).code === 0;

  const status = await run('openshell', ['status']);
  if (status.code !== 0) {
    throw new OpenShellCommandError('openshell status', status);
  }

  if (options.build !== false && !(await succeeds('docker', ['image', 'inspect', options.image]))) {
    await runStep(`Build image ${options.image}`, 'docker', ['build', '-t', options.image, files.dir]);
  }

  for (const [id, file] of Object.entries(files.profiles)) {
    const existing = await run('openshell', ['profile', 'export', '-o', 'json', id]);
    if (existing.code !== 0) {
      await runStep(`Import profile ${id}`, 'openshell', ['profile', 'import', '--file', file]);
      continue;
    }
    // Updates must carry the current resource_version of the profile.
    const {resource_version: resourceVersion} = JSON.parse(existing.stdout) as {resource_version?: number};
    const updateFile = path.join(files.dir, 'profiles', `.${id}.update.yaml`);
    await fs.writeFile(updateFile, `${await fs.readFile(file, 'utf8')}resource_version: ${resourceVersion ?? 0}\n`);
    try {
      await runStep(`Update profile ${id}`, 'openshell', ['profile', 'update', '--file', updateFile, id]);
    } finally {
      await fs.rm(updateFile, {force: true});
    }
  }

  for (const provider of setup.providers) {
    const secret = options.secrets[provider.envVar];
    if (!secret) throw new Error(`No value for ${provider.envVar}`);
    const env = {[provider.envVar]: secret};
    await ((await succeeds('openshell', ['provider', 'get', provider.name]))
      ? runStep(
          `Update provider ${provider.name}`,
          'openshell',
          ['provider', 'update', provider.name, '--credential', provider.envVar],
          env,
        )
      : runStep(
          `Create provider ${provider.name}`,
          'openshell',
          ['provider', 'create', '--name', provider.name, '--type', provider.type, '--credential', provider.envVar],
          env,
        ));
  }

  if (options.sandbox === false) return steps;

  const sandboxExists = await succeeds('openshell', ['sandbox', 'get', setup.sandboxName]);
  if (sandboxExists && options.recreate) {
    await runStep(`Delete sandbox ${setup.sandboxName}`, 'openshell', ['sandbox', 'delete', setup.sandboxName]);
  }
  if (!sandboxExists || options.recreate) {
    await runStep(`Create sandbox ${setup.sandboxName}`, 'openshell', sandboxCreateArgs(setup, files, options.image));
    return steps;
  }
  await runStep(`Apply policy to sandbox ${setup.sandboxName}`, 'openshell', [
    'policy',
    'set',
    setup.sandboxName,
    '--policy',
    files.policy,
    '--wait',
  ]);
  if (files.safetyConfig) {
    await runStep(`Upload Safety Mode configuration to ${setup.sandboxName}`, 'openshell', [
      'sandbox',
      'upload',
      '--no-git-ignore',
      setup.sandboxName,
      files.safetyConfig,
      OPENSHELL_SAFETY_CONFIG_PATH,
    ]);
  }

  return steps;
}
